import type { AutoComplianceAuditSupplement } from "./compliance-audit-types";

export const autoComplianceAuditSupplement: AutoComplianceAuditSupplement = {
  pcfCoverageLadder: [
    { band: "Tier 1 — Verified PCF", pct: 22 },
    { band: "Tier 2 — Cradle-to-gate LCA", pct: 36 },
    { band: "Tier 3 — Industry average", pct: 28 },
    { band: "Tier 4 — Spend-based", pct: 11 },
    { band: "No data", pct: 3 },
  ],
  openFindings: [
    {
      id: "F-01",
      source: "Control test",
      severity: "High",
      title: "Cat 11 model — limited assurance scope gap",
      detail: "Internal controls over use-phase proxy not fully tested; fleet LCV telematics pending.",
      owner: "Product Engineering",
      targetDate: "2026-02-15",
      status: "Open",
      linkedControlId: "C-BMM-11",
    },
    {
      id: "F-02",
      source: "Assurance",
      severity: "High",
      title: "BRSR Principle 6 — evidence pack incomplete",
      detail: "4 of 8 disclosure lines lack signed data-owner attestation.",
      owner: "Compliance",
      targetDate: "2026-01-31",
      status: "In progress",
    },
    {
      id: "F-03",
      source: "Evidence",
      severity: "High",
      title: "Cathode Materials Ltd — PCF non-compliant",
      detail: "Supplier flagged; blocks Wave 1 battery coverage in Cat 1.",
      owner: "Procurement",
      targetDate: "2026-03-30",
      status: "Open",
    },
    {
      id: "F-04",
      source: "Control test",
      severity: "Medium",
      title: "Inbound air freight spike — Cat 4 reconciliation",
      detail: "Q3 mode split exceeds policy; GLEC factors not refreshed.",
      owner: "Logistics",
      targetDate: "2026-02-28",
      status: "Open",
    },
    {
      id: "F-05",
      source: "Regulatory",
      severity: "Medium",
      title: "SBTi supplier engagement KPI — below target",
      detail: "41% suppliers with targets vs 67% near-term commitment.",
      owner: "Sustainability",
      targetDate: "2026-04-15",
      status: "In progress",
    },
  ],
  auditorQueries: [
    {
      id: "Q-01",
      subject: "Cat 11 grid factor vintage — India state split",
      askedBy: "EY Assurance",
      assignee: "Sustainability",
      status: "Open",
      dueDate: "2026-02-10",
    },
    {
      id: "Q-02",
      subject: "Tier 1 PCF coverage calculation — FY25 close",
      askedBy: "EY Assurance",
      assignee: "Procurement",
      status: "Open",
      dueDate: "2026-02-18",
    },
    {
      id: "Q-03",
      subject: "Duplicate supplier allocation guard — Cat 1",
      askedBy: "Internal Audit",
      assignee: "Finance Control",
      status: "Answered",
    },
  ],
};
