import type { SupplierNode, SupplierTrendPoint } from "./types";

function trend(base: number, drift = -0.02): SupplierTrendPoint[] {
  return [
    { period: "FY23", tCO2e: Math.round(base * 1.06) },
    { period: "FY24", tCO2e: Math.round(base * 1.03) },
    { period: "FY25", tCO2e: base },
  ];
}

/** Cat 1 supplier-attributed emissions (FY25) — scaled to inventory Cat 1 total (892 kt). */
const CAT1_SUPPLIER_ATTRIBUTION_TCO2E = 892_000;

const RAW_MOCK_SUPPLIERS: SupplierNode[] = [
  {
    id: "s1",
    name: "VoltCell Energy Systems",
    tier: 1,
    tCO2e: 486_000,
    intensity: 4.2,
    compliance: "At risk",
    riskScore: 7.8,
    riskLevel: "High",
    geography: "Gyeonggi",
    country: "South Korea",
    components: ["Battery pack"],
    certifications: ["ISO 14001"],
    plantDestination: "Chennai",
    emissionsTrend: trend(486_000),
    modelIds: ["m1", "m3"],
    spendINRCr: 1184,
    pcfStatus: "Received",
    capStatus: "Open",
    contractRenewal: "2025-Q3",
    scope12Disclosed: true,
  },
  {
    id: "s2",
    name: "ForgeAlloys India",
    tier: 1,
    tCO2e: 312_000,
    intensity: 2.8,
    compliance: "Compliant",
    riskScore: 4.2,
    riskLevel: "Medium",
    geography: "Pune",
    country: "India",
    components: ["Chassis & body"],
    certifications: ["ISO 14001", "IATF 16949"],
    plantDestination: "Pune",
    emissionsTrend: trend(312_000),
    modelIds: ["m2", "m3", "m4"],
    spendINRCr: 756,
    pcfStatus: "Verified",
    capStatus: "None",
    contractRenewal: "2026-Q1",
    scope12Disclosed: true,
  },
  {
    id: "s3",
    name: "Precision Drivetrain Co.",
    tier: 1,
    tCO2e: 248_000,
    intensity: 3.1,
    compliance: "Compliant",
    riskScore: 3.9,
    riskLevel: "Low",
    geography: "Stuttgart",
    country: "Germany",
    components: ["Engine / e-motor"],
    certifications: ["ISO 50001"],
    plantDestination: "Pune",
    emissionsTrend: trend(248_000),
    modelIds: ["m1", "m2", "m3"],
    spendINRCr: 598,
    pcfStatus: "Verified",
    contractRenewal: "2025-Q4",
    scope12Disclosed: true,
  },
  {
    id: "s4",
    name: "SemiconDrive Modules",
    tier: 1,
    tCO2e: 186_000,
    intensity: 2.4,
    compliance: "Compliant",
    riskScore: 3.2,
    riskLevel: "Low",
    geography: "Bangalore",
    country: "India",
    components: ["Electronics"],
    certifications: ["ISO 14001"],
    plantDestination: "Sanand",
    emissionsTrend: trend(186_000),
    modelIds: ["m1", "m2", "m3", "m4"],
    spendINRCr: 448,
    pcfStatus: "Verified",
    contractRenewal: "2026-Q2",
  },
  {
    id: "s5",
    name: "GreenRubber Compounds",
    tier: 1,
    tCO2e: 142_000,
    intensity: 1.9,
    compliance: "Compliant",
    riskScore: 2.8,
    riskLevel: "Low",
    geography: "Chennai",
    country: "India",
    components: ["Tyres & wheels"],
    certifications: ["ISCC"],
    plantDestination: "Chennai",
    emissionsTrend: trend(142_000),
    modelIds: ["m2", "m3", "m4"],
    spendINRCr: 342,
    pcfStatus: "Received",
    contractRenewal: "2025-Q4",
  },
  {
    id: "s6",
    name: "AeroGlass Interiors",
    tier: 1,
    tCO2e: 98_000,
    intensity: 2.1,
    compliance: "At risk",
    riskScore: 5.4,
    riskLevel: "Medium",
    geography: "Pune",
    country: "India",
    components: ["Interior trim"],
    certifications: ["ISO 14001"],
    plantDestination: "Pune",
    emissionsTrend: trend(98_000),
    modelIds: ["m2", "m3", "m4"],
    spendINRCr: 236,
    pcfStatus: "Requested",
    contractRenewal: "2025-Q2",
  },
  {
    id: "s7",
    name: "ThermalSystems Global",
    tier: 1,
    tCO2e: 86_000,
    intensity: 2.6,
    compliance: "Compliant",
    riskScore: 4.0,
    riskLevel: "Medium",
    geography: "Munich",
    country: "Germany",
    components: ["HVAC & thermal"],
    certifications: ["ISO 14001"],
    plantDestination: "Sanand",
    emissionsTrend: trend(86_000),
    modelIds: ["m1", "m2", "m4"],
    spendINRCr: 198,
    pcfStatus: "Verified",
    contractRenewal: "2026-Q1",
  },
  {
    id: "s8",
    name: "Cathode Materials Ltd",
    tier: 2,
    tCO2e: 198_000,
    intensity: 5.6,
    compliance: "Non-compliant",
    riskScore: 8.4,
    riskLevel: "High",
    geography: "Fujian",
    country: "China",
    components: ["Battery pack"],
    certifications: [],
    parentId: "s1",
    plantDestination: "Chennai",
    emissionsTrend: trend(198_000),
    modelIds: ["m1"],
    spendINRCr: 186,
    pcfStatus: "Expired",
    capStatus: "Open",
    contractRenewal: "2025-Q2",
    alternateSupplier: "GreenCathode APAC (qualification)",
  },
  {
    id: "s9",
    name: "Lithium Refine Hub",
    tier: 2,
    tCO2e: 124_000,
    intensity: 6.1,
    compliance: "At risk",
    riskScore: 7.1,
    riskLevel: "High",
    geography: "Perth",
    country: "Australia",
    components: ["Battery pack"],
    certifications: ["ISO 14001"],
    parentId: "s1",
    emissionsTrend: trend(124_000),
    modelIds: ["m1", "m3"],
  },
  {
    id: "s10",
    name: "SteelWorks APAC",
    tier: 2,
    tCO2e: 96_000,
    intensity: 3.8,
    compliance: "Compliant",
    riskScore: 5.0,
    riskLevel: "Medium",
    geography: "Jharkhand",
    country: "India",
    components: ["Chassis & body"],
    certifications: ["ISO 14001"],
    parentId: "s2",
    emissionsTrend: trend(96_000),
    modelIds: ["m2", "m4"],
  },
  {
    id: "s11",
    name: "RareEarth Magnets Co.",
    tier: 3,
    tCO2e: 68_000,
    intensity: 8.2,
    compliance: "At risk",
    riskScore: 6.5,
    riskLevel: "Medium",
    geography: "Jiangxi",
    country: "China",
    components: ["Engine / e-motor"],
    certifications: [],
    parentId: "s3",
    emissionsTrend: trend(68_000),
    modelIds: ["m1", "m3"],
  },
  {
    id: "s12",
    name: "CopperWind GmbH",
    tier: 2,
    tCO2e: 52_000,
    intensity: 4.4,
    compliance: "Compliant",
    riskScore: 4.8,
    riskLevel: "Medium",
    geography: "NRW",
    country: "Germany",
    components: ["Engine / e-motor"],
    certifications: ["ISO 50001"],
    parentId: "s3",
    emissionsTrend: trend(52_000),
    modelIds: ["m1"],
  },
  {
    id: "s13",
    name: "PCB Assembly Taiwan",
    tier: 2,
    tCO2e: 44_000,
    intensity: 3.2,
    compliance: "Compliant",
    riskScore: 3.5,
    riskLevel: "Low",
    geography: "Taoyuan",
    country: "Taiwan",
    components: ["Electronics"],
    certifications: ["ISO 14001"],
    parentId: "s4",
    emissionsTrend: trend(44_000),
    modelIds: ["m1", "m2", "m3", "m4"],
  },
  {
    id: "s14",
    name: "SyntheticRubber SEA",
    tier: 2,
    tCO2e: 38_000,
    intensity: 2.9,
    compliance: "At risk",
    riskScore: 5.2,
    riskLevel: "Medium",
    geography: "Johor",
    country: "Malaysia",
    components: ["Tyres & wheels"],
    certifications: [],
    parentId: "s5",
    emissionsTrend: trend(38_000),
    modelIds: ["m4"],
  },
  {
    id: "s15",
    name: "AlloyCast Sanand",
    tier: 2,
    tCO2e: 34_000,
    intensity: 3.0,
    compliance: "Compliant",
    riskScore: 3.8,
    riskLevel: "Low",
    geography: "Gujarat",
    country: "India",
    components: ["Chassis & body"],
    certifications: ["IATF 16949"],
    parentId: "s2",
    emissionsTrend: trend(34_000),
    modelIds: ["m1", "m3"],
  },
  {
    id: "s16",
    name: "RecycledAlu Europe",
    tier: 2,
    tCO2e: 28_000,
    intensity: 1.6,
    compliance: "Compliant",
    riskScore: 2.2,
    riskLevel: "Low",
    geography: "Antwerp",
    country: "Belgium",
    components: ["Chassis & body"],
    certifications: ["ISCC", "ISO 14001"],
    parentId: "s2",
    emissionsTrend: trend(28_000),
    modelIds: ["m2"],
  },
  {
    id: "s17",
    name: "CellSeparator Tech",
    tier: 3,
    tCO2e: 22_000,
    intensity: 5.1,
    compliance: "At risk",
    riskScore: 6.0,
    riskLevel: "Medium",
    geography: "Osaka",
    country: "Japan",
    components: ["Battery pack"],
    certifications: ["ISO 14001"],
    parentId: "s8",
    emissionsTrend: trend(22_000),
    modelIds: ["m1"],
  },
  {
    id: "s18",
    name: "Graphite Anode Supply",
    tier: 3,
    tCO2e: 18_000,
    intensity: 4.8,
    compliance: "Compliant",
    riskScore: 4.5,
    riskLevel: "Medium",
    geography: "Heilongjiang",
    country: "China",
    components: ["Battery pack"],
    certifications: [],
    parentId: "s8",
    emissionsTrend: trend(18_000),
    modelIds: ["m1", "m3"],
  },
  {
    id: "s19",
    name: "WiringHarness Pune",
    tier: 2,
    tCO2e: 26_000,
    intensity: 2.2,
    compliance: "Compliant",
    riskScore: 3.0,
    riskLevel: "Low",
    geography: "Pune",
    country: "India",
    components: ["Electronics"],
    certifications: ["IATF 16949"],
    parentId: "s4",
    emissionsTrend: trend(26_000),
    modelIds: ["m2", "m4"],
  },
  {
    id: "s20",
    name: "Adhesives & Sealants EU",
    tier: 2,
    tCO2e: 16_000,
    intensity: 2.5,
    compliance: "Compliant",
    riskScore: 3.4,
    riskLevel: "Low",
    geography: "Lyon",
    country: "France",
    components: ["Interior trim"],
    certifications: ["ISO 14001"],
    parentId: "s6",
    emissionsTrend: trend(16_000),
    modelIds: ["m3"],
  },
  {
    id: "s21",
    name: "Compressor India",
    tier: 2,
    tCO2e: 14_000,
    intensity: 2.7,
    compliance: "Compliant",
    riskScore: 3.6,
    riskLevel: "Low",
    geography: "Chennai",
    country: "India",
    components: ["HVAC & thermal"],
    certifications: ["ISO 14001"],
    parentId: "s7",
    emissionsTrend: trend(14_000),
    modelIds: ["m2", "m4"],
  },
  {
    id: "s22",
    name: "GlassFab Korea",
    tier: 2,
    tCO2e: 12_000,
    intensity: 3.3,
    compliance: "Compliant",
    riskScore: 4.1,
    riskLevel: "Medium",
    geography: "Ulsan",
    country: "South Korea",
    components: ["Interior trim"],
    certifications: ["ISO 14001"],
    parentId: "s6",
    emissionsTrend: trend(12_000),
    modelIds: ["m1", "m4"],
  },
  {
    id: "s23",
    name: "BrakeSystems Italy",
    tier: 1,
    tCO2e: 74_000,
    intensity: 2.3,
    compliance: "Compliant",
    riskScore: 3.1,
    riskLevel: "Low",
    geography: "Turin",
    country: "Italy",
    components: ["Brakes & safety"],
    certifications: ["ISO 14001", "IATF 16949"],
    plantDestination: "Sanand",
    emissionsTrend: trend(74_000),
    modelIds: ["m2", "m3", "m4"],
  },
  {
    id: "s24",
    name: "PaintShop Solutions",
    tier: 2,
    tCO2e: 20_000,
    intensity: 3.6,
    compliance: "At risk",
    riskScore: 5.8,
    riskLevel: "Medium",
    geography: "Pune",
    country: "India",
    components: ["Coatings"],
    certifications: ["ISO 14001"],
    emissionsTrend: trend(20_000),
    modelIds: ["m2", "m3", "m4"],
  },
];

function scaleSupplierRegister(suppliers: SupplierNode[]): SupplierNode[] {
  const rawSum = suppliers.reduce((a, s) => a + s.tCO2e, 0);
  const scaled = suppliers.map((s) => {
    const tCO2e = Math.round((s.tCO2e * CAT1_SUPPLIER_ATTRIBUTION_TCO2E) / rawSum);
    const scale = tCO2e / s.tCO2e;
    return {
      ...s,
      tCO2e,
      emissionsTrend: s.emissionsTrend?.map((p) => ({ ...p, tCO2e: Math.round(p.tCO2e * scale) })),
    };
  });
  const drift = CAT1_SUPPLIER_ATTRIBUTION_TCO2E - scaled.reduce((a, s) => a + s.tCO2e, 0);
  if (drift !== 0) {
    const top = scaled.reduce((best, s, i, arr) => (s.tCO2e > arr[best]!.tCO2e ? i : best), 0);
    const adj = scaled[top]!;
    scaled[top] = {
      ...adj,
      tCO2e: adj.tCO2e + drift,
      emissionsTrend: adj.emissionsTrend?.map((p, i, arr) =>
        i === arr.length - 1 ? { ...p, tCO2e: adj.tCO2e + drift } : p,
      ),
    };
  }
  return scaled;
}

export const MOCK_SUPPLIERS = scaleSupplierRegister(RAW_MOCK_SUPPLIERS);

export const MOCK_SUPPLY_EDGES = [
  { from: "s8", to: "s1" },
  { from: "s9", to: "s1" },
  { from: "s17", to: "s8" },
  { from: "s18", to: "s8" },
  { from: "s10", to: "s2" },
  { from: "s15", to: "s2" },
  { from: "s16", to: "s2" },
  { from: "s11", to: "s3" },
  { from: "s12", to: "s3" },
  { from: "s13", to: "s4" },
  { from: "s19", to: "s4" },
  { from: "s14", to: "s5" },
  { from: "s20", to: "s6" },
  { from: "s22", to: "s6" },
  { from: "s21", to: "s7" },
  { from: "s1", to: "plant" },
  { from: "s2", to: "plant" },
  { from: "s3", to: "plant" },
  { from: "s4", to: "plant" },
  { from: "s5", to: "plant" },
  { from: "s6", to: "plant" },
  { from: "s7", to: "plant" },
  { from: "s23", to: "plant" },
];
