import type { EmissionRecord } from "./types";

/** Granular emissions register — 48 line items across categories, plants, and models. */
export const MOCK_EMISSION_RECORDS: EmissionRecord[] = [
  { id: "e01", category: "Cat 1", ghgCategory: 1, source: "VoltCell Energy Systems", period: "FY25 Q4", tCO2e: 122_000, quality: "Actual", confidence: 91, vehicleModel: "BMM Nex EV", supplierId: "s1", geography: "South Korea" },
  { id: "e02", category: "Cat 1", ghgCategory: 1, source: "ForgeAlloys India", period: "FY25 Q4", tCO2e: 78_000, quality: "Actual", confidence: 88, vehicleModel: "BMM Urban ICE", supplierId: "s2", geography: "India" },
  { id: "e03", category: "Cat 1", ghgCategory: 1, source: "Precision Drivetrain Co.", period: "FY25 Q4", tCO2e: 62_000, quality: "Actual", confidence: 86, supplierId: "s3", geography: "Germany" },
  { id: "e04", category: "Cat 1", ghgCategory: 1, source: "SemiconDrive Modules", period: "FY25 Q3", tCO2e: 46_500, quality: "Actual", confidence: 84, geography: "India" },
  { id: "e05", category: "Cat 1", ghgCategory: 1, source: "GreenRubber Compounds", period: "FY25 Q3", tCO2e: 35_500, quality: "Estimated", confidence: 76, vehicleModel: "BMM Fleet LCV", supplierId: "s5" },
  { id: "e06", category: "Cat 1", ghgCategory: 1, source: "Cathode Materials Ltd", period: "FY25 Q4", tCO2e: 49_500, quality: "Estimated", confidence: 62, supplierId: "s8", geography: "China" },
  { id: "e07", category: "Cat 1", ghgCategory: 1, source: "AeroGlass Interiors", period: "FY25 Q2", tCO2e: 24_500, quality: "Estimated", confidence: 71, geography: "India" },
  { id: "e08", category: "Cat 1", ghgCategory: 1, source: "BrakeSystems Italy", period: "FY25 Q4", tCO2e: 18_500, quality: "Actual", confidence: 89, supplierId: "s23", geography: "Italy" },
  { id: "e09", category: "Cat 2", ghgCategory: 2, source: "Paint line capex — Pune", period: "FY25", tCO2e: 28_000, quality: "Estimated", confidence: 68 },
  { id: "e10", category: "Cat 4", ghgCategory: 4, source: "Road freight — Pune hub", period: "FY25 Q4", tCO2e: 52_000, quality: "Estimated", confidence: 74, geography: "India" },
  { id: "e11", category: "Cat 4", ghgCategory: 4, source: "Sea freight — Chennai port", period: "FY25 Q4", tCO2e: 38_000, quality: "Actual", confidence: 82, geography: "India" },
  { id: "e12", category: "Cat 4", ghgCategory: 4, source: "Air freight — KR battery cells", period: "FY25 Q3", tCO2e: 12_800, quality: "Actual", confidence: 85, supplierId: "s1", geography: "South Korea" },
  { id: "e13", category: "Cat 4", ghgCategory: 4, source: "Road — Sanand inbound", period: "FY25 Q2", tCO2e: 28_400, quality: "Estimated", confidence: 70, geography: "India" },
  { id: "e14", category: "Cat 4", ghgCategory: 4, source: "Sea — Hamburg to Mumbai", period: "FY25 Q1", tCO2e: 22_600, quality: "Estimated", confidence: 72, geography: "Germany" },
  { id: "e15", category: "Cat 4", ghgCategory: 4, source: "Road — cross-plant transfer", period: "FY25 Q4", tCO2e: 14_200, quality: "Proxy", confidence: 58 },
  { id: "e16", category: "Cat 5", ghgCategory: 5, source: "Plant waste — Pune", period: "FY25", tCO2e: 22_000, quality: "Estimated", confidence: 65 },
  { id: "e17", category: "Cat 5", ghgCategory: 5, source: "Plant waste — Chennai", period: "FY25", tCO2e: 12_000, quality: "Estimated", confidence: 63 },
  { id: "e18", category: "Cat 5", ghgCategory: 5, source: "Hazardous treatment", period: "FY25", tCO2e: 8_000, quality: "Proxy", confidence: 55 },
  { id: "e19", category: "Cat 6", ghgCategory: 6, source: "Business travel — domestic", period: "FY25", tCO2e: 5_200, quality: "Estimated", confidence: 72 },
  { id: "e20", category: "Cat 6", ghgCategory: 6, source: "Business travel — international", period: "FY25", tCO2e: 2_800, quality: "Estimated", confidence: 68 },
  { id: "e21", category: "Cat 7", ghgCategory: 7, source: "Employee commuting — Pune", period: "FY25", tCO2e: 2_400, quality: "Proxy", confidence: 52 },
  { id: "e22", category: "Cat 7", ghgCategory: 7, source: "Employee commuting — Chennai", period: "FY25", tCO2e: 1_600, quality: "Proxy", confidence: 50 },
  { id: "e23", category: "Cat 9", ghgCategory: 9, source: "Dealer delivery logistics", period: "FY25", tCO2e: 28_000, quality: "Estimated", confidence: 66 },
  { id: "e24", category: "Cat 9", ghgCategory: 9, source: "Spare parts distribution", period: "FY25", tCO2e: 20_000, quality: "Proxy", confidence: 58 },
  { id: "e25", category: "Cat 11", ghgCategory: 11, source: "Nex EV — grid electricity use", period: "FY25", tCO2e: 892_000, quality: "Actual", confidence: 78, vehicleModel: "BMM Nex EV" },
  { id: "e26", category: "Cat 11", ghgCategory: 11, source: "Urban ICE — fuel combustion", period: "FY25", tCO2e: 1_248_000, quality: "Proxy", confidence: 64, vehicleModel: "BMM Urban ICE" },
  { id: "e27", category: "Cat 11", ghgCategory: 11, source: "Cross Hybrid — blended", period: "FY25", tCO2e: 486_000, quality: "Proxy", confidence: 62, vehicleModel: "BMM Cross Hybrid" },
  { id: "e28", category: "Cat 11", ghgCategory: 11, source: "Fleet LCV — diesel use", period: "FY25", tCO2e: 878_000, quality: "Proxy", confidence: 60, vehicleModel: "BMM Fleet LCV" },
  { id: "e29", category: "Cat 11", ghgCategory: 11, source: "ICCT India lifetime km", period: "FY25 Q4", tCO2e: 124_000, quality: "Proxy", confidence: 58 },
  { id: "e30", category: "Cat 12", ghgCategory: 12, source: "Recycler consortium — metals", period: "FY25", tCO2e: 42_000, quality: "Estimated", confidence: 55 },
  { id: "e31", category: "Cat 12", ghgCategory: 12, source: "Battery EOL — 2nd life", period: "FY25", tCO2e: 28_000, quality: "Estimated", confidence: 52, vehicleModel: "BMM Nex EV" },
  { id: "e32", category: "Cat 12", ghgCategory: 12, source: "Shredder residue", period: "FY25", tCO2e: 26_000, quality: "Proxy", confidence: 48 },
  { id: "e33", category: "Cat 1", ghgCategory: 1, source: "ThermalSystems Global", period: "FY25 Q1", tCO2e: 21_500, quality: "Actual", confidence: 87, supplierId: "s7" },
  { id: "e34", category: "Cat 1", ghgCategory: 1, source: "Lithium Refine Hub", period: "FY25 Q2", tCO2e: 31_000, quality: "Estimated", confidence: 66, supplierId: "s9", geography: "Australia" },
  { id: "e35", category: "Cat 4", ghgCategory: 4, source: "Taiwan electronics air", period: "FY25 Q2", tCO2e: 6_400, quality: "Actual", confidence: 80, supplierId: "s13", geography: "Taiwan" },
  { id: "e36", category: "Cat 1", ghgCategory: 1, source: "RecycledAlu Europe", period: "FY25 Q3", tCO2e: 7_000, quality: "Actual", confidence: 90, supplierId: "s16", geography: "Belgium" },
  { id: "e37", category: "Cat 11", ghgCategory: 11, source: "Nex EV — FY24 baseline", period: "FY24", tCO2e: 918_000, quality: "Proxy", confidence: 61, vehicleModel: "BMM Nex EV" },
  { id: "e38", category: "Cat 11", ghgCategory: 11, source: "Urban ICE — FY24", period: "FY24", tCO2e: 1_286_000, quality: "Proxy", confidence: 60, vehicleModel: "BMM Urban ICE" },
  { id: "e39", category: "Cat 4", ghgCategory: 4, source: "Malaysia rubber sea", period: "FY25 Q3", tCO2e: 9_200, quality: "Estimated", confidence: 73, supplierId: "s14", geography: "Malaysia" },
  { id: "e40", category: "Cat 1", ghgCategory: 1, source: "PaintShop Solutions", period: "FY25 Q4", tCO2e: 5_000, quality: "Estimated", confidence: 69, supplierId: "s24" },
  { id: "e41", category: "Cat 4", ghgCategory: 4, source: "Belgium recycled alu road", period: "FY25 Q2", tCO2e: 3_800, quality: "Estimated", confidence: 71, geography: "Belgium" },
  { id: "e42", category: "Cat 11", ghgCategory: 11, source: "Cross Hybrid Q4", period: "FY25 Q4", tCO2e: 121_500, quality: "Proxy", confidence: 59, vehicleModel: "BMM Cross Hybrid" },
  { id: "e43", category: "Cat 1", ghgCategory: 1, source: "WiringHarness Pune", period: "FY25 Q1", tCO2e: 6_500, quality: "Actual", confidence: 83, supplierId: "s19" },
  { id: "e44", category: "Cat 9", ghgCategory: 9, source: "Export CKD logistics", period: "FY25", tCO2e: 12_000, quality: "Estimated", confidence: 64 },
  { id: "e45", category: "Cat 12", ghgCategory: 12, source: "EOL — Fleet LCV", period: "FY25", tCO2e: 18_000, quality: "Proxy", confidence: 47, vehicleModel: "BMM Fleet LCV" },
  { id: "e46", category: "Cat 1", ghgCategory: 1, source: "GlassFab Korea", period: "FY25 Q3", tCO2e: 3_000, quality: "Actual", confidence: 85, supplierId: "s22" },
  { id: "e47", category: "Cat 4", ghgCategory: 4, source: "China cathode sea", period: "FY25 Q4", tCO2e: 11_400, quality: "Estimated", confidence: 70, supplierId: "s8", geography: "China" },
  { id: "e48", category: "Cat 11", ghgCategory: 11, source: "Sanand plant allocation", period: "FY25 Q4", tCO2e: 48_000, quality: "Proxy", confidence: 54 },
];
