import type { AutomotiveScope3MockData } from "./types";
import {
  MOCK_CAT11,
  MOCK_CATEGORY_OWNERS,
  MOCK_FINANCIAL_KPIS,
  MOCK_INVESTMENT_PIPELINE,
  MOCK_METHODOLOGY,
  MOCK_PLANT_SLICES,
  MOCK_REPORTING_CONTEXT,
  MOCK_RESTATEMENTS,
  MOCK_SBTI,
  MOCK_SUPPLIER_PROGRAMME,
  MOCK_VARIANCE_BRIDGE,
} from "./mockData-business";
import { MOCK_EMISSION_RECORDS } from "./mockData-records";
import { MOCK_SUPPLIERS, MOCK_SUPPLY_EDGES } from "./mockData-suppliers";
import { buildAutoComplianceAuditPage } from "./compliance-audit-build";
import { autoComplianceAuditSupplement } from "./compliance-audit-supplement";
import {
  MOCK_CFO_PNL_CARBON,
  MOCK_CSO_ASSURANCE_GAPS,
  MOCK_DATA_QUALITY_GAPS,
  MOCK_MODEL_CARBON_ECONOMICS,
  MOCK_PERSONA_INSIGHTS,
  MOCK_PROCUREMENT_SCORECARDS,
  MOCK_SUPPLIER_DRILL,
} from "./mockData-persona-drilldowns";

/** Reconciled FY25 Scope 3 total — all category % sum to 100%; upstream + downstream = total. */
export const SCOPE3_TOTAL_TCO2E = 4_820_000;

const CAT1 = 892_000;
const CAT2 = 28_000;
const CAT4 = 198_000;
const CAT5 = 42_000;
const CAT6 = 8_000;
const CAT7 = 4_000;
const CAT9 = 48_000;
const CAT11 = 3_504_000;
const CAT12 = 96_000;

function pct(n: number): number {
  return Math.round((n / SCOPE3_TOTAL_TCO2E) * 1000) / 10;
}

const MONTHLY = [
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
  "Jan",
  "Feb",
  "Mar",
].map((period, i) => ({
  period,
  tCO2e: Math.round(412_000 - i * 3_100),
}));

function modelTrend(scale: number) {
  return MONTHLY.map((m) => ({ ...m, tCO2e: Math.round(m.tCO2e * scale) }));
}

export const automotiveScope3MockData: AutomotiveScope3MockData = {
  accountingNote:
    "FY25 inventory (Mar 2025 close). Scope 3 categories sum to 4.82 Mt (mutually exclusive). Production 312,400 units · sales 298,600 (13.8k dealer/demo stock). Supplier register attributes 892 kt to Cat 1. Model lifecycle intensities (tCO₂e/vehicle) are full LCA-style; annual inventory allocation uses production share %.",
  company: {
    legalName: "Bharat Mobility Motors Ltd",
    shortName: "BMM",
    brsrTier: "BRSR Core — Top 250",
    hq: "Pune, Maharashtra",
    plants: ["Pune", "Chennai", "Sanand"],
    vehicleModels: ["All models", "BMM Nex EV", "BMM Urban ICE", "BMM Cross Hybrid", "BMM Fleet LCV"],
    reportingFY: "FY2024-25",
    lastInventoryClose: "2025-03-31",
    scope3TCO2e: SCOPE3_TOTAL_TCO2E,
    vehiclesProducedFY: 312_400,
    revenueINRCr: 5720,
  },
  overview: {
    totalScope3TCO2e: SCOPE3_TOTAL_TCO2E,
    emissionsPerVehicleTCO2e: Math.round((SCOPE3_TOTAL_TCO2E / 312_400) * 10) / 10,
    usePhasePct: pct(CAT11),
    evSharePct: 32,
    yoyChangePct: -2.3,
    topSupplierContributionPct: pct(MOCK_SUPPLIERS[0]!.tCO2e),
  },
  lifecycle: [
    { phase: "Production", iceTCO2e: 724_000, evTCO2e: 448_000 },
    { phase: "Use phase", iceTCO2e: 2_412_000, evTCO2e: 1_092_000 },
    { phase: "End-of-life", iceTCO2e: 58_000, evTCO2e: 38_000 },
  ],
  emissionsTrend: MONTHLY,
  emissionsTrendByModel: {
    "BMM Nex EV": modelTrend(0.22),
    "BMM Urban ICE": modelTrend(0.34),
    "BMM Cross Hybrid": modelTrend(0.18),
    "BMM Fleet LCV": modelTrend(0.26),
  },
  topSuppliers: MOCK_SUPPLIERS.slice(0, 5).map((s, i) => ({
    id: s.id,
    name: s.name,
    tCO2e: s.tCO2e,
    pct: pct(s.tCO2e),
    kind: "supplier" as const,
  })),
  topComponents: [
    { id: "c1", name: "Battery pack", kind: "component", tCO2e: 612_000, pct: pct(612_000) },
    { id: "c2", name: "Engine / e-motor", kind: "component", tCO2e: 368_000, pct: pct(368_000) },
    { id: "c3", name: "Chassis & body", kind: "component", tCO2e: 294_000, pct: pct(294_000) },
    { id: "c4", name: "Electronics", kind: "component", tCO2e: 186_000, pct: pct(186_000) },
    { id: "c5", name: "Tyres & wheels", kind: "component", tCO2e: 142_000, pct: pct(142_000) },
  ],
  quickInsights: [
    { id: "qi1", text: `${pct(CAT11)}% of Scope 3 is use phase (Cat 11) — EV mix at 32% is the highest-leverage decarbonisation lever.`, severity: "info" },
    { id: "qi2", text: "Battery pack and Tier-2 cathode supply account for ~40% of production-phase (Cat 1) emissions.", severity: "warning" },
    { id: "qi3", text: "Cathode Materials Ltd is non-compliant with 8.4 risk score — engage or qualify alternate by Q2 FY26.", severity: "critical" },
    { id: "qi4", text: "CFO: Shadow carbon ₹443 Cr flat YoY — intensity −2.3% offset by volume; Fleet LCV margin-at-risk ₹124 Cr.", severity: "warning" },
    { id: "qi5", text: "Data quality: 84% completeness — Cat 11 proxy (60% confidence) is primary assurance blocker.", severity: "warning" },
  ],
  suppliers: MOCK_SUPPLIERS,
  supplyEdges: MOCK_SUPPLY_EDGES,
  tierBreakdown: [
    { tier: 1, tCO2e: MOCK_SUPPLIERS.filter((s) => s.tier === 1).reduce((a, s) => a + s.tCO2e, 0) },
    { tier: 2, tCO2e: MOCK_SUPPLIERS.filter((s) => s.tier === 2).reduce((a, s) => a + s.tCO2e, 0) },
    { tier: 3, tCO2e: MOCK_SUPPLIERS.filter((s) => s.tier === 3).reduce((a, s) => a + s.tCO2e, 0) },
  ],
  valueChainCategories: [
    { id: "cat1", label: "Purchased goods & services", stream: "Upstream", tCO2e: CAT1, pct: pct(CAT1), ghgCategory: 1 },
    { id: "cat2", label: "Capital goods", stream: "Upstream", tCO2e: CAT2, pct: pct(CAT2), ghgCategory: 2 },
    { id: "cat4", label: "Upstream transportation", stream: "Upstream", tCO2e: CAT4, pct: pct(CAT4), ghgCategory: 4 },
    { id: "cat5", label: "Waste generated in operations", stream: "Upstream", tCO2e: CAT5, pct: pct(CAT5), ghgCategory: 5 },
    { id: "cat6", label: "Business travel", stream: "Upstream", tCO2e: CAT6, pct: pct(CAT6), ghgCategory: 6 },
    { id: "cat7", label: "Employee commuting", stream: "Upstream", tCO2e: CAT7, pct: pct(CAT7), ghgCategory: 7 },
    { id: "cat9", label: "Downstream transportation", stream: "Downstream", tCO2e: CAT9, pct: pct(CAT9), ghgCategory: 9 },
    { id: "cat11", label: "Use of sold products", stream: "Downstream", tCO2e: CAT11, pct: pct(CAT11), ghgCategory: 11 },
    { id: "cat12", label: "End-of-life treatment", stream: "Downstream", tCO2e: CAT12, pct: pct(CAT12), ghgCategory: 12 },
  ],
  sankeyFlows: [
    { from: "Raw materials", to: "Tier 2/3 suppliers", value: 412_000 },
    { from: "Tier 2/3 suppliers", to: "Tier 1 suppliers", value: 892_000 },
    { from: "Tier 1 suppliers", to: "Vehicle assembly", value: 892_000 },
    { from: "Vehicle assembly", to: "Use phase", value: CAT11 },
    { from: "Use phase", to: "End-of-life", value: CAT12 },
  ],
  upstreamTotal: CAT1 + CAT2 + CAT4 + CAT5 + CAT6 + CAT7,
  downstreamTotal: CAT9 + CAT11 + CAT12,
  components: [
    {
      id: "c1",
      name: "Battery pack",
      tCO2e: 612_000,
      pct: pct(612_000),
      materials: [
        { material: "Lithium-ion cells", pct: 62 },
        { material: "Aluminium casing", pct: 18 },
        { material: "BMS electronics", pct: 12 },
      ],
      topSuppliers: [{ name: "VoltCell Energy Systems", pct: 72 }],
      lowCarbonAlternative: "Low-carbon cathode + increased recycled aluminium casing (−12% intensity)",
      modelIds: ["m1", "m3"],
    },
    {
      id: "c2",
      name: "Engine / e-motor",
      tCO2e: 368_000,
      pct: pct(368_000),
      materials: [
        { material: "Steel alloys", pct: 38 },
        { material: "Copper windings", pct: 24 },
        { material: "Rare-earth magnets", pct: 14 },
      ],
      topSuppliers: [{ name: "Precision Drivetrain Co.", pct: 58 }],
      lowCarbonAlternative: "Reduced rare-earth magnet grade on hybrid line",
      modelIds: ["m1", "m2", "m3"],
    },
    {
      id: "c3",
      name: "Chassis & body",
      tCO2e: 294_000,
      pct: pct(294_000),
      materials: [
        { material: "High-strength steel", pct: 54 },
        { material: "Aluminium", pct: 22 },
      ],
      topSuppliers: [{ name: "ForgeAlloys India", pct: 81 }],
      lowCarbonAlternative: "30% recycled aluminium pilot on Urban ICE",
      modelIds: ["m2", "m3", "m4"],
    },
    {
      id: "c4",
      name: "Electronics",
      tCO2e: 186_000,
      pct: pct(186_000),
      materials: [
        { material: "PCBs", pct: 42 },
        { material: "Semiconductors", pct: 36 },
      ],
      topSuppliers: [{ name: "SemiconDrive Modules", pct: 64 }],
      modelIds: ["m1", "m2", "m3", "m4"],
    },
    {
      id: "c5",
      name: "Tyres & wheels",
      tCO2e: 142_000,
      pct: pct(142_000),
      materials: [
        { material: "Synthetic rubber", pct: 48 },
        { material: "Steel rims", pct: 28 },
      ],
      topSuppliers: [{ name: "GreenRubber Compounds", pct: 88 }],
      modelIds: ["m2", "m3", "m4"],
    },
    {
      id: "c6",
      name: "Interior trim",
      tCO2e: 98_000,
      pct: pct(98_000),
      materials: [{ material: "Polymers & textiles", pct: 68 }],
      topSuppliers: [{ name: "AeroGlass Interiors", pct: 76 }],
      modelIds: ["m2", "m3", "m4"],
    },
    {
      id: "c7",
      name: "HVAC & thermal",
      tCO2e: 86_000,
      pct: pct(86_000),
      materials: [{ material: "Refrigerants & compressors", pct: 55 }],
      topSuppliers: [{ name: "ThermalSystems Global", pct: 82 }],
      modelIds: ["m1", "m2", "m4"],
    },
  ],
  vehicleModels: [
    { id: "m1", name: "BMM Nex EV", powertrain: "EV", productionTCO2e: 8.2, usePhaseTCO2e: 22.4, eolTCO2e: 0.6, lifecycleTCO2e: 31.2, unitsProduced: 99_968, shareOfScope3Pct: 22 },
    { id: "m2", name: "BMM Urban ICE", powertrain: "ICE", productionTCO2e: 5.1, usePhaseTCO2e: 38.6, eolTCO2e: 0.8, lifecycleTCO2e: 44.5, unitsProduced: 118_712, shareOfScope3Pct: 34 },
    { id: "m3", name: "BMM Cross Hybrid", powertrain: "Hybrid", productionTCO2e: 6.4, usePhaseTCO2e: 28.2, eolTCO2e: 0.7, lifecycleTCO2e: 35.3, unitsProduced: 56_232, shareOfScope3Pct: 18 },
    { id: "m4", name: "BMM Fleet LCV", powertrain: "ICE", productionTCO2e: 6.8, usePhaseTCO2e: 52.1, eolTCO2e: 1.1, lifecycleTCO2e: 60.0, unitsProduced: 37_488, shareOfScope3Pct: 26 },
  ],
  geography: [
    { country: "India", iso: "IN", tCO2e: 2_140_000, intensity: 0.82, supplierCount: 12, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.71 },
    { country: "China", iso: "CN", tCO2e: 386_000, intensity: 0.58, supplierCount: 4, regulatoryRisk: "Medium", gridIntensityKgPerKwh: 0.55 },
    { country: "South Korea", iso: "KR", tCO2e: 512_000, intensity: 0.45, supplierCount: 2, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.42 },
    { country: "Germany", iso: "DE", tCO2e: 406_000, intensity: 0.38, supplierCount: 3, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.39 },
    { country: "Australia", iso: "AU", tCO2e: 124_000, intensity: 0.62, supplierCount: 1, regulatoryRisk: "Medium", gridIntensityKgPerKwh: 0.65 },
    { country: "Italy", iso: "IT", tCO2e: 74_000, intensity: 0.41, supplierCount: 1, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.33 },
    { country: "Taiwan", iso: "TW", tCO2e: 44_000, intensity: 0.48, supplierCount: 1, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.51 },
    { country: "Belgium", iso: "BE", tCO2e: 28_000, intensity: 0.35, supplierCount: 1, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.17 },
    { country: "Malaysia", iso: "MY", tCO2e: 38_000, intensity: 0.52, supplierCount: 1, regulatoryRisk: "Medium", gridIntensityKgPerKwh: 0.58 },
    { country: "Japan", iso: "JP", tCO2e: 22_000, intensity: 0.44, supplierCount: 1, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.47 },
    { country: "France", iso: "FR", tCO2e: 16_000, intensity: 0.36, supplierCount: 1, regulatoryRisk: "Low", gridIntensityKgPerKwh: 0.05 },
  ],
  logisticsRoutes: [
    { id: "lr1", from: "Busan, KR", to: "Chennai plant", plant: "Chennai", mode: "Sea", tCO2e: 28_400, distanceKm: 6200, supplierId: "s1" },
    { id: "lr2", from: "Busan, KR", to: "Chennai plant", plant: "Chennai", mode: "Air", tCO2e: 12_800, distanceKm: 6200, supplierId: "s1" },
    { id: "lr3", from: "Stuttgart, DE", to: "Pune plant", plant: "Pune", mode: "Road", tCO2e: 18_200, distanceKm: 6800, supplierId: "s3" },
    { id: "lr4", from: "Fujian, CN", to: "Chennai plant", plant: "Chennai", mode: "Sea", tCO2e: 14_600, distanceKm: 4800, supplierId: "s8" },
    { id: "lr5", from: "Jharkhand, IN", to: "Pune plant", plant: "Pune", mode: "Road", tCO2e: 8_400, distanceKm: 1400, supplierId: "s10" },
    { id: "lr6", from: "Antwerp, BE", to: "Pune plant", plant: "Pune", mode: "Sea", tCO2e: 6_200, distanceKm: 7200, supplierId: "s16" },
    { id: "lr7", from: "Taoyuan, TW", to: "Sanand plant", plant: "Sanand", mode: "Air", tCO2e: 6_400, distanceKm: 5100, supplierId: "s13" },
    { id: "lr8", from: "Perth, AU", to: "Chennai plant", plant: "Chennai", mode: "Sea", tCO2e: 9_800, distanceKm: 5800, supplierId: "s9" },
    { id: "lr9", from: "Pune plant", to: "Sanand plant", plant: "Sanand", mode: "Road", tCO2e: 4_200, distanceKm: 650 },
    { id: "lr10", from: "Chennai plant", to: "Dealer hub — North", plant: "Pune", mode: "Road", tCO2e: 22_000, distanceKm: 2100 },
  ],
  transportModes: [
    { mode: "Road", tCO2e: 136_800, pct: 69.2 },
    { mode: "Sea", tCO2e: 49_800, pct: 25.2 },
    { mode: "Air", tCO2e: 11_200, pct: 5.6 },
  ],
  categoryTracking: [
    {
      ghgCategory: 1,
      label: "Purchased goods & services",
      tCO2e: CAT1,
      pct: pct(CAT1),
      dataQuality: "Actual",
      confidence: 88,
      trend: [
        { period: "FY23", tCO2e: 948_000 },
        { period: "FY24", tCO2e: 918_000 },
        { period: "FY25", tCO2e: CAT1 },
      ],
      monthlyTrend: MONTHLY.map((m, i) => ({ period: m.period, tCO2e: Math.round(74_000 - i * 800) })),
    },
    {
      ghgCategory: 4,
      label: "Upstream transportation",
      tCO2e: CAT4,
      pct: pct(CAT4),
      dataQuality: "Estimated",
      confidence: 72,
      trend: [
        { period: "FY23", tCO2e: 212_000 },
        { period: "FY24", tCO2e: 204_000 },
        { period: "FY25", tCO2e: CAT4 },
      ],
      monthlyTrend: MONTHLY.map((m, i) => ({ period: m.period, tCO2e: Math.round(16_800 - i * 200) })),
    },
    {
      ghgCategory: 11,
      label: "Use of sold products",
      tCO2e: CAT11,
      pct: pct(CAT11),
      dataQuality: "Proxy",
      confidence: 65,
      trend: [
        { period: "FY23", tCO2e: 3_720_000 },
        { period: "FY24", tCO2e: 3_612_000 },
        { period: "FY25", tCO2e: CAT11 },
      ],
      monthlyTrend: MONTHLY.map((m, i) => ({ period: m.period, tCO2e: Math.round(298_000 - i * 2_400) })),
    },
    {
      ghgCategory: 12,
      label: "End-of-life",
      tCO2e: CAT12,
      pct: pct(CAT12),
      dataQuality: "Estimated",
      confidence: 58,
      trend: [
        { period: "FY23", tCO2e: 102_000 },
        { period: "FY24", tCO2e: 98_000 },
        { period: "FY25", tCO2e: CAT12 },
      ],
    },
    {
      ghgCategory: 2,
      label: "Capital goods",
      tCO2e: CAT2,
      pct: pct(CAT2),
      dataQuality: "Estimated",
      confidence: 70,
      trend: [
        { period: "FY23", tCO2e: 32_000 },
        { period: "FY24", tCO2e: 30_000 },
        { period: "FY25", tCO2e: CAT2 },
      ],
    },
    {
      ghgCategory: 5,
      label: "Waste",
      tCO2e: CAT5,
      pct: pct(CAT5),
      dataQuality: "Estimated",
      confidence: 64,
      trend: [
        { period: "FY23", tCO2e: 46_000 },
        { period: "FY24", tCO2e: 44_000 },
        { period: "FY25", tCO2e: CAT5 },
      ],
    },
    {
      ghgCategory: 6,
      label: "Business travel",
      tCO2e: CAT6,
      pct: pct(CAT6),
      dataQuality: "Actual",
      confidence: 82,
      trend: [
        { period: "FY23", tCO2e: 10_000 },
        { period: "FY24", tCO2e: 9_000 },
        { period: "FY25", tCO2e: CAT6 },
      ],
    },
    {
      ghgCategory: 7,
      label: "Employee commuting",
      tCO2e: CAT7,
      pct: pct(CAT7),
      dataQuality: "Proxy",
      confidence: 54,
      trend: [
        { period: "FY23", tCO2e: 5_000 },
        { period: "FY24", tCO2e: 4_500 },
        { period: "FY25", tCO2e: CAT7 },
      ],
    },
    {
      ghgCategory: 9,
      label: "Downstream transportation",
      tCO2e: CAT9,
      pct: pct(CAT9),
      dataQuality: "Estimated",
      confidence: 68,
      trend: [
        { period: "FY23", tCO2e: 52_000 },
        { period: "FY24", tCO2e: 50_000 },
        { period: "FY25", tCO2e: CAT9 },
      ],
    },
  ],
  emissionRecords: MOCK_EMISSION_RECORDS,
  intensityPerVehicle: Math.round((SCOPE3_TOTAL_TCO2E / 312_400) * 10) / 10,
  intensityPerRevenueCr: Math.round(SCOPE3_TOTAL_TCO2E / 5720),
  targets: [
    {
      id: "t1",
      name: "Scope 3 absolute reduction (2030)",
      unit: "tCO2e",
      targetValue: 3_200_000,
      actualValue: SCOPE3_TOTAL_TCO2E,
      status: "At risk",
      dueFY: "FY2030",
      unitLabel: "tCO₂e",
    },
    {
      id: "t2",
      name: "EV production mix",
      unit: "percent",
      targetValue: 45,
      actualValue: 32,
      status: "On track",
      dueFY: "FY2027",
      unitLabel: "% of units",
    },
    {
      id: "t3",
      name: "Tier 1 supplier PCF coverage",
      unit: "coverage_pct",
      targetValue: 90,
      actualValue: 68,
      status: "At risk",
      dueFY: "FY2026",
      unitLabel: "% suppliers",
    },
    {
      id: "t4",
      name: "Battery upstream intensity",
      unit: "intensity",
      targetValue: 3.0,
      actualValue: 4.2,
      status: "Missed",
      dueFY: "FY2026",
      unitLabel: "tCO₂e / kWh pack",
    },
  ],
  pathwayTrend: [
    { fy: "FY22", actual: 5_240_000, required: 5_100_000, sbti: 5_080_000 },
    { fy: "FY23", actual: 5_080_000, required: 4_920_000, sbti: 4_880_000 },
    { fy: "FY24", actual: 4_930_000, required: 4_720_000, sbti: 4_680_000 },
    { fy: "FY25", actual: SCOPE3_TOTAL_TCO2E, required: 4_520_000, sbti: 4_480_000 },
    { fy: "FY26", actual: SCOPE3_TOTAL_TCO2E, required: 4_320_000, sbti: 4_280_000 },
    { fy: "FY30", actual: SCOPE3_TOTAL_TCO2E, required: 3_200_000, sbti: 3_100_000 },
  ],
  opportunities: [
    { id: "o1", title: "Switch cathode supplier to EU low-carbon source", category: "Supply chain", impactTCO2e: 186_000, effort: "High", impact: "High", capexINRCr: 42, owner: "Procurement" },
    { id: "o2", title: "Increase recycled aluminium in chassis", category: "Materials", impactTCO2e: 42_000, effort: "Low", impact: "Medium" },
    { id: "o3", title: "Consolidate Pune–Chennai road freight", category: "Logistics", impactTCO2e: 18_400, effort: "Low", impact: "Low" },
    { id: "o4", title: "Accelerate EV mix to 45% by FY27", category: "Product mix", impactTCO2e: 620_000, effort: "High", impact: "High" },
    { id: "o5", title: "Shift KR inbound cells from air to sea", category: "Logistics", impactTCO2e: 12_800, effort: "Low", impact: "Medium" },
    { id: "o6", title: "Supplier PCF programme — Tier 1 completion", category: "Governance", impactTCO2e: 48_000, effort: "Medium", impact: "Medium" },
    { id: "o7", title: "Low-carbon steel for chassis stampings", category: "Materials", impactTCO2e: 36_000, effort: "Medium", impact: "Medium" },
    { id: "o8", title: "Hybrid thermal system efficiency", category: "Product design", impactTCO2e: 28_000, effort: "Medium", impact: "Low" },
    { id: "o9", title: "Battery second-life before recycling", category: "End-of-life", impactTCO2e: 22_000, effort: "Low", impact: "Low" },
    { id: "o10", title: "Dealer delivery route optimisation", category: "Logistics", impactTCO2e: 14_000, effort: "Low", impact: "Low" },
  ],
  alerts: [
    { id: "a1", message: "Battery upstream intensity target missed for Q4 FY25", severity: "critical" },
    { id: "a2", message: "BRSR Principle 6 evidence pack due in 18 days", severity: "warning" },
    { id: "a3", message: "Cathode Materials Ltd — emissions threshold exceeded", severity: "critical" },
    { id: "a4", message: "Tier 1 PCF coverage at 68% vs 90% FY26 target", severity: "warning" },
  ],
  brsrMapping: [
    { id: "b1", disclosure: "Principle 6 — Essential Indicators", dataPoint: "Scope 3 gross emissions (tCO₂e)", status: "Mapped", evidenceIds: ["ev1", "ev2"] },
    { id: "b2", disclosure: "Principle 6 — Leadership Indicators", dataPoint: "Value chain engagement on emissions", status: "Partial", evidenceIds: ["ev3"] },
    { id: "b3", disclosure: "Section C — ESG", dataPoint: "Supplier due diligence on environment", status: "Mapped", evidenceIds: ["ev4", "ev5"] },
    { id: "b4", disclosure: "Assurance", dataPoint: "Limited assurance on Scope 3 Cat 1 & 11", status: "Partial", evidenceIds: ["ev6"] },
    { id: "b5", disclosure: "Principle 6 — Essential", dataPoint: "Scope 3 intensity per rupee turnover", status: "Mapped", evidenceIds: ["ev2"] },
    { id: "b6", disclosure: "Leadership — Climate", dataPoint: "Science-based targets disclosure", status: "Partial" },
    { id: "b7", disclosure: "Section C", dataPoint: "Product lifecycle environmental impact", status: "Mapped", evidenceIds: ["ev7"] },
    { id: "b8", disclosure: "Assurance", dataPoint: "Internal controls over Cat 11 model", status: "Gap" },
  ],
  auditTrail: [
    { id: "at1", dataSource: "VoltCell PCF v3.2", methodology: "GHG Protocol · supplier-specific", timestamp: "2025-03-12T09:14:00Z", modifiedBy: "sustainability@bmm.in", relatedEvidenceId: "ev1" },
    { id: "at2", dataSource: "Use-phase model — ICCT India", methodology: "Cat 11 · lifetime km proxy", timestamp: "2025-02-28T14:02:00Z", modifiedBy: "system.import", relatedEvidenceId: "ev7" },
    { id: "at3", dataSource: "Road freight ledger", methodology: "Cat 4 · tonne-km factors", timestamp: "2025-03-01T11:30:00Z", modifiedBy: "logistics.ops@bmm.in", relatedEvidenceId: "ev8" },
    { id: "at4", dataSource: "ForgeAlloys PCF refresh", methodology: "Cat 1 · cradle-to-gate", timestamp: "2025-03-08T10:00:00Z", modifiedBy: "procurement@bmm.in", relatedEvidenceId: "ev4" },
    { id: "at5", dataSource: "EOL recycler certificates", methodology: "Cat 12 · treatment splits", timestamp: "2025-02-15T16:45:00Z", modifiedBy: "sustainability@bmm.in", relatedEvidenceId: "ev9" },
    { id: "at6", dataSource: "Board target rebaseline", methodology: "SBTi pathway lock", timestamp: "2025-01-20T11:00:00Z", modifiedBy: "cfo.office@bmm.in" },
  ],
  evidenceDocuments: [
    { id: "ev1", name: "VoltCell PCF v3.2 — Nex EV pack", type: "PCF", supplierId: "s1", category: "Cat 1", uploadedAt: "2025-03-10", version: "3.2", sizeMb: 4.2, approvalStage: "Approved" },
    { id: "ev2", name: "FY25 Scope 3 inventory workbook", type: "LCA", category: "All categories", uploadedAt: "2025-03-28", version: "1.0", sizeMb: 18.6, approvalStage: "Under review" },
    { id: "ev3", name: "Supplier engagement tracker Q4", type: "Boundary memo", category: "Cat 1", uploadedAt: "2025-03-05", version: "Q4", sizeMb: 1.1, approvalStage: "Approved" },
    { id: "ev4", name: "ForgeAlloys ISO 14001 + PCF", type: "Certification", supplierId: "s2", category: "Cat 1", uploadedAt: "2025-02-20", version: "2025", sizeMb: 2.8, approvalStage: "Approved" },
    { id: "ev5", name: "Cathode Materials audit response", type: "Assurance PBC", supplierId: "s8", category: "Cat 1", uploadedAt: "2025-03-15", version: "draft", sizeMb: 0.9, approvalStage: "Draft" },
    { id: "ev6", name: "Limited assurance PBC index", type: "Assurance PBC", category: "BRSR", uploadedAt: "2025-03-01", version: "FY25", sizeMb: 6.4, approvalStage: "Under review" },
    { id: "ev7", name: "ICCT India use-phase memo", type: "LCA", category: "Cat 11", uploadedAt: "2025-01-12", version: "2.1", sizeMb: 3.2, approvalStage: "Approved" },
    { id: "ev8", name: "Inbound freight invoices Q4", type: "Invoice", category: "Cat 4", uploadedAt: "2025-03-20", version: "Q4", sizeMb: 12.1, approvalStage: "Approved" },
    { id: "ev9", name: "Recycler consortium EOL certificates", type: "Certification", category: "Cat 12", uploadedAt: "2025-02-14", version: "FY25", sizeMb: 2.2, approvalStage: "Approved" },
  ],
  approvalWorkflow: [
    { id: "aw1", subject: "FY25 Scope 3 inventory — management sign-off", stage: "Under review", reviewer: "CFO office", updatedAt: "2025-03-29T10:00:00Z", comment: "Awaiting Cat 11 model sensitivity" },
    { id: "aw2", subject: "BRSR Principle 6 disclosure pack", stage: "Draft", reviewer: "Compliance", updatedAt: "2025-03-25T14:00:00Z" },
    { id: "aw3", subject: "VoltCell PCF v3.2", stage: "Approved", reviewer: "Head of Sustainability", updatedAt: "2025-03-12T09:30:00Z" },
    { id: "aw4", subject: "Cathode Materials corrective plan", stage: "Rejected", reviewer: "Procurement", updatedAt: "2025-03-18T11:00:00Z", comment: "Resubmit with alternate supplier RFQ" },
  ],
  supplierRiskHeatmap: MOCK_SUPPLIERS.filter((s) => s.tier <= 2)
    .map((s, i) => ({
      supplierId: s.id,
      name: s.name,
      emissionsRank: i + 1,
      compliance: s.compliance,
      quadrant:
        s.compliance === "Non-compliant" || (s.riskLevel === "High" && s.tCO2e > 150_000)
          ? ("Critical" as const)
          : s.compliance === "At risk"
            ? ("Engage" as const)
            : s.tCO2e > 200_000
              ? ("Monitor" as const)
              : ("Leader" as const),
    }))
    .sort((a, b) => a.emissionsRank - b.emissionsRank),
  dataCompletenessPct: 84,
  accuracyByCategory: [
    { category: "Cat 1", score: 86 },
    { category: "Cat 4", score: 72 },
    { category: "Cat 11", score: 64 },
    { category: "Cat 12", score: 58 },
    { category: "Cat 2", score: 70 },
    { category: "Cat 5", score: 62 },
  ],
  recommendations: [
    { id: "r1", category: "Supplier switch", title: "Qualify EU cathode supplier for Nex EV line", trigger: "Tier-2 intensity > 5.5 tCO₂e/unit", action: "Run RFQ with 2030 intensity cap", impactTCO2e: 186_000 },
    { id: "r2", category: "Material substitution", title: "Pilot 30% recycled aluminium in Urban ICE chassis", trigger: "Chassis hotspot rank #3", action: "Engineering sign-off + LCA refresh", impactTCO2e: 42_000 },
    { id: "r3", category: "Logistics optimisation", title: "Shift KR battery cells from air to sea freight", trigger: "Air mode 5.6% of inbound tCO₂e", action: "Re-route via Chennai port buffer", impactTCO2e: 12_800 },
    { id: "r4", category: "Supplier switch", title: "Secondary source for rare-earth magnets", trigger: "Single source via Precision Drivetrain", action: "Dual-source qualification programme", impactTCO2e: 24_000 },
    { id: "r5", category: "Material substitution", title: "Low-carbon steel for ForgeAlloys stampings", trigger: "Cat 1 steel share > 50%", action: "Mass-balance certificates with ISCC", impactTCO2e: 36_000 },
  ],
  insightFeed: [
    {
      id: "if1",
      severity: "Critical",
      category: "Use phase & portfolio",
      headline: "Use phase dominates despite EV ramp",
      body: "EV share is 32% of sales mix but Category 11 still accounts for 72.7% of FY25 Scope 3. Grid factor and lifetime km assumptions for Urban ICE and Fleet LCV drive most of the gap versus SBTi glide path.",
      confidencePct: 92,
      recommendedAction: "Refresh Cat 11 telematics sample for Fleet LCV and publish grid-sensitivity annex before Q1 board pack.",
      expectedImpactTCO2e: 620_000,
      linkedCategoryId: 11,
      workflow: "Open",
      generatedAt: "2025-04-14",
    },
    {
      id: "if2",
      severity: "Critical",
      category: "Supplier Risk",
      headline: "Tier-2 battery concentration risk",
      body: "Cathode active material and lithium refining represent ~38% of Nex EV pack emissions. Cathode Materials Ltd remains non-compliant on PCF — blocks Wave 1 battery coverage.",
      confidencePct: 88,
      recommendedAction: "Escalate procurement hold on cathode POs until site-specific LCA and assurance letter received.",
      expectedImpactTCO2e: 186_000,
      linkedSupplier: "Cathode Materials Ltd",
      linkedCategoryId: 1,
      workflow: "Assigned",
      assignee: "Procurement — Cells",
      generatedAt: "2025-04-11",
    },
    {
      id: "if3",
      severity: "High",
      category: "Anomaly Detection",
      headline: "Air freight spike on KR inbound",
      body: "Q3 air mode share hit 6.4% of inbound Cat 4 tCO₂e vs 4% policy cap. KR→Chennai cell lane is the primary outlier; sea buffer inventory can absorb volume within 6 months.",
      confidencePct: 85,
      recommendedAction: "Lock sea allocation for cathode and cell SKUs through FY26; retire remaining air legs on quarterly logistics review.",
      expectedImpactTCO2e: 12_800,
      linkedCategoryId: 4,
      workflow: "Open",
      generatedAt: "2025-04-09",
    },
    {
      id: "if4",
      severity: "High",
      category: "Use phase & portfolio",
      headline: "Fleet LCV drives Cat 11 mass",
      body: "Fleet LCV is 26% of production volume but ~38% of use-phase proxy emissions due to higher annual km and diesel-heavy duty cycle in the current factor set.",
      confidencePct: 79,
      recommendedAction: "Segment Cat 11 by duty cycle; pilot B2B telematics feed for top 200 fleet accounts before inventory lock.",
      expectedImpactTCO2e: 278_000,
      linkedCategoryId: 11,
      workflow: "Acknowledged",
      generatedAt: "2025-04-06",
    },
    {
      id: "if5",
      severity: "High",
      category: "Data Quality",
      headline: "Cat 12 EoL proxy overstated vs recycler yield",
      body: "End-of-life treatment uses industry-average landfill share; recycler contracts show 18% higher recovery on steel and aluminium streams than the default factor library.",
      confidencePct: 74,
      recommendedAction: "Replace Cat 12 default with mass-balance certificates from Pune and Chennai dismantlers for FY25 close.",
      expectedImpactTCO2e: 48_000,
      linkedCategoryId: 12,
      workflow: "Open",
      generatedAt: "2025-04-03",
    },
    {
      id: "if6",
      severity: "Medium",
      category: "Compliance Gap",
      headline: "BRSR Principle 6 — Tier 2/3 coverage gap",
      body: "Only 44% of Tier 2/3 suppliers by spend have accepted engagement letters. Disclosure narrative cites programme launch but lacks FY25 coverage metric in the workbook.",
      confidencePct: 81,
      recommendedAction: "Attach engagement tracker export to BRSR annex; target 60% spend coverage by Aug 2025.",
      expectedImpactTCO2e: 0,
      workflow: "Assigned",
      assignee: "Compliance — BRSR",
      generatedAt: "2025-03-28",
    },
    {
      id: "if7",
      severity: "Medium",
      category: "Reduction Opportunity",
      headline: "Recycled aluminium pilot on Urban ICE chassis",
      body: "LCA indicates 30% recycled content on chassis stampings reduces Cat 1 intensity by ~4.2% for Urban ICE without capex beyond tooling refresh.",
      confidencePct: 77,
      recommendedAction: "Fast-track engineering sign-off and supplier qualification with ForgeAlloys for Q3 SOP.",
      expectedImpactTCO2e: 42_000,
      linkedCategoryId: 1,
      workflow: "Open",
      generatedAt: "2025-03-22",
    },
    {
      id: "if8",
      severity: "Medium",
      category: "Supplier Risk",
      headline: "Single-source rare-earth magnet exposure",
      body: "Precision Drivetrain GmbH supplies 71% of traction motor magnets; no secondary source qualified for Nex EV or Cross Hybrid.",
      confidencePct: 83,
      recommendedAction: "Run dual-source RFQ with 2030 intensity cap; link outcome to procurement scorecard gate.",
      expectedImpactTCO2e: 24_000,
      linkedSupplier: "Precision Drivetrain GmbH",
      linkedCategoryId: 1,
      workflow: "Open",
      generatedAt: "2025-03-18",
    },
    {
      id: "if9",
      severity: "Low",
      category: "Anomaly Detection",
      headline: "Sanand plant logistics km variance",
      body: "Inbound km per unit at Sanand is 8% above Pune baseline after new Gujarat supplier cluster — within tolerance but trending up two quarters.",
      confidencePct: 68,
      recommendedAction: "Review lane consolidation with 3PL; no immediate inventory restatement required.",
      expectedImpactTCO2e: 3_200,
      linkedCategoryId: 4,
      workflow: "Dismissed",
      dismissReason: "Accepted — monitor on quarterly ops review",
      generatedAt: "2025-03-10",
    },
    {
      id: "if10",
      severity: "Low",
      category: "Data Quality",
      headline: "Scope 3 record count vs executive total",
      body: "48 activity records sum to 4.79 Mt vs 4.82 Mt executive headline — variance within Cat 7 proxy rounding policy.",
      confidencePct: 90,
      recommendedAction: "Document bridge in assurance workpaper; no adjustment before lock.",
      expectedImpactTCO2e: 0,
      workflow: "Acknowledged",
      generatedAt: "2025-03-05",
    },
  ],
  emissionDrivers: [
    { name: "Use of sold products (Cat 11)", pct: pct(CAT11) },
    { name: "Purchased goods & services (Cat 1)", pct: pct(CAT1) },
    { name: "Upstream transportation (Cat 4)", pct: pct(CAT4) },
    { name: "End-of-life treatment (Cat 12)", pct: pct(CAT12) },
    { name: "Downstream transportation (Cat 9)", pct: pct(CAT9) },
  ],
  reportTemplates: [
    { id: "rt1", name: "BRSR Scope 3 Disclosure Report", description: "Principle 6 aligned pack with category tables and assurance footnotes.", format: ["PDF", "Excel"], status: "Ready" },
    { id: "rt2", name: "ESG Executive Summary", description: "Board-ready lifecycle narrative, KPIs, and decarbonisation pathway.", format: ["PDF"], status: "Ready" },
    { id: "rt3", name: "Supplier engagement pack", description: "Tier 1 PCF status, risk heatmap, and engagement tracker.", format: ["PDF", "Excel"], status: "Draft" },
    { id: "rt4", name: "CDP Climate Change — Scope 3 module", description: "CDP-aligned category and methodology disclosure.", format: ["PDF", "Excel"], status: "Draft" },
    { id: "rt5", name: "Board one-pager — Scope 3", description: "5 KPIs, pathway, top 3 risks and actions for board / EXCO.", format: ["PDF"], status: "Ready" },
  ],
  reportSchedules: [
    { id: "rs1", templateId: "rt2", cadence: "Quarterly", nextRun: "2025-06-15", recipients: ["board@bmm.in", "cfo.office@bmm.in"], delivery: "Email" },
    { id: "rs2", templateId: "rt1", cadence: "Quarterly", nextRun: "2025-05-30", recipients: ["compliance@bmm.in"], delivery: "Dashboard" },
    { id: "rs3", templateId: "rt3", cadence: "Monthly", nextRun: "2025-04-28", recipients: ["procurement@bmm.in"], delivery: "Email" },
  ],
  customReportFields: [
    { id: "f1", label: "Total Scope 3 (tCO₂e)", group: "KPI", selected: true },
    { id: "f2", label: "Emissions per vehicle", group: "KPI", selected: true },
    { id: "f3", label: "Category breakdown", group: "Category", selected: true },
    { id: "f4", label: "Top 10 suppliers", group: "Supplier", selected: false },
    { id: "f5", label: "Model lifecycle table", group: "Model", selected: true },
    { id: "f6", label: "Data quality by category", group: "Category", selected: false },
    { id: "f7", label: "SBTi pathway chart", group: "KPI", selected: true },
    { id: "f8", label: "BRSR mapping table", group: "Category", selected: false },
  ],
  globalFilterOptions: {
    vehicleModels: ["All models", "BMM Nex EV", "BMM Urban ICE", "BMM Cross Hybrid", "BMM Fleet LCV"],
    suppliers: ["All suppliers", ...MOCK_SUPPLIERS.filter((s) => s.tier === 1).map((s) => s.name)],
    geographies: ["All regions", "India", "China", "South Korea", "Germany", "Australia", "Italy", "Taiwan", "Belgium", "Malaysia", "Japan", "France"],
    periods: ["FY2024-25", "FY2023-24", "Q4 FY25", "Q3 FY25"],
    plants: ["All plants", "Pune", "Chennai", "Sanand"],
    powertrains: ["All powertrains", "ICE", "EV", "Hybrid"],
    comparePeriods: ["None", "FY2023-24 vs FY2024-25"],
  },
  reportingContext: MOCK_REPORTING_CONTEXT,
  financialKpis: MOCK_FINANCIAL_KPIS,
  varianceBridge: MOCK_VARIANCE_BRIDGE,
  investmentPipeline: MOCK_INVESTMENT_PIPELINE,
  methodologyRegister: MOCK_METHODOLOGY,
  restatementLog: MOCK_RESTATEMENTS,
  cat11Assumptions: MOCK_CAT11,
  supplierProgramme: MOCK_SUPPLIER_PROGRAMME,
  categoryOwners: MOCK_CATEGORY_OWNERS,
  plantSlices: MOCK_PLANT_SLICES,
  sbtiStatus: MOCK_SBTI,
  complianceAudit: autoComplianceAuditSupplement,
  complianceAuditPage: buildAutoComplianceAuditPage(MOCK_SUPPLIERS, 84, autoComplianceAuditSupplement),
  personaInsights: MOCK_PERSONA_INSIGHTS,
  cfoPnlCarbon: MOCK_CFO_PNL_CARBON,
  modelCarbonEconomics: MOCK_MODEL_CARBON_ECONOMICS,
  procurementScorecards: MOCK_PROCUREMENT_SCORECARDS,
  dataQualityGaps: MOCK_DATA_QUALITY_GAPS,
  csoAssuranceGaps: MOCK_CSO_ASSURANCE_GAPS,
  supplierDrillById: MOCK_SUPPLIER_DRILL,
};
