import type { BankAuditReadiness, BankControlRegisterRow, BankInventoryMeta } from "./types";

export const bankInventoryMeta: BankInventoryMeta = {
  reportingYearLabel: "FY2024–25 (1 Apr 2024 – 31 Mar 2025)",
  methodologyVersion:
    "PCAF Financial Institutions Standard v2 · GHG Protocol Scope 3 (Categories 1–8 operational + Category 15 financed) · BRSR Core KPI mapping · India grid & sector EF registry lock FY25",
  organizationalBoundary:
    "Consolidated scheduled commercial bank boundary per Companies Act — includes domestic branches, project finance SPV exposures where economic share is attributed, and listed equity & bond holdings at EVIC share. Foreign offices (Singapore, Dubai, London) carved per boundary memo BAX-BND-2025-04. Sovereign bonds use production-based PCAF sovereign methodology.",
  dataFreshnessNote:
    "Illustrative mock pack: financed emissions total reconciles to executive Category 15 roll-up (~417.4 Mt); control tests and evidence links are synthetic for UX validation.",
};

export const bankAuditReadiness: BankAuditReadiness = {
  overallPct: 73,
  dimensions: [
    {
      key: "completeness",
      label: "Borrower & exposure data completeness",
      score: 76,
      status: "Adequate",
      missing: "SME & trade finance sleeves below 35% primary-data coverage; 6 top emitters without FY25 transition milestones.",
      recommendedAction: "Expand annual climate questionnaire; tie PCAF ladder targets to credit covenants for Score 4–5 exposures.",
    },
    {
      key: "methodology",
      label: "PCAF methodology & policy documentation",
      score: 82,
      status: "Strong",
      missing: "Minor cross-links between attribution workbook versions and sector EF registry tags.",
      recommendedAction: "Publish FI calculation manual vNext with option-level decision trees per asset class.",
    },
    {
      key: "trail",
      label: "Attribution audit trail & change control",
      score: 64,
      status: "Weak",
      missing: "Attribution workbook change log sparse; YoY reconciliation memo not signed for BRSR Core tie-out.",
      recommendedAction: "Enable controlled versioning in GRC tool; quarterly sample over manual adjustments.",
    },
    {
      key: "factors",
      label: "Emission factor governance",
      score: 71,
      status: "Adequate",
      missing: "DEFRA Q4 release not fully mapped to trade finance commodity proxies.",
      recommendedAction: "Complete Q4 mapping workshop; signed impact memo for restated sector intensities.",
    },
    {
      key: "verification",
      label: "BRSR Core / limited assurance readiness",
      score: 58,
      status: "Weak",
      missing: "Boundary & exclusion justification missing; green deposit allocator SPO pending.",
      recommendedAction: "Close PBC list for financed emissions KPI; align NZBA progress narrative with auditor sampling plan.",
    },
  ],
  quarterlyTrend: [
    { quarter: "FY24 Q1", score: 66 },
    { quarter: "FY24 Q2", score: 68 },
    { quarter: "FY24 Q3", score: 70 },
    { quarter: "FY24 Q4", score: 73 },
  ],
  dataTraceabilityPct: 72,
  methodologyDocCompletenessPct: 82,
};

export const bankControlRegister: BankControlRegisterRow[] = [
  {
    controlId: "C-BAX-01",
    description: "Borrower climate data collection workflow (annual refresh)",
    scope3Coverage: "Cat. 15 (all asset classes)",
    linkedBorrowerIds: ["b1", "b2", "b5", "b7", "b22"],
    linkedAssetClassIds: ["bl", "pf", "sme"],
    type: "Preventive",
    frameworks: ["PCAF", "RBI Climate Risk", "BRSR Core"],
    owner: "Head — ESG Risk",
    frequency: "Annual",
    lastTested: "2025-11-18",
    status: "Partially Effective",
    evidenceLink: "/evidence/c-bax-01-borrower-questionnaire-log.xlsx",
  },
  {
    controlId: "C-BAX-02",
    description: "Independent review of PCAF attribution calculations",
    scope3Coverage: "Cat. 15",
    linkedAssetClassIds: ["bl", "eq", "pf"],
    type: "Detective",
    frameworks: ["PCAF", "NZBA"],
    owner: "Model Risk",
    frequency: "Quarterly",
    lastTested: "2025-12-02",
    status: "Effective",
    evidenceLink: "/evidence/c-bax-02-attribution-recalc-sample.pdf",
  },
  {
    controlId: "C-BAX-03",
    description: "Emission factor update & version control (ICE / DEFRA / India)",
    scope3Coverage: "Cat. 1–8 operational; Cat. 15 proxies",
    type: "Preventive",
    frameworks: ["PCAF", "BRSR"],
    owner: "Climate Analytics",
    frequency: "Quarterly",
    lastTested: "2025-10-30",
    status: "Effective",
    evidenceLink: "/evidence/c-bax-03-ef-registry-fy25.csv",
  },
  {
    controlId: "C-BAX-04",
    description: "Climate stress testing — RBI prescribed scenarios",
    scope3Coverage: "Portfolio risk (financed + collateral)",
    type: "Detective",
    frameworks: ["RBI Climate Risk", "TCFD"],
    owner: "CRO Office",
    frequency: "Annual",
    lastTested: "2025-08-20",
    status: "Partially Effective",
    evidenceLink: "/evidence/c-bax-04-stress-pack-board.pdf",
  },
  {
    controlId: "C-BAX-05",
    description: "Board ESG & climate risk oversight — minutes & actions",
    scope3Coverage: "Governance (all scopes)",
    type: "Preventive",
    frameworks: ["TCFD", "SEBI LODR"],
    owner: "Company Secretary",
    frequency: "Quarterly",
    lastTested: "2025-12-15",
    status: "Effective",
    evidenceLink: "/evidence/c-bax-05-board-minutes-extract.pdf",
  },
  {
    controlId: "C-BAX-06",
    description: "Green finance use-of-proceeds verification",
    scope3Coverage: "Green finance book; Cat. 15 mitigation narrative",
    linkedBorrowerIds: ["b14"],
    type: "Preventive",
    frameworks: ["RBI Green Deposits", "SEBI Green Bond"],
    owner: "Green Finance PMO",
    frequency: "Event-triggered",
    lastTested: "2025-09-05",
    status: "Effective",
    evidenceLink: "/evidence/c-bax-06-uop-verification.zip",
  },
  {
    controlId: "C-BAX-07",
    description: "BRSR disclosure sign-off — data owner matrix",
    scope3Coverage: "BRSR Principle 6; Cat. 15 KPI",
    type: "Preventive",
    frameworks: ["BRSR", "BRSR Core"],
    owner: "Compliance",
    frequency: "Annual",
    lastTested: "2025-11-02",
    status: "Deficient",
    evidenceLink: "/evidence/c-bax-07-brsr-signoff-matrix.xlsx",
  },
  {
    controlId: "C-BAX-08",
    description: "Third-party assurance — evidence indexing",
    scope3Coverage: "Assurance scope (Cat. 15 + selected operational)",
    type: "Detective",
    frameworks: ["BRSR Core", "PCAF"],
    owner: "Internal Audit",
    frequency: "Annual",
    lastTested: "2025-07-12",
    status: "Partially Effective",
    evidenceLink: "/evidence/c-bax-08-pbc-index.pdf",
  },
  {
    controlId: "C-BAX-09",
    description: "Transition plan review for high-intensity borrowers",
    scope3Coverage: "Cat. 15 — power, steel, cement, aviation",
    linkedBorrowerIds: ["b1", "b2", "b4", "b19"],
    type: "Corrective",
    frameworks: ["NZBA", "SBTi FI"],
    owner: "Credit Policy",
    frequency: "Monthly",
    lastTested: "2025-12-28",
    status: "Effective",
    evidenceLink: "/evidence/c-bax-09-transition-review-log.csv",
  },
  {
    controlId: "C-BAX-10",
    description: "Physical risk model validation — collateral geocoding",
    scope3Coverage: "Climate risk register; CRE & infra collateral",
    linkedBorrowerIds: ["b8", "b15"],
    type: "Detective",
    frameworks: ["RBI Climate Risk"],
    owner: "Risk Analytics",
    frequency: "Annual",
    lastTested: "2025-05-30",
    status: "Deficient",
    evidenceLink: "/evidence/c-bax-10-geocode-validation.pdf",
  },
  {
    controlId: "C-BAX-11",
    description: "Data quality score monitoring — PCAF ladder",
    scope3Coverage: "Cat. 15 — all sleeves",
    linkedAssetClassIds: ["sme", "tf", "mrt", "veh"],
    type: "Detective",
    frameworks: ["PCAF"],
    owner: "ESG Risk",
    frequency: "Monthly",
    lastTested: "2025-12-10",
    status: "Effective",
    evidenceLink: "/evidence/c-bax-11-pcaf-ladder-dashboard.png",
  },
  {
    controlId: "C-BAX-12",
    description: "Whistle-line & escalation for greenwashing allegations",
    scope3Coverage: "Green finance & disclosure",
    type: "Detective",
    frameworks: ["SEBI LODR"],
    owner: "Compliance",
    frequency: "Event-triggered",
    lastTested: "2025-03-15",
    status: "Not Assessed",
    evidenceLink: "/evidence/c-bax-12-whistle-register.pdf",
  },
  {
    controlId: "C-BAX-13",
    description: "Anomaly resolution log for financed emissions spikes",
    scope3Coverage: "Cat. 15",
    linkedBorrowerIds: ["b17", "b4"],
    type: "Corrective",
    frameworks: ["PCAF", "CDP"],
    owner: "Finance Control",
    frequency: "Quarterly",
    lastTested: "2025-11-30",
    status: "Partially Effective",
    evidenceLink: "/evidence/c-bax-13-anomaly-log.xlsx",
  },
  {
    controlId: "C-BAX-14",
    description: "Boundary & exclusions memo — annual attestation",
    scope3Coverage: "Organizational boundary; Cat. 15 exclusions",
    type: "Preventive",
    frameworks: ["BRSR Core"],
    owner: "Statutory Auditor interface",
    frequency: "Annual",
    lastTested: "2025-10-01",
    status: "Deficient",
    evidenceLink: "/evidence/c-bax-14-boundary-memo-draft.docx",
  },
];

export const bankComplianceAuditSupplement = {
  pcafCoverageLadder: [
    { band: "Score 1", pct: 8 },
    { band: "Score 2", pct: 14 },
    { band: "Score 3", pct: 28 },
    { band: "Score 4", pct: 33 },
    { band: "Score 5", pct: 17 },
  ],
  openFindings: [
    {
      id: "F-01",
      source: "Control test" as const,
      severity: "High" as const,
      title: "BRSR sign-off matrix incomplete — data owner attestations missing",
      detail: "Control C-BAX-07 failed walkthrough; 4 of 12 Principle 6 KPI owners unsigned.",
      owner: "Compliance",
      targetDate: "2026-02-15",
      status: "Open" as const,
      linkedControlId: "C-BAX-07",
    },
    {
      id: "F-02",
      source: "Control test" as const,
      severity: "High" as const,
      title: "Boundary & exclusions memo not finalized",
      detail: "Statutory auditor cannot scope assurance until BAX-BND-2025-04 is signed.",
      owner: "Statutory Auditor interface",
      targetDate: "2026-01-31",
      status: "In progress" as const,
      linkedControlId: "C-BAX-14",
    },
    {
      id: "F-03",
      source: "Regulatory" as const,
      severity: "High" as const,
      title: "RBI climate disclosure — disorderly transition NPA bridge",
      detail: "Gap flagged in regulatory tracker; CET1 narrative exists but NPA bridge unpublished.",
      owner: "CRO Office",
      targetDate: "2026-03-30",
      status: "Open" as const,
    },
    {
      id: "F-04",
      source: "Evidence" as const,
      severity: "Medium" as const,
      title: "Third-party data agreements — 2 vendors unsigned",
      detail: "PBC index shows Missing status for vendor MSAs covering emissions data feeds.",
      owner: "ESG Risk",
      targetDate: "2026-02-28",
      status: "Open" as const,
    },
    {
      id: "F-05",
      source: "Assurance" as const,
      severity: "Medium" as const,
      title: "Attribution workbook versioning — change log sparse",
      detail: "Audit trail dimension score 64%; sample of Q3 manual overrides without approver ID.",
      owner: "Finance Control",
      targetDate: "2026-02-20",
      status: "In progress" as const,
    },
    {
      id: "F-06",
      source: "Control test" as const,
      severity: "Medium" as const,
      title: "Physical risk geocoding — collateral sample exceptions",
      detail: "C-BAX-10 failed; 19% CRE renewals lack hazard-based insurance covenants in sampled accounts.",
      owner: "Risk Analytics",
      targetDate: "2026-04-15",
      status: "Open" as const,
      linkedControlId: "C-BAX-10",
    },
  ],
  auditorQueries: [
    {
      id: "AQ-01",
      subject: "PCAF Option 3 proxy — SME sleeve methodology",
      askedBy: "External assurance partner",
      assignee: "ESG Risk",
      status: "Pending evidence" as const,
      lastUpdated: "2025-12-18",
      relatedControlId: "C-BAX-11",
    },
    {
      id: "AQ-02",
      subject: "YoY financed emissions reconciliation — power sector delta",
      askedBy: "External assurance partner",
      assignee: "Climate Analytics",
      status: "Open" as const,
      lastUpdated: "2025-12-22",
      relatedControlId: "C-BAX-13",
    },
    {
      id: "AQ-03",
      subject: "Green deposit allocator second-party opinion",
      askedBy: "Internal Audit",
      assignee: "Green Finance PMO",
      status: "Answered" as const,
      lastUpdated: "2025-12-10",
      relatedControlId: "C-BAX-06",
    },
  ],
};

