import type { BankScope3MockData } from "./types";
import {
  bankAuditReadiness,
  bankComplianceAuditSupplement,
  bankControlRegister,
  bankInventoryMeta,
} from "./controls-audit-mock";
import { buildBankComplianceAuditPage } from "./compliance-audit-build";
import { carbonLensBlock } from "./carbon-lens-mock";
import { upstreamDownstreamMockData } from "./upstream-downstream-mock-data";
import { ghgTrackingMockData } from "./ghg-tracking-mock-data";
import { buildBankSubmittedDataPage, upstreamSuppliersFromMock } from "./submitted-data-mock";

/**
 * PCAF-style financed emissions & India banking compliance mock dataset (FY24–25 illustrative).
 * Single source for the Bharatiya Axis Bank Ltd dashboard prototype.
 *
 * **Cross-view consistency (read before editing):**
 * - `executive.totalFinancedEmissionsTCO2e` (417.36 Mt) = sum of `financedAssetClasses[].attributedTCO2e` = sum of `sectors[].attributedTCO2e` = GHG `sectorTracker` / `sectorDetails` totals.
 * - `company.scope3TCO2e` × `category15PctOfScope3` ≈ that financed total (97.4% illustrative).
 * - Carbon Lens **corporate loans** tiles (~198 Mt sub-total) are the **business-loan sleeve** only; Sectors / GHG show **all instruments** per sector.
 * - `executive.physicalCollateralHighHazardINRCr` = sum of `physicalDistricts[].collateralINRCr` (high-hazard band register).
 */
const _bankScope3Core = {
  company: {
    legalName: "Bharatiya Axis Bank Ltd",
    shortName: "BAXB",
    brsrTier: "BRSR Core — Top 150",
    rbiLicenseCategory: "Scheduled Commercial Bank — Private Sector",
    nzbaSignatoryDate: "2021-11-04",
    sbtiFiStatus: "Near-term FI target under validation (2026 submission)",
    loanBookINRCr: 620000,
    investmentBookINRCr: 140000,
    corporateBorrowers: 4200,
    retailLoanAccounts: 2300000,
    branches: 5800,
    foreignOffices: ["Singapore", "Dubai", "London"],
    scope1TCO2e: 182400,
    scope2TCO2e: 948000,
    scope3TCO2e: 428500000,
    category15PctOfScope3: 97.4,
    pcafCoveragePct: 58.2,
    weightedPcafScore: 3.42,
    lastInventoryClose: "2025-03-31",
  },
  executive: {
    totalFinancedEmissionsTCO2e: 417360000,
    financedYoyPct: 2.1,
    waciTCO2ePerCr: 673.2,
    waciYoyPct: -0.8,
    pcafCoveragePct: 58.2,
    coverageYoyPct: 4.6,
    weightedPcafScore: 3.42,
    pcafScoreYoyDelta: -0.11,
    climateRiskExposureINRCr: 184200,
    climateRiskYoyPct: 3.4,
    greenFinanceINRCr: 42840,
    greenFinanceYoyPct: 11.2,
    brsrReadinessPct: 73,
    brsrCoreAssuranceFlag: true,
    activeRegulatoryGaps: 4,
    nzbaGapTCO2e2030: 18600000,
    annualReductionNeededPct: 6.2,
    physicalCollateralHighHazardINRCr: 22680,
  },
  financedAssetClasses: [
    {
      id: "bl",
      name: "Business loans & unlisted equity",
      outstandingINRCr: 218400,
      attributionMethod: "PCAF Option 1 — attributed share of borrower Scope 1+2",
      attributedTCO2e: 198420000,
      pctOfScope3: 46.3,
      pcafScore: 3.1,
      coveragePct: 62,
      yoyPct: 1.8,
      riskFlag: "Sector concentration — power & steel",
    },
    {
      id: "eq",
      name: "Listed equity & bonds",
      outstandingINRCr: 140000,
      attributionMethod: "EVIC attribution — listed instruments",
      attributedTCO2e: 112600000,
      pctOfScope3: 26.3,
      pcafScore: 2.4,
      coveragePct: 71,
      yoyPct: 3.2,
      riskFlag: "Oil & gas sleeve overweight vs NZBA pathway",
    },
    {
      id: "pf",
      name: "Project finance",
      outstandingINRCr: 48600,
      attributionMethod: "Project-level economic share",
      attributedTCO2e: 54880000,
      pctOfScope3: 12.8,
      pcafScore: 3.6,
      coveragePct: 54,
      yoyPct: -1.4,
      riskFlag: "Infra & thermal exposure review",
    },
    {
      id: "mrt",
      name: "Mortgages & retail housing",
      outstandingINRCr: 128000,
      attributionMethod: "PCAF built environment — energy label proxy",
      attributedTCO2e: 12840000,
      pctOfScope3: 3.0,
      pcafScore: 4.2,
      coveragePct: 38,
      yoyPct: 4.1,
      riskFlag: "Data quality — label coverage patchy",
    },
    {
      id: "veh",
      name: "Motor vehicle loans",
      outstandingINRCr: 41200,
      attributionMethod: "Fleet proxy + vehicle class factors",
      attributedTCO2e: 9620000,
      pctOfScope3: 2.2,
      pcafScore: 4.0,
      coveragePct: 44,
      yoyPct: 6.8,
      riskFlag: "ICE share still dominant in book",
    },
    {
      id: "tf",
      name: "Trade finance",
      outstandingINRCr: 22400,
      attributionMethod: "Counterparty + commodity intensity factors",
      attributedTCO2e: 8140000,
      pctOfScope3: 1.9,
      pcafScore: 4.4,
      coveragePct: 31,
      yoyPct: 0.9,
      riskFlag: "Commodity-linked volatility",
    },
    {
      id: "sme",
      name: "SME loans",
      outstandingINRCr: 31800,
      attributionMethod: "Revenue-based physical asset proxy",
      attributedTCO2e: 11660000,
      pctOfScope3: 2.8,
      pcafScore: 4.6,
      coveragePct: 27,
      yoyPct: 2.0,
      riskFlag: "Sparse primary emissions data",
    },
    {
      id: "sov",
      name: "Sovereign bonds",
      outstandingINRCr: 19600,
      attributionMethod: "PCAF sovereign methodology — production-based",
      attributedTCO2e: 9200000,
      pctOfScope3: 2.1,
      pcafScore: 3.0,
      coveragePct: 82,
      yoyPct: -0.5,
      riskFlag: "Low — liquid hedging book",
    },
  ],
  sectors: [
    {
      sector: "Power Generation",
      exposureINRCr: 42800,
      borrowers: 186,
      waciTCO2ePerCr: 3732.9,
      attributedTCO2e: 159767821,
      pathwayStatus: "Off Track",
      physicalRisk1to10: 6,
      transitionRisk1to10: 9,
      brsrReported: true,
      transitionPlansCount: 42,
      ieaBenchmarkWaci: 890,
      sparkTrend: [168185, 159981, 155879, 159768],
    },
    {
      sector: "Steel & Metals",
      exposureINRCr: 31200,
      borrowers: 264,
      waciTCO2ePerCr: 3158.6,
      attributedTCO2e: 98548375,
      pathwayStatus: "Off Track",
      physicalRisk1to10: 5,
      transitionRisk1to10: 8,
      brsrReported: true,
      transitionPlansCount: 58,
      ieaBenchmarkWaci: 720,
      sparkTrend: [104603, 102552, 100501, 98548],
    },
    {
      sector: "Real Estate & Construction",
      exposureINRCr: 28600,
      borrowers: 512,
      waciTCO2ePerCr: 861.4,
      attributedTCO2e: 24637094,
      pathwayStatus: "No Data",
      physicalRisk1to10: 8,
      transitionRisk1to10: 5,
      brsrReported: false,
      transitionPlansCount: 28,
      ieaBenchmarkWaci: 310,
      sparkTrend: [24202, 24510, 24612, 24637],
    },
    {
      sector: "Automotive",
      exposureINRCr: 19400,
      borrowers: 178,
      waciTCO2ePerCr: 779.4,
      attributedTCO2e: 15120268,
      pathwayStatus: "On Track",
      physicalRisk1to10: 4,
      transitionRisk1to10: 6,
      brsrReported: true,
      transitionPlansCount: 44,
      ieaBenchmarkWaci: 400,
      sparkTrend: [16408, 15998, 15383, 15120],
    },
    {
      sector: "Chemicals & Petrochemicals",
      exposureINRCr: 16800,
      borrowers: 96,
      waciTCO2ePerCr: 1312.7,
      attributedTCO2e: 22052783,
      pathwayStatus: "Off Track",
      physicalRisk1to10: 7,
      transitionRisk1to10: 7,
      brsrReported: true,
      transitionPlansCount: 22,
      ieaBenchmarkWaci: 410,
      sparkTrend: [22972, 22561, 22151, 22053],
    },
    {
      sector: "Aviation",
      exposureINRCr: 8200,
      borrowers: 14,
      waciTCO2ePerCr: 4307.2,
      attributedTCO2e: 35318911,
      pathwayStatus: "Off Track",
      physicalRisk1to10: 5,
      transitionRisk1to10: 9,
      brsrReported: true,
      transitionPlansCount: 6,
      ieaBenchmarkWaci: 950,
      sparkTrend: [38970, 37329, 36098, 35319],
    },
    {
      sector: "Shipping",
      exposureINRCr: 5400,
      borrowers: 22,
      waciTCO2ePerCr: 2010,
      attributedTCO2e: 10854104,
      pathwayStatus: "No Data",
      physicalRisk1to10: 6,
      transitionRisk1to10: 7,
      brsrReported: false,
      transitionPlansCount: 5,
      ieaBenchmarkWaci: 520,
      sparkTrend: [11076, 10973, 10912, 10854],
    },
    {
      sector: "Agribusiness",
      exposureINRCr: 22400,
      borrowers: 640,
      waciTCO2ePerCr: 369.2,
      attributedTCO2e: 8269794,
      pathwayStatus: "On Track",
      physicalRisk1to10: 8,
      transitionRisk1to10: 4,
      brsrReported: true,
      transitionPlansCount: 120,
      ieaBenchmarkWaci: 200,
      sparkTrend: [8409, 8368, 8307, 8270],
    },
    {
      sector: "Cement",
      exposureINRCr: 9800,
      borrowers: 48,
      waciTCO2ePerCr: 2297.2,
      attributedTCO2e: 22512216,
      pathwayStatus: "Off Track",
      physicalRisk1to10: 6,
      transitionRisk1to10: 8,
      brsrReported: true,
      transitionPlansCount: 18,
      ieaBenchmarkWaci: 600,
      sparkTrend: [24202, 23382, 22767, 22512],
    },
    {
      sector: "IT & Data Centers",
      exposureINRCr: 12600,
      borrowers: 88,
      waciTCO2ePerCr: 533.3,
      attributedTCO2e: 6719207,
      pathwayStatus: "On Track",
      physicalRisk1to10: 3,
      transitionRisk1to10: 5,
      brsrReported: true,
      transitionPlansCount: 36,
      ieaBenchmarkWaci: 280,
      sparkTrend: [6974, 6871, 6768, 6719],
    },
    {
      sector: "MSME Diversified",
      exposureINRCr: 38200,
      borrowers: 1840,
      waciTCO2ePerCr: 194.8,
      attributedTCO2e: 7443225,
      pathwayStatus: "No Data",
      physicalRisk1to10: 5,
      transitionRisk1to10: 5,
      brsrReported: false,
      transitionPlansCount: 210,
      ieaBenchmarkWaci: 110,
      sparkTrend: [7794, 7630, 7548, 7443],
    },
    {
      sector: "Textile & Apparel",
      exposureINRCr: 14200,
      borrowers: 412,
      waciTCO2ePerCr: 430.7,
      attributedTCO2e: 6116202,
      pathwayStatus: "On Track",
      physicalRisk1to10: 7,
      transitionRisk1to10: 5,
      brsrReported: true,
      transitionPlansCount: 64,
      ieaBenchmarkWaci: 230,
      sparkTrend: [6358, 6256, 6153, 6116],
    },
  ],
  borrowers: [
    mk("b1", "IndoSteel Corp", "Steel & Metals", 4200, "BB", 18200000, 1580000, 376, 3, true, true, "Active Dialogue", "high carbon lock-in", "Term loan", "Mar-2029", 14.2, "Internal CRG", 2100000, true, "Steel & Metals"),
    mk("b2", "ReliPower Ltd", "Power Generation", 6100, "B", 24800000, 2200000, 361, 4, false, false, "First Contact", "no transition plan", "Project finance", "Sep-2031", 18.6, "Sustainalytics-equivalent", 4200000, false, "Power Generation"),
    mk("b3", "Konkan Cement Works", "Cement", 2800, "BBB", 9200000, 810000, 289, 3, true, true, "Committed to Transition Plan", "none", "TL + WC", "Jun-2028", 12.1, "MSCI-equivalent", 1800000, false, "Cement"),
    mk("b4", "SkyWings Airlines", "Aviation", 1900, "B", 11200000, 980000, 516, 4, false, true, "Active Dialogue", "stranded asset exposure", "RCF", "Dec-2027", 16.4, "Internal CRG", 3100000, false, "Aviation"),
    mk("b5", "ChemNova Petrochem", "Chemicals & Petrochemicals", 2400, "BB", 13500000, 1020000, 425, 3, false, true, "Unengaged", "litigation risk", "Term loan", "Apr-2030", 11.0, "Sustainalytics-equivalent", 1600000, false, "Chemicals & Petrochemicals"),
    mk("b6", "Eastern Grid Power", "Power Generation", 5200, "A", 19800000, 1650000, 317, 2, true, true, "Active Dialogue", "none", "Project finance", "Mar-2032", 15.2, "MSCI-equivalent", 2600000, false, "Power Generation"),
    mk("b7", "HarborLine Shipping", "Shipping", 1600, "CCC", 4800000, 410000, 256, 5, false, false, "First Contact", "no transition plan", "TL", "Aug-2026", 9.8, "Internal CRG", 900000, false, "Shipping"),
    mk("b8", "NCR Realty Developers", "Real Estate & Construction", 3600, "BBB", 6200000, 540000, 150, 4, false, true, "Active Dialogue", "none", "Construction finance", "Feb-2029", 13.5, "MSCI-equivalent", 800000, false, "Real Estate & Construction"),
    mk("b9", "Deccan Auto Components", "Automotive", 2100, "A", 5100000, 420000, 200, 2, true, true, "Committed to Transition Plan", "none", "TL", "Nov-2028", 10.4, "MSCI-equivalent", 600000, false, "Automotive"),
    mk("b10", "Krishna Agro Processing", "Agribusiness", 1800, "AA", 2800000, 210000, 117, 2, true, true, "Active Dialogue", "none", "WC + TL", "May-2027", 8.1, "Internal CRG", 400000, false, "Agribusiness"),
    mk("b11", "CloudPeak Data Parks", "IT & Data Centers", 2200, "AA", 3600000, 290000, 132, 2, true, true, "Active Dialogue", "none", "Hypothecation TL", "Jan-2030", 9.4, "MSCI-equivalent", 500000, false, "IT & Data Centers"),
    mk("b12", "Ganga Textiles Ltd", "Textile & Apparel", 1400, "BBB", 3100000, 240000, 171, 3, false, true, "First Contact", "none", "TL", "Jul-2028", 11.2, "Sustainalytics-equivalent", 450000, false, "Textile & Apparel"),
    mk("b13", "SME Packwell Cluster", "MSME Diversified", 420, "BB", 890000, 62000, 148, 4, false, false, "Unengaged", "none", "CGTMSE", "Sep-2026", 6.2, "Internal CRG", 120000, false, "MSME Diversified"),
    mk("b14", "WesternWind Renewables", "Power Generation", 3800, "AA", 1200000, 180000, 47, 1, true, true, "Committed to Transition Plan", "none", "Project finance", "Dec-2034", 22.5, "MSCI-equivalent", 200000, false, "Power Generation"),
    mk("b15", "UrbanMortgage SPV-12", "Real Estate & Construction", 900, "A", 420000, 38000, 42, 3, false, true, "Active Dialogue", "none", "Mortgage pool", "Jun-2050", 4.1, "Internal CRG", 60000, false, "Real Estate & Construction"),
    mk("b16", "FleetFirst Logistics", "Automotive", 650, "BBB", 780000, 54000, 83, 3, false, true, "First Contact", "none", "Vehicle loan book", "Mar-2028", 5.5, "Internal CRG", 90000, true, "Automotive"),
    mk("b17", "Listed OilCo Holdings", "Chemicals & Petrochemicals", 4800, "BBB", 22000000, 890000, 185, 2, true, true, "Active Dialogue", "high carbon lock-in", "Bond + equity", "Rolling", 3.2, "MSCI-equivalent", 12000000, true, "Chemicals & Petrochemicals"),
    mk("b18", "BlueHarbor Trade", "Shipping", 1100, "B", 2100000, 168000, 153, 4, false, false, "Unengaged", "none", "Trade finance", "Sep-2026", 7.4, "Internal CRG", 300000, false, "Shipping"),
    mk("b19", "Highland Cement", "Cement", 1900, "BB", 7400000, 640000, 337, 3, true, true, "Active Dialogue", "none", "TL", "Aug-2029", 12.8, "Sustainalytics-equivalent", 1100000, false, "Cement"),
    mk("b20", "MetroChem Specialties", "Chemicals & Petrochemicals", 2600, "A", 7800000, 560000, 215, 2, true, true, "Committed to Transition Plan", "none", "TL + RCF", "Oct-2030", 10.6, "MSCI-equivalent", 950000, false, "Chemicals & Petrochemicals"),
    mk("b21", "Peninsula Steel Rolling", "Steel & Metals", 980, "BBB", 4100000, 360000, 367, 3, false, true, "Active Dialogue", "none", "TL", "Feb-2028", 9.1, "Sustainalytics-equivalent", 520000, false, "Steel & Metals"),
    mk("b22", "WesternOre Pellets", "Steel & Metals", 1420, "BB", 6200000, 510000, 359, 4, false, false, "First Contact", "no transition plan", "CC + BG", "Jul-2029", 8.4, "Internal CRG", 780000, false, "Steel & Metals"),
  ],
  climateRisks: [
    cr("r1", "Physical: Acute", ["Real Estate & Construction", "Agribusiness"], 28600, "High", "Short-term <3yr", true, "Collateral revaluation & insurance uplift", true),
    cr("r2", "Physical: Chronic", ["Power Generation", "Steel & Metals"], 51200, "Medium", "Medium 3–10yr", true, "Heat stress O&M capex buffers in covenants", true),
    cr("r3", "Transition: Policy", ["Cement", "Steel & Metals"], 41000, "High", "Long-term >10yr", true, "Sector intensity caps & shadow carbon price", true),
    cr("r4", "Transition: Technology", ["Automotive", "Aviation"], 27600, "Medium", "Medium 3–10yr", true, "EV / SAF technology roadmap reviews", false),
    cr("r5", "Transition: Market", ["Shipping", "Chemicals & Petrochemicals"], 18200, "Medium", "Short-term <3yr", true, "Margin stress scenarios in RAROC", true),
    cr("r6", "Transition: Reputation", ["Power Generation"], 12800, "Low", "Short-term <3yr", false, "NZBA engagement playbook", false),
    cr("r7", "Physical: Acute", ["Shipping", "Aviation"], 14200, "High", "Short-term <3yr", true, "Cyclone & port disruption contingency", true),
    cr("r8", "Transition: Policy", ["Real Estate & Construction"], 22400, "Medium", "Long-term >10yr", true, "Building code efficiency alignment", false),
    cr("r9", "Physical: Chronic", ["IT & Data Centers"], 12600, "Low", "Medium 3–10yr", true, "Water stress & cooling redundancy KPIs", false),
    cr("r10", "Transition: Technology", ["Power Generation", "Cement"], 35600, "High", "Long-term >10yr", true, "CCUS / fuel-switch feasibility milestones", true),
  ],
  greenFinance: {
    greenLoansOutstandingINRCr: 18640,
    greenLoanAccounts: 842,
    verifiedGreenPct: 78,
    greenBondsOutstandingINRCr: 12400,
    greenDepositsINRCr: 9800,
    sllCount: 64,
    sllAvgKpiPerformancePct: 87,
    sllStepTriggersActive: 12,
    greenLoanRows: [
      gl("g1", "WesternWind Renewables", "Power Generation", "Renewable Energy", 3800, "Verified", 96, 1280000, "Dec-2034", true),
      gl("g2", "UrbanGreen Housing", "Real Estate & Construction", "Green Building", 1200, "Verified", 91, 420000, "Jun-2033", true),
      gl("g3", "EVolve Mobility Pvt Ltd", "Automotive", "EV Fleet", 860, "In review", 84, 310000, "Mar-2029", true),
      gl("g4", "AquaTreat Systems", "Chemicals & Petrochemicals", "Water Mgmt", 420, "Verified", 88, 98000, "Sep-2028", true),
      gl("g5", "BioCircle Waste", "MSME Diversified", "Waste Treatment", 310, "Self-declared", 72, 76000, "Jan-2027", false),
      gl("g6", "Western Ghats Reforest", "Agribusiness", "Biodiversity", 240, "In review", 69, 54000, "Apr-2031", true),
    ],
    bondSeries: [
      {
        isin: "IN002024Green01",
        amountINRCr: 5000,
        couponPct: 7.12,
        maturity: "2031-04-15",
        useOfProceeds: ["Solar PV", "Wind onshore", "Green transmission"],
        allocationPct: 94,
        opinionProvider: "Second Party Opinion — DNV",
        cbiCertified: true,
      },
      {
        isin: "IN002023Green02",
        amountINRCr: 3200,
        couponPct: 7.45,
        maturity: "2030-09-10",
        useOfProceeds: ["Affordable green housing", "Energy efficiency"],
        allocationPct: 91,
        opinionProvider: "SPO — Sustainalytics",
        cbiCertified: false,
      },
    ],
    rbiGreenDepositChecklist: [
      { item: "Ring-fencing of proceeds (RBI/2023-24/104)", status: "Compliant" },
      { item: "Third-party allocation confirmation", status: "In Progress" },
      { item: "Eligible green project list published", status: "Compliant" },
      { item: "Impact reporting — quarterly", status: "Compliant" },
      { item: "Board-approved green deposit policy", status: "Compliant" },
      { item: "Customer communication — plain language", status: "Gap Identified" },
    ],
    sebiGreenBondChecklist: [
      { item: "Use-of-proceeds tracking", ok: true },
      { item: "Process for project evaluation & selection", ok: true },
      { item: "Management of proceeds", ok: true },
      { item: "Reporting — allocation & impact", ok: true },
      { item: "External review / SPO", ok: true },
      { item: "Materiality & boundary", ok: true },
      { item: "Sign-off by Board ESG committee", ok: true },
      { item: "Assurance readiness for impact metrics", ok: false },
    ],
    impact: {
      mwhRenewable: 12800000,
      tco2eAvoided: 18200000,
      greenSqKm: 1.85,
    },
  },
  regulatory: [
    rc("BRSR Principal 6", "SEBI LODR — BRSR", "2026-06-30", "In Progress", 78, "Close 6 supplier-adjacent narrative gaps in financed emissions annex.", "esg_officer"),
    rc(
      "CDP Supply Chain — Cat. 1–3",
      "CDP — Supplier engagement",
      "2026-05-30",
      "In Progress",
      66,
      "Raise Tier-1 vendor climate disclosure completion above 60%; align with upstream/downstream register.",
      "procurement_gm",
    ),
    rc("BRSR Core KPI Set", "SEBI — Core assurance", "2026-05-15", "In Progress", 71, "Lock PCAF score reconciliation workbook vFY25.", "compliance_officer"),
    rc("RBI Climate Risk Disclosure", "RBI/2024-25/34 — Climate-related financial risks", "2026-07-31", "Gap Identified", 64, "Publish disorderly transition scenario NPA bridge.", "cro"),
    rc("PCAF Annual Disclosure", "PCAF Standard FI v2", "2026-09-30", "In Progress", 82, "Upload asset-class attribution sensitivity tables.", "esg_officer"),
    rc("TCFD Four Pillars", "FSB TCFD (RBI-aligned)", "2026-07-31", "In Progress", 69, "Complete metrics & targets pillar — financed emissions intensity.", "compliance_officer"),
    rc("NZBA Annual Progress", "NZBA Commitment Protocol", "2026-04-30", "Gap Identified", 58, "Sector targets vs IEA NZE — power & steel deltas.", "esg_officer"),
    rc("CDP Financial Services", "CDP FS Climate", "2026-07-26", "In Progress", 74, "C14 financed emissions module — PCAF mapping.", "esg_officer"),
    rc("SBTi FI Near-term", "SBTi Financial Institutions", "2026-12-15", "In Progress", 61, "Submit sector coverage file for validation.", "esg_officer"),
    rc("EU Taxonomy (foreign branches)", "Delegated Acts — climate", "2026-08-31", "Overdue", 44, "DNSH documentation for London wholesale book.", "compliance_officer"),
  ],
  inventoryMeta: bankInventoryMeta,
  controls: bankControlRegister,
  auditReadiness: bankAuditReadiness,
  complianceAudit: bankComplianceAuditSupplement,
  aiInsights: [
    ai("ai1", "Critical", "Financed Emissions Risk", "Power book exceeds NZBA 2030 intensity guardrail", "Power generation financed emissions total ~159.8 MtCO₂e (all instruments — same as Sectors / GHG) with sector WACI ~3,730 tCO₂e/₹cr vs IEA benchmark 890. Wholesale business-loan sleeve alone is ~49% of that sector stack; thermal-heavy names still drive the gap.", 91, "Trigger sector engagement war-room; tighten new thermal limits.", "Power Generation"),
    ai("ai2", "High", "Data Quality", "SME sleeve drives weighted PCAF score above 3.4", "~27% coverage on SME loans with 72% Score 4–5 exposures. Moving 15% of Score 5 to Score 3 improves weighted score from 3.42 to ~3.05.", 86, "Launch SME climate questionnaire + utility-linked proxies.", "MSME Diversified"),
    ai("ai3", "High", "Borrower Engagement", "Top 5 emitters — 3 remain 'Unengaged' or 'First Contact'", "ChemNova, HarborLine, SME Packwell show no transition milestones logged in FY25 H2. Combined attributed emissions ~1.49 MtCO₂e — small in Mt terms but material to PCAF score 4–5 tail (see GHG PCAF-by-sector).", 84, "Assign RM playbooks; schedule PCAF data workshops.", "ChemNova Petrochem"),
    ai("ai4", "Medium", "Green Finance Opportunity", "Green deposits runway vs peers", "₹9,800 cr mobilized vs ₹14,200 cr addressable retail base in ESG cohorts — 11% uplift potential with certified project pipeline.", 72, "Bundle rooftop solar + green deposit campaigns in Tier-2 branches.", "Green Deposits"),
    ai("ai5", "Medium", "Regulatory Gap", "RBI climate scenario — disorderly transition NPA bridge missing", "Stress pack shows CET1 impact -38 bps under orderly but disorderly bridge to NPA ratio not published — flagged in mock gap tracker.", 88, "Complete disorderly narrative + board risk appetite linkage.", "RBI Climate Risk Disclosure"),
    ai("ai6", "Medium", "Climate Physical Risk", "Mumbai + Kochi collateral heat map — high flood overlap", "₹7,300 cr CRE collateral in combined high flood / cyclone bands (subset of ₹22,680 cr high-hazard district register — Climate view); insurance covenants absent on 19% of accounts.", 79, "Insert hazard-based insurance covenants for renewals.", "Real Estate & Construction"),
    ai("ai7", "Low", "Portfolio Decarbonization", "Renewables sleeve outperforming pathway", "WesternWind Renewables shows 47 tCO₂e/₹cr vs sector average; consider upsize under green TL framework.", 68, "Template SLL structure for grid-scale hybrids.", "WesternWind Renewables"),
    ai("ai8", "High", "Financed Emissions Risk", "Listed oil & gas overweight vs NZBA sector benchmark", "Listed OilCo Holdings shows ~0.89 MtCO₂e direct attributed emissions on file, but EVIC-linked oil & gas sleeve sensitivity: +10% EVIC shock moves **portfolio** financed total by ~+4.2% in stress workbook (see Financed — listed equity row).", 83, "Run divestment / hedging strategy paper for ALCO.", "Listed OilCo Holdings"),
    ai("ai9", "Medium", "Data Quality", "Trade finance emissions rely on commodity proxies", "31% data coverage with PCAF score 4.4; consider bank-wide LC counterparty emission survey.", 74, "Pilot blockchain-backed shipment EF attachments.", "Trade finance"),
    ai("ai10", "Low", "Regulatory Gap", "EU Taxonomy DNSH documentation overdue", "London branch wholesale exposures — DNSH pack incomplete since FY24 Q4; status Overdue in compliance tracker.", 80, "Engage external counsel; assign compliance_owner workstream.", "EU Taxonomy"),
    ai(
      "ai11",
      "High",
      "Borrower Engagement",
      "IndoSteel Corp — BF-BOF asset lock-in vs NZBA steel pathway",
      "₹4,200 cr exposure with high carbon lock-in flag; no SBTi commitment logged. Attributed emissions ~1.58 MtCO₂e FY25 — RM engagement paused 120+ days.",
      85,
      "Schedule transition plan workshop; escalate to credit policy for covenant KPIs.",
      "IndoSteel Corp",
    ),
  ],
  nzbaTrend: [
    { fyLabel: "FY22–23", actualTCO2e: 398000000, nzbaTargetTCO2e: 402000000, ieaNetZeroTCO2e: 390000000 },
    { fyLabel: "FY23–24", actualTCO2e: 408800000, nzbaTargetTCO2e: 395000000, ieaNetZeroTCO2e: 382000000 },
    { fyLabel: "FY24–25", actualTCO2e: 417360000, nzbaTargetTCO2e: 388000000, ieaNetZeroTCO2e: 374000000, isCurrent: true },
    { fyLabel: "FY25–26", actualTCO2e: 424000000, nzbaTargetTCO2e: 381000000, ieaNetZeroTCO2e: 366000000 },
    { fyLabel: "FY26–27", actualTCO2e: 430500000, nzbaTargetTCO2e: 372000000, ieaNetZeroTCO2e: 356000000 },
    { fyLabel: "FY27–28", actualTCO2e: 435000000, nzbaTargetTCO2e: 362000000, ieaNetZeroTCO2e: 345000000 },
    { fyLabel: "FY28–29", actualTCO2e: 438000000, nzbaTargetTCO2e: 350000000, ieaNetZeroTCO2e: 332000000 },
    { fyLabel: "FY29–30", actualTCO2e: 440500000, nzbaTargetTCO2e: 338000000, ieaNetZeroTCO2e: 318000000 },
    { fyLabel: "FY30–31", actualTCO2e: 441800000, nzbaTargetTCO2e: 325000000, ieaNetZeroTCO2e: 305000000 },
  ],
  tcfdPillars: [
    { pillar: "Governance", completenessPct: 82 },
    { pillar: "Strategy", completenessPct: 74 },
    { pillar: "Risk Management", completenessPct: 69 },
    { pillar: "Metrics & Targets", completenessPct: 61 },
  ],
  scenarioRows: [
    {
      scenario: "IEA Net Zero 2050",
      loanAtRiskINRCr: 42800,
      npaDeltaPct: 0.85,
      cet1ImpactBps: -38,
      horizon: "2030",
    },
    {
      scenario: "IEA Announced Pledges (STEPS)",
      loanAtRiskINRCr: 31200,
      npaDeltaPct: 0.52,
      cet1ImpactBps: -22,
      horizon: "2030",
    },
    {
      scenario: "RBI Adverse Climate Stress",
      loanAtRiskINRCr: 51800,
      npaDeltaPct: 1.24,
      cet1ImpactBps: -56,
      horizon: "2032",
    },
  ],
  sectorScenarioMatrix: [
    { sector: "Power Generation", netZero: 9, steps: 6, rbiAdverse: 10 },
    { sector: "Steel & Metals", netZero: 8, steps: 7, rbiAdverse: 9 },
    { sector: "Cement", netZero: 7, steps: 6, rbiAdverse: 8 },
    { sector: "Real Estate & Construction", netZero: 5, steps: 5, rbiAdverse: 7 },
    { sector: "Aviation", netZero: 8, steps: 8, rbiAdverse: 9 },
    { sector: "Automotive", netZero: 4, steps: 5, rbiAdverse: 6 },
  ],
  physicalDistricts: [
    { district: "Mumbai Suburban", state: "Maharashtra", hazard: "Flood + pluvial", collateralINRCr: 4200 },
    { district: "Ernakulam", state: "Kerala", hazard: "Cyclone + flood", collateralINRCr: 3100 },
    { district: "Ahmedabad", state: "Gujarat", hazard: "Heat stress", collateralINRCr: 2800 },
    { district: "Chennai", state: "Tamil Nadu", hazard: "Cyclone", collateralINRCr: 2650 },
    { district: "Gautam Buddha Nagar", state: "Uttar Pradesh", hazard: "Heat + water stress", collateralINRCr: 2400 },
    { district: "Khorda", state: "Odisha", hazard: "Cyclone", collateralINRCr: 2100 },
    { district: "Surat", state: "Gujarat", hazard: "Flood", collateralINRCr: 1980 },
    { district: "Hyderabad", state: "Telangana", hazard: "Heat stress", collateralINRCr: 1850 },
    { district: "Kamrup Metropolitan", state: "Assam", hazard: "Flood", collateralINRCr: 1620 },
    { district: "North Goa", state: "Goa", hazard: "Coastal inundation", collateralINRCr: 980 },
  ],
  stressTest: {
    scenarios: ["Orderly Transition", "Disorderly Transition", "Hothouse World"],
    npaRatioChangePct: 0.62,
    capitalAdequacyBps: "-42 bps CET1 (illustrative)",
    boardSignOff: "Board Risk Committee — approved with conditions",
    signOffDate: "2025-09-12",
  },
  auditDocuments: [
    { docType: "PCAF Methodology Statement", status: "Available" },
    { docType: "Emission Factor Version Log", status: "Available" },
    { docType: "Data Source Register", status: "In Preparation" },
    { docType: "Attribution Calculation Workbook", status: "Available" },
    { docType: "Boundary & Exclusion Justification", status: "Missing" },
    { docType: "Data Collection Procedure", status: "Available" },
    { docType: "Quality Review Sign-off", status: "In Preparation" },
    { docType: "YoY Reconciliation Memo", status: "Available" },
    { docType: "Anomaly Resolution Log", status: "Available" },
    { docType: "Third-Party Data Agreements", status: "Missing" },
    { docType: "Board Approval Record", status: "Available" },
    { docType: "Prior Year Comparative", status: "Available" },
  ],
  brsrReadinessDimensions: [
    { name: "Data Completeness", scorePct: 76, status: "Adequate", gap: "SME & trade finance coverage", action: "Expand borrower survey + LC attachments" },
    { name: "Methodology Documentation", scorePct: 82, status: "Strong", gap: "Minor version cross-links", action: "Link EF registry tags to PCAF options" },
    { name: "Emission Factor Currency", scorePct: 71, status: "Adequate", gap: "DEFRA release not fully mapped", action: "Complete Q4 mapping workshop" },
    { name: "Audit Trail Quality", scorePct: 64, status: "Gap", gap: "Attribution workbook change log sparse", action: "Enable controlled versioning in GRC tool" },
    { name: "Third-Party Verification", scorePct: 58, status: "Gap", gap: "Green deposit allocator letter pending", action: "Close allocator SPO by Feb 2026" },
    { name: "Boundary Documentation", scorePct: 79, status: "Adequate", gap: "Foreign branch carve-out narrative", action: "Publish London branch boundary memo" },
  ],
  brsrReadinessTrend: [
    { quarter: "FY24 Q1", score: 66 },
    { quarter: "FY24 Q2", score: 68 },
    { quarter: "FY24 Q3", score: 70 },
    { quarter: "FY24 Q4", score: 73 },
  ],
  reports: [
    rp("rep1", "BRSR Section A — Environmental (Principle 6)", "SEBI BRSR", "2026-06-30", "Incomplete", 78, ["Waste intensity — branch network", "Water — foreign offices"], "2025-12-01"),
    rp("rep2", "BRSR Core KPI Assurance Pack", "SEBI Core", "2026-05-15", "Incomplete", 71, ["Financed emissions intensity KPI — auditor tie-out"], null),
    rp("rep3", "RBI Climate Risk Disclosure Report", "RBI/2024-25/34", "2026-07-31", "Incomplete", 64, ["Disorderly transition NPA bridge"], "2025-08-30"),
    rp("rep4", "PCAF Annual Disclosure", "PCAF FI Standard v2", "2026-09-30", "Ready", 92, [], "2025-11-18"),
    rp("rep5", "NZBA Annual Progress Report", "NZBA Protocol", "2026-04-30", "Incomplete", 58, ["Steel sector engagement evidence"], null),
    rp("rep6", "CDP Financial Services — Climate", "CDP FS", "2026-07-26", "Incomplete", 74, ["C14.6 asset class splits"], "2025-10-05"),
    rp("rep7", "Board Risk Committee Climate Report", "Internal — quarterly", "2026-01-15", "Ready", 88, [], "2025-10-12"),
    rp("rep8", "EU Taxonomy Alignment — Foreign Branches", "EU Taxonomy", "2026-08-31", "Not Started", 44, ["DNSH documentation", "Eligible activity mapping"], null),
  ],
  carbonLens: carbonLensBlock,
  upstreamDownstream: upstreamDownstreamMockData,
  ghgTracking: ghgTrackingMockData,
} satisfies Omit<BankScope3MockData, "complianceAuditPage" | "submittedData">;

export const bankScope3MockData: BankScope3MockData = {
  ..._bankScope3Core,
  complianceAuditPage: buildBankComplianceAuditPage(
    _bankScope3Core.borrowers,
    _bankScope3Core.executive,
    bankComplianceAuditSupplement,
    bankControlRegister,
  ),
  submittedData: buildBankSubmittedDataPage(
    _bankScope3Core.borrowers,
    upstreamSuppliersFromMock(upstreamDownstreamMockData.upstream.suppliers),
    bankControlRegister,
  ),
};

function mk(
  id: string,
  name: string,
  sector: string,
  loanOutstandingINRCr: number,
  esgRating: import("./types").EsgRatingBand,
  scope12TCO2e: number,
  attributedTCO2e: number,
  emissionIntensity: number,
  pcafScore: number,
  sbtiCommitted: boolean,
  brsrDisclosed: boolean,
  engagement: import("./types").BorrowerRow["engagement"],
  redFlags: import("./types").BorrowerRow["redFlags"],
  facilityType: string,
  maturity: string,
  attributionFactorPct: number,
  ratingAgency: string,
  scope3TCO2e: number | undefined,
  treasuryRelevant: boolean,
  rmFocusSector: string,
): import("./types").BorrowerRow {
  return {
    id,
    name,
    sector,
    loanOutstandingINRCr,
    esgRating,
    scope12TCO2e,
    attributedTCO2e,
    emissionIntensity,
    pcafScore,
    sbtiCommitted,
    brsrDisclosed,
    engagement,
    redFlags,
    facilityType,
    maturity,
    attributionFactorPct,
    ratingAgency,
    scope3TCO2e,
    treasuryRelevant,
    rmFocusSector,
  };
}

function cr(
  id: string,
  riskType: string,
  sectors: string[],
  exposureINRCr: number,
  magnitude: import("./types").ClimateRiskRegisterRow["magnitude"],
  horizon: import("./types").ClimateRiskRegisterRow["horizon"],
  rbiTcfdDisclosure: boolean,
  mitigation: string,
  disclosedInAnnualReport: boolean,
): import("./types").ClimateRiskRegisterRow {
  return { id, riskType, sectors, exposureINRCr, magnitude, horizon, rbiTcfdDisclosure, mitigation, disclosedInAnnualReport };
}

function gl(
  id: string,
  borrower: string,
  sector: string,
  greenType: string,
  amountINRCr: number,
  verification: import("./types").GreenLoanRow["verification"],
  uopAlignmentPct: number,
  co2eAvoidedPerYr: number,
  maturity: string,
  brsrReportable: boolean,
): import("./types").GreenLoanRow {
  return { id, borrower, sector, greenType, amountINRCr, verification, uopAlignmentPct, co2eAvoidedPerYr, maturity, brsrReportable };
}

function rc(
  framework: string,
  section: string,
  deadline: string,
  status: import("./types").ComplianceStatus,
  completenessPct: number,
  nextAction: string,
  ownerPersona: import("./types").BankPersonaId,
): import("./types").RegulatoryComplianceRow {
  return { framework, section, deadline, status, completenessPct, nextAction, ownerPersona };
}

function ai(
  id: string,
  severity: import("./types").InsightSeverity,
  category: import("./types").BankInsightCategory,
  title: string,
  detail: string,
  confidencePct: number,
  recommendedAction: string,
  linkedEntity: string,
): import("./types").AiInsight {
  return { id, severity, category, title, detail, confidencePct, recommendedAction, linkedEntity, workflow: "Open" };
}

function rp(
  id: string,
  name: string,
  regulatoryBasis: string,
  deadline: string,
  status: import("./types").ReportPackStatus,
  completenessPct: number,
  missingFields: string[],
  lastGenerated: string | null,
): import("./types").ReportDefinition {
  return { id, name, regulatoryBasis, deadline, status, completenessPct, missingFields, lastGenerated };
}
