import type { UpstreamDownstreamMockData } from "./types";
import { attachUpstreamDownstreamDrills } from "./upstream-downstream-drills";

/** Illustrative FY24–25 dataset for UpstreamDownstreamView — values referenced from bank inventory narrative. */
const upstreamDownstreamMockDataBase: UpstreamDownstreamMockData = {
  hero: {
    bankTicker: "BABL",
    upstreamSuppliers: [
      { name: "Tata Power / Adani", note: "Branch electricity — 1,180 branches on blended grid; PPA-backed RE 18% of kWh (FY25)." },
      { name: "TCS / Infosys", note: "Core banking + DC hosting; DLP, fraud analytics, and API gateway managed services." },
      { name: "Air India + IndiGo", note: "Domestic + short-haul international; class-of-service uplift per travel policy v2025.03." },
      { name: "DLF / Embassy REIT", note: "Leased floor area ~2.4M sq ft; landlord disclosure gap filled via CAM invoices." },
      { name: "HP India / Dell", note: "End-user compute refresh cycle; embodied carbon from OEM PCFs where available." },
    ],
    downstreamBorrowers: [
      { name: "ReliPower Ltd", note: "Coal generation — large rotating exposure; PCAF Option 2 with audited S1+2." },
      { name: "IndoSteel Corp", note: "BF-BOF steel; SBTi committed; intensity improving 12% YoY on sample lines." },
      { name: "AviCo Airways", note: "Jet kerosene dominated; EU ETS linkage on international legs (modelled)." },
      { name: "Home Loan customers", note: "Retail mortgage pool — proxy intensity from floor-area + climate zone map." },
      { name: "MSME borrowers", note: "Distributed tail — EEIO + bureau cash-flow overlays; higher PCAF uncertainty." },
    ],
    upstreamPctScope3: 2.7,
    downstreamPctScope3: 97.3,
    insideTCO2e: 13100,
    outsideTCO2e: 482600,
    tagline:
      "The bank's product is money. What borrowers DO with that money is where 97% of emissions come from.",
    rupeeFlowLeftLabel: "₹ flows LEFT (bank pays suppliers)",
    rupeeFlowRightLabel: "₹ flows RIGHT (bank lends to borrowers)",
  },
  upstream: {
    headerTitle: "Upstream — What BABL Buys to Run Itself",
    sublabel: "Bank as BUYER | Scope 3 Categories 1–8",
    pctScope3: 2.7,
    totalTCO2e: 13100,
    categories: [
      { id: "c1", label: "Cat 1: Purchased Services (IT, catering)", tco2e: 3200 },
      { id: "c2", label: "Cat 2: Capital Goods (laptops, ATMs)", tco2e: 820 },
      { id: "c3", label: "Cat 3: Fuel & Energy Related", tco2e: 480 },
      { id: "c5", label: "Cat 5: Waste", tco2e: 140 },
      { id: "c6", label: "Cat 6: Business Travel", tco2e: 1800, flagYoyPct: 22, flagLabel: "Up 22% YoY" },
      { id: "c7", label: "Cat 7: Employee Commuting", tco2e: 960 },
      { id: "c8", label: "Cat 8: Leased Office Space", tco2e: 1000 },
    ],
    suppliers: [
      { supplier: "Tata Power / Adani", supply: "Branch electricity", spendCr: 840, tco2e: 7200, category: "Scope 2" },
      { supplier: "TCS", supply: "Core banking software", spendCr: 1200, tco2e: 980, category: "Cat 1" },
      { supplier: "Air India + IndiGo", supply: "Business travel", spendCr: 320, tco2e: 1800, category: "Cat 6" },
      { supplier: "Infosys BPM", supply: "Back-office ops", spendCr: 680, tco2e: 540, category: "Cat 1" },
      { supplier: "DLF / Embassy REIT", supply: "Office leases", spendCr: 920, tco2e: 1000, category: "Cat 8" },
      { supplier: "HP India / Dell", supply: "Laptops & hardware", spendCr: 280, tco2e: 820, category: "Cat 2" },
      { supplier: "BPCL / IOCL", supply: "Diesel for generators", spendCr: 180, tco2e: 480, category: "Cat 3" },
    ],
    supplierHoverSuffix:
      "Their manufacturing/delivery emissions are BABL's upstream Scope 3 when BABL pays them for this supply.",
    greenProcurement: [
      { label: "% of IT contracts with suppliers who have SBTi targets", value: "42%" },
      { label: "% of electricity from renewable sources", value: "28%" },
      { label: "Travel policy carbon budget per employee", value: "₹ 18,000/yr" },
    ],
    upstreamNetZero: { label: "Upstream Net Zero Target 2035", pctAchieved: 31 },
  },
  downstream: {
    headerTitle: "Downstream — Who BABL Lends Money To",
    sublabel: "Bank as CAPITAL SUPPLIER | Category 15 — Financed Emissions",
    pctScope3: 97.3,
    totalTCO2e: 482600,
    moneyFlowSegments: [
      { id: "bl", label: "Business Loans", exposureCr: 420000, tco2e: 348400, pctBook: 72.2, pcafScore: 3.1 },
      { id: "eq", label: "Listed Equity & Bonds", exposureCr: 82000, tco2e: 57400, pctBook: 11.9, pcafScore: 2.4 },
      { id: "pf", label: "Project Finance", exposureCr: 48000, tco2e: 38200, pctBook: 7.9, pcafScore: 3.6 },
      { id: "hl", label: "Home Loans", exposureCr: 180000, tco2e: 18200, pctBook: 3.8, pcafScore: 4.2 },
      { id: "vl", label: "Vehicle Loans", exposureCr: 68000, tco2e: 9800, pctBook: 2.0, pcafScore: 4.0 },
      { id: "tf", label: "Trade Finance", exposureCr: 42000, tco2e: 6800, pctBook: 1.4, pcafScore: 4.4 },
      { id: "uw", label: "Underwriting", exposureCr: 28000, tco2e: 3200, pctBook: 0.7, pcafScore: 3.8 },
    ],
    scatterPoints: [
      { sector: "Power", exposureCr: 42800, intensityPerCr: 892, borrowers: 86, quadrant: "TR", fill: "#ef4444" },
      { sector: "Steel", exposureCr: 31200, intensityPerCr: 1040, borrowers: 64, quadrant: "TR", fill: "#ef4444" },
      { sector: "Aviation", exposureCr: 18400, intensityPerCr: 720, borrowers: 22, quadrant: "TR", fill: "#f97316" },
      { sector: "Cement", exposureCr: 14200, intensityPerCr: 610, borrowers: 38, quadrant: "TL", fill: "#f97316" },
      { sector: "Shipping", exposureCr: 9800, intensityPerCr: 540, borrowers: 19, quadrant: "TL", fill: "#f97316" },
      { sector: "Chemicals", exposureCr: 22600, intensityPerCr: 380, borrowers: 112, quadrant: "BL", fill: "#f97316" },
      { sector: "Auto", exposureCr: 41200, intensityPerCr: 234, borrowers: 840, quadrant: "BL", fill: "#fbbf24" },
      { sector: "MSME", exposureCr: 31800, intensityPerCr: 372, borrowers: 12400, quadrant: "BL", fill: "#fbbf24" },
      { sector: "Agri", exposureCr: 88400, intensityPerCr: 86, borrowers: 420000, quadrant: "BR", fill: "#22c55e" },
      { sector: "IT", exposureCr: 24600, intensityPerCr: 42, borrowers: 620, quadrant: "BR", fill: "#22c55e" },
      { sector: "Textile", exposureCr: 19200, intensityPerCr: 118, borrowers: 410, quadrant: "BR", fill: "#22c55e" },
      { sector: "Real Estate", exposureCr: 128000, intensityPerCr: 100, borrowers: 2100000, quadrant: "BR", fill: "#22c55e" },
    ],
    quadrantLabels: [
      { key: "TR", title: "HIGH MONEY + HIGH CARBON", subtitle: "Priority engagement" },
      { key: "TL", title: "LOW MONEY + HIGH CARBON", subtitle: "Exit strategy" },
      { key: "BR", title: "HIGH MONEY + LOW CARBON", subtitle: "Grow this" },
      { key: "BL", title: "LOW MONEY + LOW CARBON", subtitle: "Monitor" },
    ],
    pcafBoxTitle: "How We Calculate Our Share of a Borrower's Emissions",
    pcafFormulaIntro: "Select a borrower to see the live attribution walk-through used in PCAF disclosure and BRSR Section A.",
    pcafBorrowers: [
      {
        id: "b1",
        name: "ReliPower Ltd",
        borrowerScope12TCO2e: 8200000,
        loanOutstandingCr: 8200,
        totalDebtPlusMarketCapCr: 82000,
        attributionPct: 10,
        attributedTCO2e: 820000,
        pcafScore: 2,
        pcafLabel: "Audited Annual Report",
      },
      {
        id: "b2",
        name: "IndoSteel Corp",
        borrowerScope12TCO2e: 4200000,
        loanOutstandingCr: 6400,
        totalDebtPlusMarketCapCr: 51200,
        attributionPct: 12.5,
        attributedTCO2e: 525000,
        pcafScore: 2,
        pcafLabel: "Audited + CDP",
      },
      {
        id: "b3",
        name: "AviCo Airways",
        borrowerScope12TCO2e: 1800000,
        loanOutstandingCr: 3100,
        totalDebtPlusMarketCapCr: 62000,
        attributionPct: 5,
        attributedTCO2e: 90000,
        pcafScore: 3,
        pcafLabel: "Estimated — sector factors",
      },
      {
        id: "b4",
        name: "MetalFab Steelworks",
        borrowerScope12TCO2e: 980000,
        loanOutstandingCr: 2200,
        totalDebtPlusMarketCapCr: 44000,
        attributionPct: 5,
        attributedTCO2e: 49000,
        pcafScore: 2,
        pcafLabel: "SBTi + audited",
      },
      {
        id: "b5",
        name: "Coastal Cement Ltd",
        borrowerScope12TCO2e: 2100000,
        loanOutstandingCr: 4100,
        totalDebtPlusMarketCapCr: 41000,
        attributionPct: 10,
        attributedTCO2e: 210000,
        pcafScore: 3,
        pcafLabel: "Annual report",
      },
      {
        id: "b6",
        name: "GreenGrid Renewables",
        borrowerScope12TCO2e: 120000,
        loanOutstandingCr: 4800,
        totalDebtPlusMarketCapCr: 24000,
        attributionPct: 20,
        attributedTCO2e: 24000,
        pcafScore: 1,
        pcafLabel: "Project-level MRV",
      },
      {
        id: "b7",
        name: "UrbanHome Finance SPV",
        borrowerScope12TCO2e: 42000,
        loanOutstandingCr: 1800,
        totalDebtPlusMarketCapCr: 9000,
        attributionPct: 20,
        attributedTCO2e: 8400,
        pcafScore: 4,
        pcafLabel: "Proxy — energy label",
      },
      {
        id: "b8",
        name: "Southern Agri Procure",
        borrowerScope12TCO2e: 88000,
        loanOutstandingCr: 920,
        totalDebtPlusMarketCapCr: 18400,
        attributionPct: 5,
        attributedTCO2e: 4400,
        pcafScore: 4,
        pcafLabel: "Spend-based proxy",
      },
      {
        id: "b9",
        name: "TechServe IT Ltd",
        borrowerScope12TCO2e: 18000,
        loanOutstandingCr: 640,
        totalDebtPlusMarketCapCr: 12800,
        attributionPct: 5,
        attributedTCO2e: 900,
        pcafScore: 3,
        pcafLabel: "Revenue proxy",
      },
      {
        id: "b10",
        name: "Harbour Shipping Co",
        borrowerScope12TCO2e: 640000,
        loanOutstandingCr: 1800,
        totalDebtPlusMarketCapCr: 36000,
        attributionPct: 5,
        attributedTCO2e: 32000,
        pcafScore: 4,
        pcafLabel: "AIS + bunker factors",
      },
      {
        id: "b11",
        name: "NorthChem Industries",
        borrowerScope12TCO2e: 740000,
        loanOutstandingCr: 2600,
        totalDebtPlusMarketCapCr: 52000,
        attributionPct: 5,
        attributedTCO2e: 37000,
        pcafScore: 3,
        pcafLabel: "Hybrid model",
      },
      {
        id: "b12",
        name: "Metro Retail Chain",
        borrowerScope12TCO2e: 210000,
        loanOutstandingCr: 1400,
        totalDebtPlusMarketCapCr: 28000,
        attributionPct: 5,
        attributedTCO2e: 10500,
        pcafScore: 4,
        pcafLabel: "Floor area proxy",
      },
      {
        id: "b13",
        name: "Precision Auto Tier-1",
        borrowerScope12TCO2e: 92000,
        loanOutstandingCr: 880,
        totalDebtPlusMarketCapCr: 17600,
        attributionPct: 5,
        attributedTCO2e: 4600,
        pcafScore: 4,
        pcafLabel: "Production proxy",
      },
      {
        id: "b14",
        name: "WeaveWell Textiles",
        borrowerScope12TCO2e: 124000,
        loanOutstandingCr: 720,
        totalDebtPlusMarketCapCr: 14400,
        attributionPct: 5,
        attributedTCO2e: 6200,
        pcafScore: 4,
        pcafLabel: "Energy spend proxy",
      },
      {
        id: "b15",
        name: "SME Cluster Agra",
        borrowerScope12TCO2e: 48000,
        loanOutstandingCr: 180,
        totalDebtPlusMarketCapCr: 3600,
        attributionPct: 5,
        attributedTCO2e: 2400,
        pcafScore: 5,
        pcafLabel: "Sparse primary data",
      },
      {
        id: "b16",
        name: "LogiTrade Finance Counterparty",
        borrowerScope12TCO2e: 220000,
        loanOutstandingCr: 420,
        totalDebtPlusMarketCapCr: 8400,
        attributionPct: 5,
        attributedTCO2e: 11000,
        pcafScore: 4,
        pcafLabel: "Commodity-linked",
      },
      {
        id: "b17",
        name: "InfraRoad Build Pvt",
        borrowerScope12TCO2e: 310000,
        loanOutstandingCr: 2900,
        totalDebtPlusMarketCapCr: 29000,
        attributionPct: 10,
        attributedTCO2e: 31000,
        pcafScore: 3,
        pcafLabel: "Project reports",
      },
      {
        id: "b18",
        name: "EV Mobility Fleet Co",
        borrowerScope12TCO2e: 42000,
        loanOutstandingCr: 1100,
        totalDebtPlusMarketCapCr: 11000,
        attributionPct: 10,
        attributedTCO2e: 4200,
        pcafScore: 2,
        pcafLabel: "Fleet telematics",
      },
      {
        id: "b19",
        name: "CityGas Distribution",
        borrowerScope12TCO2e: 180000,
        loanOutstandingCr: 1600,
        totalDebtPlusMarketCapCr: 32000,
        attributionPct: 5,
        attributedTCO2e: 9000,
        pcafScore: 3,
        pcafLabel: "Regulatory returns",
      },
      {
        id: "b20",
        name: "Offshore Wind SPV-7",
        borrowerScope12TCO2e: 8000,
        loanOutstandingCr: 6200,
        totalDebtPlusMarketCapCr: 31000,
        attributionPct: 20,
        attributedTCO2e: 1600,
        pcafScore: 1,
        pcafLabel: "IEA-aligned MRV",
      },
    ],
    greenMoney: {
      title: "GREEN MONEY",
      exposureCr: 74400,
      pctBook: 12,
      narrative: ["Renewable energy", "EV loans", "Green buildings"],
      tco2eLabel: "Avoided",
      tco2e: 72400,
      targetLabel: "Target: 25% by 2027",
      statusLabel: "Status: Behind",
      statusTone: "amber",
    },
    brownMoney: {
      title: "BROWN MONEY",
      exposureCr: 248000,
      pctBook: 40,
      narrative: ["Coal, Steel", "Cement, Aviation", "Petrochemicals, Shipping"],
      tco2eLabel: "Causes",
      tco2e: 386400,
      targetLabel: "Target: 30% by 2027",
      statusLabel: "Status: Too high",
      statusTone: "red",
    },
    neutralMoney: {
      title: "NEUTRAL MONEY",
      exposureCr: 297600,
      pctBook: 48,
      narrative: ["Real Estate,", "MSME, Retail,", "Agri, IT"],
      tco2eLabel: "Mixed",
      tco2e: 96200,
      targetLabel: "Neutral",
      statusLabel: "Status: OK",
      statusTone: "green",
    },
    netPositionLine:
      "NET POSITION: BABL causes 4,10,200 tCO₂e more than it avoids. NZBA requires this gap to close 28% by 2030.",
  },
  engagement: {
    funnelTitle: "The Borrower Engagement Pipeline",
    stages: [
      { id: "s1", title: "Identified & Prioritized", subtitle: "Screening queue", count: 200, pctOfPrior: 100 },
      { id: "s2", title: "Contacted", subtitle: "Email / meet", count: 164, pctOfPrior: 82 },
      { id: "s3", title: "Questionnaire Sent", subtitle: "Data request", count: 128, pctOfPrior: 64 },
      { id: "s4", title: "Data Received & Verified", subtitle: "QA pass", count: 89, pctOfPrior: 45 },
      { id: "s5", title: "Transition Plan Agreed", subtitle: "Milestone map", count: 42, pctOfPrior: 21 },
      { id: "s6", title: "SBTi Committed", subtitle: "Targets set", count: 18, pctOfPrior: 9 },
      { id: "s7", title: "Annual Progress Reported", subtitle: "Assurance", count: 11, pctOfPrior: 6 },
    ],
    insightLineA: "Moving all Stage 3→4 borrowers improves PCAF avg score from 3.8 → 2.9",
    insightLineB: "42 borrowers with transition plans cover 68% of total attributed emissions",
    ringLabel: "Top 50 emitters in active engagement",
    ringCurrent: 34,
    ringTotal: 50,
    rmSectorBanner: "Corporate RM view — engagement pipeline filtered to Steel & Metals borrowers (illustrative).",
  },
  trend: {
    points: [
      { fy: "FY22-23", outsideActual: 422000, outsideTarget: 410000, insideActual: 15200, insideTarget: 14000 },
      { fy: "FY23-24", outsideActual: 448000, outsideTarget: 398000, insideActual: 14400, insideTarget: 11200 },
      { fy: "FY24-25", outsideActual: 462000, outsideTarget: 382000, insideActual: 13800, insideTarget: 8200 },
      { fy: "FY25-26", outsideActual: 482600, outsideTarget: 365000, insideActual: 13100, insideTarget: 6200 },
      { fy: "FY26-27", outsideActual: 482600, outsideTarget: 352000, insideActual: 13100, insideTarget: 4800 },
      { fy: "FY27-28", outsideActual: 482600, outsideTarget: 347232, insideActual: 13100, insideTarget: 3200 },
      { fy: "FY28-29", outsideActual: 482600, outsideTarget: 347232, insideActual: 13100, insideTarget: 1800 },
      { fy: "FY29-30", outsideActual: 482600, outsideTarget: 347232, insideActual: 13100, insideTarget: 900 },
      { fy: "FY30-31", outsideActual: 482600, outsideTarget: 347232, insideActual: 13100, insideTarget: 0 },
    ],
    annotations: [
      { fy: "FY24-25", text: "FY24: New coal sector loans added ₹18,000 Cr", tone: "up" },
      { fy: "FY24-25", text: "FY24: Steel borrower MetalFab improved intensity 12%", tone: "down" },
    ],
    gapLabel: "NZBA GAP — tCO₂e to close by 2030",
    gapTCO2e: 135368,
    footerLines: [
      "Inside emissions are declining — on track for 2035 net zero.",
      "Outside emissions are growing — 28% reduction needed by 2030.",
      "The battle is downstream. The solution is who we lend to.",
    ],
  },
};

export const upstreamDownstreamMockData: UpstreamDownstreamMockData = attachUpstreamDownstreamDrills(upstreamDownstreamMockDataBase);
