-- ============================================================
-- SOC 2 — Seed evidence_sufficiency_matrix.
-- sufficiency_criteria and evaluation_criteria stored as JSONB:
--   sufficiency_criteria: { "summary": "...", "must_show": ["...", ...] }
--   evaluation_criteria:  { "reviewer_checks": ["...", ...] }
-- Run after 04_soc2_seed_data.sql.
-- ============================================================

BEGIN;

SET search_path TO soc2, core, public;

INSERT INTO soc2.evidence_sufficiency_matrix (
  item_code, control_id, evidence_item_name, control_name,
  mandatory_advisory, evidence_type, sufficiency_criteria, evaluation_criteria, soc_version
) VALUES
('A1', 'CC1', 'Information security policy (comprehensive)', 'Control Environment', 'M', 'Policy document; narrative PDF; standards document',
  '{"must_show": ["Board approval signature/date", "Scope covering all trust services categories", "Policy owner named", "Annual review cycle", "Control environment commitments"]}'::jsonb,
  '{"reviewer_checks": ["Board-approved?", "Dated within 12 months?", "Covers CC1 through CC5?", "Risk mitigation addressed?", "Risk appetite statement present?"]}'::jsonb, '2022'),
('A1', 'CC5', 'Information security policy (comprehensive)', 'Control Activities', 'M', 'Policy document; narrative PDF; standards document',
  '{"must_show": ["Board approval signature/date", "Scope covering all trust services categories", "Policy owner named", "Annual review cycle", "Control environment commitments"]}'::jsonb,
  '{"reviewer_checks": ["Control activities deployed through policies", "Tone at top and structure documented"]}'::jsonb, '2022'),
('A1', 'CC9', 'Information security policy (comprehensive)', 'Risk Mitigation', 'M', 'Policy document; narrative PDF; standards document',
  '{"must_show": ["Board approval signature/date", "Scope covering all trust services categories", "Policy owner named", "Annual review cycle", "Control environment commitments"]}'::jsonb,
  '{"reviewer_checks": ["Risk mitigation and business disruption addressed in policy"]}'::jsonb, '2022'),
('A2', 'CC3', 'Risk assessment methodology & risk register', 'Risk Assessment', 'M', 'Risk assessment document; risk register; scenario analysis',
  '{"must_include": ["Risk assessment methodology", "Risk register with inherent/residual ratings", "Fraud risk scenarios", "Change trigger review process"]}'::jsonb,
  '{"reviewer_checks": ["Methodology documented?", "Risk register current?", "Fraud considered?", "Change events trigger re-assessment?", "Residual risks within tolerance?"]}'::jsonb, '2022'),
('A3', 'CC1', 'Board & management oversight evidence', 'Control Environment', 'M', 'Board minutes; committee reports; management review records',
  '{"must_show": ["Board meeting frequency", "Security/privacy agenda items", "Deficiency communications", "Independent board member attestation"]}'::jsonb,
  '{"reviewer_checks": ["Board meets regularly?", "Security on agenda?", "Deficiencies communicated?", "Board independence demonstrated?"]}'::jsonb, '2022'),
('A3', 'CC4', 'Board & management oversight evidence', 'Monitoring Activities', 'M', 'Board minutes; committee reports; management review records',
  '{"must_show": ["Board meeting frequency", "Security/privacy agenda items", "Deficiency communications", "Independent board member attestation"]}'::jsonb,
  '{"reviewer_checks": ["Deficiencies evaluated and communicated to management/board"]}'::jsonb, '2022'),
('A4', 'CC9', 'Vendor & third-party risk management program', 'Risk Mitigation', 'M', 'Vendor register; risk tier classification; contract excerpts; assessment records',
  '{"must_include": ["Vendor inventory with tier classification", "SLAs and NDAs", "Initial and periodic risk assessments", "Confidentiality/privacy commitments where applicable"]}'::jsonb,
  '{"reviewer_checks": ["All critical vendors inventoried?", "Tiered by risk?", "SLAs present?", "Assessments current?", "Privacy commitments obtained?"]}'::jsonb, '2022'),
('A5', 'A1', 'Business continuity & disaster recovery plan', 'Availability (Capacity, Recovery, Testing)', 'A', 'BCP/DR plan document; test records; alternate processing procedures',
  '{"must_include": ["BCP/DR documented procedures", "Recovery time/point objectives", "Alternate processing infrastructure", "Test results within 12 months"]}'::jsonb,
  '{"reviewer_checks": ["Plan documented?", "RTOs/RPOs set?", "Alternate infrastructure identified?", "Tested within 12 months?", "Lessons learned incorporated?"]}'::jsonb, '2022'),
('A5', 'CC9', 'Business continuity & disaster recovery plan', 'Risk Mitigation', 'M', 'BCP/DR plan document; test records; alternate processing procedures',
  '{"must_include": ["BCP/DR documented procedures", "Recovery time/point objectives", "Alternate processing infrastructure", "Test results within 12 months"]}'::jsonb,
  '{"reviewer_checks": ["Risk mitigation for disruptions", "Environmental protections and recovery testing evidenced"]}'::jsonb, '2022'),
('B1', 'CC6', 'Logical access control policy & procedures', 'Logical and Physical Access Controls', 'M', 'Policy document; procedures; standards',
  '{"must_address": ["Identification and authentication requirements", "User registration/deregistration process", "Role-based access control", "Least privilege principle", "Separation of duties"]}'::jsonb,
  '{"reviewer_checks": ["Policy covers all CC6.1–CC6.3 requirements?", "Roles defined?", "Least privilege addressed?", "Separation of duties documented?"]}'::jsonb, '2022'),
('B2', 'CC6', 'User access list & privileged account inventory', 'Logical and Physical Access Controls', 'M', 'Account listing; AD export; system account reports',
  '{"must_include_per_account": ["Username", "System/application", "Account type (user/admin/service)", "Role assignment", "Last access review date"]}'::jsonb,
  '{"reviewer_checks": ["All systems covered?", "Privileged accounts flagged?", "Service accounts inventoried?", "Last review dated?"]}'::jsonb, '2022'),
('B3', 'CC6', 'Access review records (periodic)', 'Logical and Physical Access Controls', 'M', 'Review reports; sign-off records; exception logs',
  '{"must_show": ["Review date and reviewer", "Systems covered", "Actions taken (revoke/modify/retain)", "Exception handling"]}'::jsonb,
  '{"reviewer_checks": ["Review cadence documented?", "All systems included?", "Actions evidenced?", "Exceptions resolved?"]}'::jsonb, '2022'),
('B4', 'CC6', 'MFA configuration evidence', 'Logical and Physical Access Controls', 'M', 'Configuration exports; architecture diagram; MFA policy',
  '{"must_show": ["MFA implemented at all required access points", "Second factor type and management", "Remote access MFA enforcement", "External access boundary MFA"]}'::jsonb,
  '{"reviewer_checks": ["MFA at all required points?", "Second factor separated from first?", "Remote access covered?", "External boundaries protected?"]}'::jsonb, '2022'),
('B5', 'CC6', 'Credential & encryption key management', 'Logical and Physical Access Controls', 'M', 'Key inventory; rotation records; vault/HSM config; encryption standards',
  '{"must_show": ["Key inventory with algorithm and key length", "Key rotation schedule", "Storage mechanism (vault/HSM)", "Destruction/revocation procedure"]}'::jsonb,
  '{"reviewer_checks": ["Keys inventoried?", "Rotation schedule met?", "Storage appropriately protected?", "Algorithm standards current?"]}'::jsonb, '2022'),
('B6', 'CC6', 'Physical access control evidence', 'Logical and Physical Access Controls', 'M', 'Access control system reports; badge logs; policy',
  '{"must_show": ["Physical access restrictions to authorised personnel", "Process for creating/modifying/removing access", "Regular physical access review"]}'::jsonb,
  '{"reviewer_checks": ["All facility types covered?", "Access modifications documented?", "Periodic reviews evidenced?", "Recovery of devices on departure?"]}'::jsonb, '2022'),
('B7', 'CC6', 'Media disposal & data sanitisation evidence', 'Logical and Physical Access Controls', 'M', 'Disposal certificates; sanitisation records; procedures',
  '{"must_show": ["Disposal/sanitisation procedure", "Certificates or records per asset", "Method appropriate to data sensitivity"]}'::jsonb,
  '{"reviewer_checks": ["Process documented?", "Methods appropriate?", "Assets tracked through disposal?", "Certificates retained?"]}'::jsonb, '2022'),
('B8', 'CC6', 'Boundary protection systems configuration', 'Logical and Physical Access Controls', 'M', 'Firewall configuration; IDS/IPS setup; network topology',
  '{"must_show": ["Firewall rules at boundaries", "IDS/IPS placement and configuration", "Data transmission encryption", "Removable media controls"]}'::jsonb,
  '{"reviewer_checks": ["All network boundaries protected?", "IDS/IPS configured?", "Data in transit encrypted?", "Removable media restricted?"]}'::jsonb, '2022'),
('B9', 'CC6', 'Malware protection & unauthorised software controls', 'Logical and Physical Access Controls', 'M', 'Anti-malware config; update logs; software allowlist; change control evidence',
  '{"must_show": ["Anti-malware on all endpoints/servers", "Update frequency", "Installation restrictions", "Change detection for configuration/software"]}'::jsonb,
  '{"reviewer_checks": ["All systems covered?", "Updates current?", "Installation restricted to authorised personnel?", "Integrity checks in place?"]}'::jsonb, '2022'),
('C1', 'CC7', 'System configuration standards & hardening', 'System Operations', 'M', 'Configuration exports; CIS benchmark results; hardening checklist',
  '{"must_show": ["Defined configuration standard (e.g., CIS)", "Baseline comparison", "Monitoring for deviation", "Vulnerability scan results"]}'::jsonb,
  '{"reviewer_checks": ["Baseline standard identified?", "All system types covered?", "Deviation monitoring active?", "Scans conducted regularly?"]}'::jsonb, '2022'),
('C2', 'CC7', 'Anomaly detection & monitoring configuration', 'System Operations', 'M', 'SIEM config; log source list; alert rules; retention policy',
  '{"must_cover": ["Log sources inventoried", "Alert rules configured for key events", "Retention period meets requirements", "Analysis process defined"]}'::jsonb,
  '{"reviewer_checks": ["All system types logged?", "Alert rules for key events?", "Retention sufficient?", "Analysis process documented?"]}'::jsonb, '2022'),
('C3', 'CC7', 'Security incident evaluation procedures', 'System Operations', 'M', 'Incident management procedures; evaluation workflow; escalation matrix',
  '{"must_show": ["Event-to-incident triage process", "Impact assessment on confidential/personal information", "Communication to responsible parties", "Documentation requirements"]}'::jsonb,
  '{"reviewer_checks": ["Triage criteria defined?", "Confidentiality/privacy impact assessed?", "Communication path clear?", "Incidents documented?"]}'::jsonb, '2022'),
('C4', 'CC7', 'Security incident response & recovery procedures', 'System Operations', 'M', 'Incident response plan; response records; recovery procedures; lessons learned',
  '{"must_include": ["Role assignments", "Containment and remediation steps", "Communication protocols", "Recovery procedures", "Post-incident review and testing"]}'::jsonb,
  '{"reviewer_checks": ["Roles assigned?", "Containment procedures documented?", "Communication protocols defined?", "Recovery tested?", "Root cause analysis performed?"]}'::jsonb, '2022'),
('C5', 'CC8', 'Change management procedures & records', 'Change Management', 'M', 'Change management policy; change records; approval evidence; test records',
  '{"must_show": ["Change policy/process documented", "Change records with approval", "Testing evidence", "Emergency change procedure", "Baseline configuration maintained"]}'::jsonb,
  '{"reviewer_checks": ["All change types covered?", "Approval before implementation?", "Testing documented?", "Separation of duties in deployment?", "Emergency process defined?"]}'::jsonb, '2022'),
('D1', 'CC7', 'Vulnerability scanning & patch management policy', 'System Operations', 'M', 'Policy document; procedures; scanning schedule',
  '{"must_include": ["Scanning frequency", "Severity-based timelines (critical/high/medium)", "System coverage scope", "Exception handling"]}'::jsonb,
  '{"reviewer_checks": ["Policy documented?", "Timelines specific and risk-based?", "All system types in scope?", "Exceptions tracked?"]}'::jsonb, '2022'),
('D2', 'CC7', 'Current vulnerability scan results', 'System Operations', 'M', 'Scan tool output; vulnerability report with severity ratings',
  '{"must_include": ["Scan date", "All in-scope systems covered", "Severity-rated findings", "Remediation status"]}'::jsonb,
  '{"reviewer_checks": ["All systems scanned?", "Scan recent?", "Tool recognised?", "Severities rated?", "Remediation tracked?"]}'::jsonb, '2022'),
('D3', 'CC7', 'Vulnerability remediation tracking log', 'System Operations', 'M', 'Remediation tracker; risk register; action plan records',
  '{"must_show": ["All findings tracked", "Severity-based prioritisation", "Closure evidence per finding", "Risk acceptance for accepted risks"]}'::jsonb,
  '{"reviewer_checks": ["All findings tracked?", "Critical findings addressed within policy timeline?", "Risk acceptance signed?", "Closure verified?"]}'::jsonb, '2022'),
('D4', 'CC4', 'Penetration test reports (annual)', 'Monitoring Activities', 'M', 'Penetration test report; executive summary; remediation plan',
  '{"must_include": ["Independent tester credentials", "Test scope and methodology", "Findings with severity", "Remediation actions"]}'::jsonb,
  '{"reviewer_checks": ["Tester independent?", "Scope adequate?", "Findings rated?", "Remediation in progress?", "Annual cadence?"]}'::jsonb, '2022'),
('E1', 'CC4', 'Monitoring activities & internal audit program', 'Monitoring Activities', 'M', 'Internal audit plan; audit reports; monitoring schedules',
  '{"must_show": ["Mix of ongoing and separate evaluations", "Knowledgeable evaluators", "Deficiencies identified and communicated", "Corrective action tracking"]}'::jsonb,
  '{"reviewer_checks": ["Monitoring program documented?", "Both ongoing and separate evaluations present?", "Deficiencies communicated to senior management/board?", "Corrective action tracked?"]}'::jsonb, '2022'),
('E2', 'CC1', 'Control environment & ethics evidence', 'Control Environment', 'M', 'Code of conduct; ethics training records; HR policy; disciplinary records',
  '{"must_cover": ["Code of conduct/ethics policy", "Commitment of integrity at all levels", "Staff screening and competency assessment", "Accountability mechanisms including disciplinary process"]}'::jsonb,
  '{"reviewer_checks": ["Code of conduct exists and communicated?", "Staff training evidenced?", "Competency assessments performed?", "Accountability mechanism documented?"]}'::jsonb, '2022'),
('E3', 'CC2', 'Information & communication procedures', 'Communication and Information', 'M', 'Communication plan; internal reporting records; external communication evidence',
  '{"must_show": ["Information quality processes", "Internal communication of responsibilities", "Separate reporting channels (e.g., whistleblower)", "External communication processes"]}'::jsonb,
  '{"reviewer_checks": ["Information quality managed?", "Personnel understand responsibilities?", "Separate communication channels exist?", "External communication for incidents defined?"]}'::jsonb, '2022'),
('F1', 'A1', 'Capacity management & availability monitoring', 'Availability (Capacity, Recovery, Testing)', 'A', 'Capacity reports; monitoring dashboards; utilisation data',
  '{"must_include": ["Current capacity baseline", "Usage measurements", "Forecasting method", "Thresholds and change triggers"]}'::jsonb,
  '{"reviewer_checks": ["Capacity measured?", "Forecast covers peak usage?", "Change triggered by forecast breach?", "System resilience considered?"]}'::jsonb, '2022'),
('F2', 'A1', 'Backup & recovery infrastructure evidence', 'Availability (Capacity, Recovery, Testing)', 'A', 'Backup configuration; offsite storage evidence; recovery infrastructure docs; test records',
  '{"must_show": ["Backup procedures and schedule", "Offsite or geographically separate storage", "Alternate processing capability", "Recovery test results"]}'::jsonb,
  '{"reviewer_checks": ["All critical data backed up?", "Offsite storage at adequate distance?", "Alternate processing tested?", "Ransomware threat mitigated?"]}'::jsonb, '2022'),
('G1', 'C1', 'Confidential information identification & retention', 'Confidentiality', 'A', 'Data classification policy; confidential data inventory; retention schedule',
  '{"must_include": ["Definition of confidential information", "Classification and tagging procedure", "Retention period by category", "Disposal procedure with destruction methods"]}'::jsonb,
  '{"reviewer_checks": ["Confidential information defined?", "Classification process operating?", "Retention periods documented?", "Disposal procedure includes destruction?"]}'::jsonb, '2022'),
('G2', 'PI1', 'Processing integrity controls (input/processing/output)', 'Processing Integrity', 'A', 'Input validation rules; processing specs; output distribution procedures; error logs',
  '{"must_cover": ["Input validation rules", "Processing specifications", "Error detection and correction", "Output distribution to intended parties only", "Storage completeness and accuracy"]}'::jsonb,
  '{"reviewer_checks": ["All processing stages covered?", "Input validation operating?", "Error handling documented?", "Output access controlled?", "Storage integrity maintained?"]}'::jsonb, '2022'),
('H1', 'P1', 'Privacy notice & consent management', 'Privacy Notice and Communication', 'A', 'Privacy notice; consent records; data subject communication',
  '{"must_include": ["Current, dated privacy notice", "Purpose specification", "Consent capture mechanism", "Documentation of explicit consent for sensitive information"]}'::jsonb,
  '{"reviewer_checks": ["Privacy notice current?", "Dated?", "Covers all required elements?", "Consent records retained?", "Explicit consent for sensitive data?"]}'::jsonb, '2022'),
('H1', 'P2', 'Privacy notice & consent management', 'Choice and Consent', 'A', 'Privacy notice; consent records; data subject communication',
  '{"must_include": ["Current, dated privacy notice", "Purpose specification", "Consent capture mechanism", "Documentation of explicit consent for sensitive information"]}'::jsonb,
  '{"reviewer_checks": ["Choices communicated?", "Consent obtained and documented?"]}'::jsonb, '2022'),
('H1', 'P3', 'Privacy notice & consent management', 'Collection', 'A', 'Privacy notice; consent records; data subject communication',
  '{"must_include": ["Current, dated privacy notice", "Purpose specification", "Consent capture mechanism", "Documentation of explicit consent for sensitive information"]}'::jsonb,
  '{"reviewer_checks": ["Collection limited to stated purposes?", "Explicit consent for sensitive data obtained?"]}'::jsonb, '2022'),
('H2', 'P3', 'Personal information collection & use controls', 'Collection', 'A', 'Data inventory; collection procedures; data minimisation evidence; use records',
  '{"must_show": ["Collection limited to stated purposes", "Lawful collection methods", "Use only for intended purposes", "Retention schedule aligned to purpose"]}'::jsonb,
  '{"reviewer_checks": ["Collection minimised?", "Methods lawful?", "Use restricted to purpose?", "Retention schedules set?"]}'::jsonb, '2022'),
('H2', 'P4', 'Personal information collection & use controls', 'Use, Retention and Disposal', 'A', 'Data inventory; collection procedures; data minimisation evidence; use records',
  '{"must_show": ["Collection limited to stated purposes", "Lawful collection methods", "Use only for intended purposes", "Retention schedule aligned to purpose"]}'::jsonb,
  '{"reviewer_checks": ["Use limited to purpose?", "Retention schedule documented and enforced?"]}'::jsonb, '2022'),
('H3', 'P4', 'Personal information disposal procedures', 'Use, Retention and Disposal', 'A', 'Deletion procedures; deletion request logs; destruction certificates',
  '{"must_show": ["Deletion procedure", "Deletion request capture and tracking", "Destruction records", "Anonymisation as alternative"]}'::jsonb,
  '{"reviewer_checks": ["Deletion requests tracked?", "Destruction performed and documented?", "Third parties notified?", "Anonymisation verified?"]}'::jsonb, '2022'),
('H4', 'P5', 'Data subject access & correction procedures', 'Access', 'A', 'Access request procedure; correction procedure; request log; response records',
  '{"must_show": ["Identity authentication before access", "Access granted within reasonable time", "Correction/amendment process", "Denial reasons communicated in writing"]}'::jsonb,
  '{"reviewer_checks": ["Authentication required?", "Timelines defined?", "Correction process documented?", "Denials communicated with reasons?"]}'::jsonb, '2022'),
('H5', 'P6', 'Third-party PI disclosure & breach notification', 'Disclosure to Third Parties', 'A', 'Disclosure records; third-party PI agreements; breach notification procedure; breach log',
  '{"must_include": ["Disclosure only with consent or legal basis", "Disclosure records", "Breach detection and notification procedure", "Third-party commitments to report", "Accounting of PI held available to data subjects"]}'::jsonb,
  '{"reviewer_checks": ["Disclosures only authorised?", "Records complete?", "Breach notification procedure defined?", "Third-party commitments obtained?", "Accounting available on request?"]}'::jsonb, '2022'),
('H6', 'P7', 'Privacy quality & monitoring program', 'Quality', 'A', 'Privacy monitoring reports; complaint log; compliance review; training records',
  '{"must_show": ["Data quality processes", "Monitoring of privacy compliance", "Complaint/inquiry process", "Dispute resolution and documentation", "Privacy training"]}'::jsonb,
  '{"reviewer_checks": ["PI accuracy maintained?", "Compliance reviews conducted?", "Complaint process communicated?", "Disputes resolved and documented?", "Training completed?"]}'::jsonb, '2022'),
('H6', 'P8', 'Privacy quality & monitoring program', 'Monitoring and Enforcement', 'A', 'Privacy monitoring reports; complaint log; compliance review; training records',
  '{"must_show": ["Data quality processes", "Monitoring of privacy compliance", "Complaint/inquiry process", "Dispute resolution and documentation", "Privacy training"]}'::jsonb,
  '{"reviewer_checks": ["Monitoring of privacy compliance?", "Sanctions for violations documented and applied?"]}'::jsonb, '2022')
ON CONFLICT (item_code, control_id) DO UPDATE SET
  evidence_item_name = EXCLUDED.evidence_item_name,
  control_name = EXCLUDED.control_name,
  mandatory_advisory = EXCLUDED.mandatory_advisory,
  evidence_type = EXCLUDED.evidence_type,
  sufficiency_criteria = EXCLUDED.sufficiency_criteria,
  evaluation_criteria = EXCLUDED.evaluation_criteria;

COMMIT;
