/**
 * UK bank operational controls — source dataset.
 *
 * Verbatim CSV supplied by the business (uk_bank_operational_controls.csv).
 * Parsed at module load by `parseControls.ts`; this is the single source of truth
 * for the real control library. Audit test metrics (population, sample, exceptions,
 * compliance, residual risk) are NOT in the CSV and are derived deterministically
 * in `deriveMetrics.ts` for the demo dashboard.
 */
export const UK_CONTROLS_CSV = `Domain,Domain_Code,Step_No,SOP_Step,Risk_ID,Risk_Statement,Control_ID,Control_Description,Control_Nature,Control_Source,Automation_Level,Primary_Obligation,Issuing_Body,Evidence_Type,Evidence_Source_System,Testing_Frequency,Control_Owner_Role
Customer Onboarding & KYC,ONB,1,Application & Data Capture / Intake,ONB-R01,"Failure to capture complete, accurate and lawful customer data at intake could result in defective downstream CDD and unlawful processing of personal data",ONB-01,"Digital onboarding portal enforces mandatory-field validation, consent capture and automated duplicate-record check before an application can progress",Preventive,Internal,Automated,"Money Laundering, Terrorist Financing & Transfer of Funds Regs 2017 (MLR 2017) reg 27-28",HM Treasury,Screenshot/Configuration Extract,Digital onboarding portal; CRM,Quarterly,Onboarding Operations Manager
Customer Onboarding & KYC,ONB,2,Initial Data Completeness & Eligibility Check,ONB-R02,Failure to screen out ineligible or duplicate applicants could result in onboarding outside risk appetite,ONB-02,System eligibility rules (age/residency/entity type) and duplicate checks auto-block or refer non-conforming applications,Preventive,Internal,Automated,MLR 2017,HM Treasury,Exception Report,CRM; customer master,Quarterly,Onboarding Analyst Team Lead
Customer Onboarding & KYC,ONB,3,Identity Verification & CDD,ONB-R03,Failure to verify identity from reliable independent sources could result in onboarding of false or undisclosed identities in breach of CDD duties,ONB-03,eIDV/ID&V decisioning engine verifies identity to a defined evidential standard; no activation without a recorded CDD pass; referrals worked manually,Preventive,External,Automated,MLR 2017 reg 27-28 (CDD),HM Treasury,System Log/Export,KYC/CDD platform; eIDV engine,Quarterly,KYC/CDD Team Manager
Customer Onboarding & KYC,ONB,4,UBO / Beneficial Ownership & Control Assessment,ONB-R04,Failure to identify and verify beneficial owners over 25% and control structures could result in onboarding entities that conceal illicit ownership,ONB-04,"KYB workflow maps ownership to UBO level, cross-checks the Companies House PSC feed and requires verification evidence for each in-scope owner before approval",Preventive,External,Semi-automated,MLR 2017 reg 5 & 28,HM Treasury,System Log/Export,KYC platform; Companies House feed,Quarterly,KYB / Entity Onboarding Manager
Customer Onboarding & KYC,ONB,5,"Sanctions, PEP & Adverse-Media Screening",ONB-R05,Failure to screen customers and connected parties against sanctions and PEP lists could result in dealing with a designated person and a strict-liability sanctions breach,ONB-05,"Name-screening tool runs customer, UBO, directors and connected parties against current sanctions/PEP/adverse-media lists; true-match hits block activation pending disposition",Preventive,External,Automated,Sanctions & Anti-Money Laundering Act 2018 (SAMLA),HM Treasury,Exception Report,Name-screening/watchlist tool; case management,Monthly,Financial Crime Screening Manager
Customer Onboarding & KYC,ONB,6,Customer Risk Assessment / Rating,ONB-R06,"Failure to risk-rate customers across product, geography, channel and ownership factors could result in mis-tiered CDD and undetected high-risk relationships",ONB-06,Customer risk-rating engine scores defined factors to a documented methodology and sets the CDD tier; overrides require recorded rationale and approval,Preventive,Internal,Automated,MLR 2017 reg 18-18A (risk-based approach),HM Treasury,Screenshot/Configuration Extract,Risk-rating engine; AML platform,Quarterly,Financial Crime Risk Manager
Customer Onboarding & KYC,ONB,7,Enhanced Due Diligence (high-risk / PEP),ONB-R07,Failure to establish source of wealth/funds and obtain senior sign-off for high-risk/PEP relationships could result in onboarding illicit funds without mitigation,ONB-07,"EDD workflow mandates SoW/SoF evidence, enhanced purpose-of-account and documented senior/MLRO-delegate sign-off before high-risk or PEP accounts activate",Preventive,External,Semi-automated,"MLR 2017 reg 33-35 (EDD, PEPs, high-risk third countries)",HM Treasury,Sign-off/Attestation Memo,EDD / case workflow system,Quarterly,EDD Specialist / MLRO Delegate
Customer Onboarding & KYC,ONB,8,Onboarding Decision & Approval,ONB-R08,Failure to record accept/reject/refer decisions within delegated authority could result in unaccountable acceptance of financial-crime risk,ONB-08,Workflow enforces decision plus rationale within a delegated-authority matrix; high-risk cases route to the Nominated Officer/MLRO; the decision log is immutable,Preventive,Internal,Semi-automated,MLR 2017,HM Treasury,Sign-off/Attestation Memo,Workflow/case system; core banking,Quarterly,Onboarding Approvals Manager / MLRO
Customer Onboarding & KYC,ONB,9,Account Activation & Customer Record Creation,ONB-R09,"Failure to create an accurate single golden record with correct product and risk attributes could result in fragmented CDD, screening gaps and reporting error",ONB-09,"Golden-record creation reconciles onboarding data across core banking and CRM; activation is gated on CDD, screening and approval flags all being present",Preventive,Internal,Semi-automated,MLR 2017 (recordkeeping),HM Treasury,Reconciliation Statement,Core banking; CRM; customer master,Quarterly,Customer Master Data Manager
Customer Onboarding & KYC,ONB,10,Customer Communication & Terms Issuance,ONB-R10,"Failure to issue clear terms, pricing and FSCS/depositor-protection messaging could result in a Consumer Duty understanding breach and depositor-protection information failure",ONB-10,"Templated communication pack (decision, terms, current FSCS information sheet) is auto-issued, version-controlled and comprehension-tested",Preventive,External,Semi-automated,FCA BCOBS,FCA,Policy Document + Version History,Customer comms platform; doc generation,Annual,Customer Communications Manager
Customer Onboarding & KYC,ONB,11,Ongoing / Trigger-Based Monitoring & Maintenance,ONB-R11,"Failure to act on material change triggers (ownership, behaviour, risk events) could result in stale CDD and undetected financial-crime risk",ONB-11,Perpetual-KYC/monitoring tool raises event-driven review triggers on defined changes; each trigger is worked to SLA with re-verification where required,Detective,Internal,Semi-automated,MLR 2017 reg 28(11) ongoing monitoring,HM Treasury,Exception Report,Perpetual KYC tool; CRM,Quarterly,KYC Operations Manager
Customer Onboarding & KYC,ONB,12,Periodic / Trigger-Based Re-KYC / Refresh,ONB-R12,Failure to refresh CDD by risk tier on schedule could result in expired due diligence on high-risk customers,ONB-12,Review-queue enforces risk-tiered refresh cycles; screening and data are re-run and risk re-scored; overdue reviews escalate and can restrict the account,Detective,Internal,Semi-automated,MLR 2017 reg 28(11),HM Treasury,Exception Report,KYC platform / review queue,Quarterly,KYC Refresh / Lifecycle Manager
Customer Onboarding & KYC,ONB,13,Offboarding / Exit & Recordkeeping,ONB-R13,"Failure to execute exit/de-risking with correct notification and statutory record retention could result in tipping-off, unlawful data retention or loss of evidential records",ONB-13,"Closure workflow sequences financial-crime, legal and customer-notification checks, applies the 5-year retention schedule and archives CDD/SAR-linked records; erasure is suppressed where retention applies",Corrective,External,Semi-automated,MLR 2017 reg 40 (5-year retention),HM Treasury,System Log/Export,Case management; records archive,Annual,Customer Exit / Records Manager
Deposits & Account Servicing,DEP,1,Product Setup & Account Parameter Configuration,DEP-R01,"Failure to configure a deposit product within approved rules (rate, fees, terms, limits) could result in customer detriment and a fair-value breach",DEP-01,Product parameters are set from the approved product master with maker-checker sign-off; configuration changes are reconciled to the product-approval record,Preventive,Internal,Semi-automated,FCA BCOBS,FCA,Reconciliation Statement,Core banking; product master; pricing engine,Quarterly,Product Operations Manager
Deposits & Account Servicing,DEP,2,Account Opening / Activation,DEP-R02,Failure to gate account opening on completed CDD and approval could result in activation of unverified customers,DEP-02,"Core banking blocks activation until onboarding CDD, screening and approval flags are satisfied; exceptions require a documented override",Preventive,External,Automated,MLR 2017 (CDD gate),HM Treasury,Exception Report,Core banking,Quarterly,Deposit Operations Manager
Deposits & Account Servicing,DEP,3,Product Selection & Disclosure,DEP-R03,"Failure to disclose product features, rates and costs clearly could result in a consumer-understanding breach and unsuitable take-up",DEP-03,A pre-contract disclosure pack is presented and acknowledgement captured before account opening; content is comprehension-tested,Preventive,External,Semi-automated,Consumer Duty (consumer understanding),FCA,Sample Testing Output,Doc generation; onboarding portal,Annual,Product Governance Lead
Deposits & Account Servicing,DEP,4,Mandate & Signatory Setup,DEP-R04,Failure to capture correct mandate and signatory authorities could result in unauthorised account operation and payment fraud,DEP-04,"Signatory mandate is captured, verified against authorised persons and dual-approved before becoming operative; changes are re-verified",Preventive,Internal,Semi-automated,Firm mandate rules,Internal,Sample Testing Output,Core banking; mandate system,Quarterly,Account Services Manager
Deposits & Account Servicing,DEP,5,Interest & Fee Application / Capitalisation,DEP-R05,Failure to apply interest and fees per agreed terms could result in systematic over/undercharging and customer redress,DEP-05,"The interest/fee engine applies parameters from the product master; a periodic recalculation reconciliation detects deviations, which are corrected",Detective,Internal,Automated,FCA BCOBS,FCA,Reconciliation Statement,Core banking; interest/fee engine,Monthly,Deposit Operations Manager
Deposits & Account Servicing,DEP,6,Overdraft Limit Management,DEP-R06,Failure to assess creditworthiness and repeat use before overdraft limits could result in unaffordable lending and a CONC breach,DEP-06,Overdraft grant/increase runs affordability and repeat-use checks per CONC; limits above threshold require review; persistent-use customers are contacted,Preventive,External,Semi-automated,FCA CONC 5A (overdraft pricing/creditworthiness),FCA,Sample Testing Output,Core banking; decisioning engine,Quarterly,Retail Credit / Overdraft Manager
Deposits & Account Servicing,DEP,7,Transaction & Statement Processing,DEP-R07,Failure to process transactions and issue accurate statements could result in information breaches and customer detriment,DEP-07,Statement generation is reconciled to the ledger; exceptions (missing or duplicate statements) are reported and corrected within SLA,Detective,Internal,Automated,FCA BCOBS (statements),FCA,Reconciliation Statement,Core banking; statement/output system,Monthly,Account Servicing Manager
Deposits & Account Servicing,DEP,8,Standing Data Maintenance & Account Maintenance Requests,DEP-R08,"Failure to control standing-data amendments could result in fraud (e.g. diverting funds via contact changes), data inaccuracy and screening gaps",DEP-08,"Sensitive standing-data changes (address, name, contact) require verification and dual authorisation; high-risk changes trigger re-screening and a fraud check",Preventive,Internal,Semi-automated,UK GDPR (accuracy),ICO,System Log/Export,Core banking; service request platform,Quarterly,Account Servicing Team Lead
Deposits & Account Servicing,DEP,9,Ongoing Servicing,DEP-R09,Failure to process servicing requests accurately and on time could result in service failures and customer harm,DEP-09,Servicing requests are tracked to SLA with quality sampling; aged or failed items escalate,Detective,Internal,Semi-automated,FCA BCOBS,FCA,Exception Report,Core banking; service request platform,Quarterly,Account Servicing Manager
Deposits & Account Servicing,DEP,10,Dormancy & Unclaimed Balances,DEP-R10,"Failure to identify, protect and correctly transfer dormant balances could result in misuse of dormant accounts or wrongful transfer to the reclaim fund",DEP-10,"Dormancy engine flags inactivity thresholds, restricts outflows, applies tracing, and governs eligible transfers to the reclaim fund with reconciliation and a reactivation path",Preventive,Internal,Semi-automated,Dormant Assets Act 2022,HM Treasury,Reconciliation Statement,Dormancy module / dormant register,Annual,Dormant Accounts Operations Manager
Deposits & Account Servicing,DEP,11,Account Restriction / Freeze / Hold Processing,DEP-R11,"Failure to place or lift holds correctly for fraud, sanctions or legal orders could result in dissipation of frozen funds or wrongful denial of access",DEP-11,Hold placement/removal follows documented authority (order / sanctions match / fraud case) with review dates; sanctions freezes are reconciled to OFSI reporting,Preventive,External,Semi-automated,POCA 2002,NCA,Regulatory Filing Copy,Core banking; legal orders / case system,Quarterly,Account Controls Manager
Deposits & Account Servicing,DEP,12,Single Customer View (SCV) / FSCS Depositor Protection,DEP-R12,"Failure to produce accurate, complete SCV/exclusion files at the £120k limit could result in delayed FSCS payout and a PRA breach in resolution",DEP-12,"The SCV engine produces eligibility/exclusion files to PRA specification, reconciled to the customer master, with 24-hour production capability tested at the current limit",Detective,External,Automated,PRA Rulebook Depositor Protection Part,PRA,Reconciliation Statement,SCV production tool; reg reporting data mart,Annual,Depositor Protection / SCV Reporting Manager
Deposits & Account Servicing,DEP,13,Account Closure & Switching,DEP-R13,Failure to execute closures/switches within CASS guarantee timelines could result in a scheme breach and customer detriment,DEP-13,CASS switch is executed to the 7-day guarantee with redirection; failed or late switches trigger guarantee redress; final statement and balance are reconciled,Detective,External,Semi-automated,Current Account Switch Service (Pay.UK CASS rules),Pay.UK,Exception Report,Core banking; CASS switching platform,Quarterly,Switching Operations Manager
Deposits & Account Servicing,DEP,14,Access-to-Cash & Servicing Channels,DEP-R14,Failure to maintain reasonable cash access for a designated large firm could result in an FCA access-to-cash breach,DEP-14,Cash-access assessments are performed before branch/ATM closures; identified gaps are addressed (e.g. banking hub) per FCA rules; MI tracks coverage,Preventive,External,Semi-automated,FSMA 2023 access-to-cash powers,FCA,Board/Committee Minute Extract,Branch/ATM systems; assessment repository,Annual,Branch & Channel Operations Manager
Deposits & Account Servicing,DEP,15,Error Correction & Adjustment,DEP-R15,Failure to detect and correct servicing errors and mispostings could result in customer detriment and ledger inaccuracy,DEP-15,"Adjustments require root-cause, dual authorisation and redress where due; the adjustment ledger is reconciled and sampled",Corrective,Internal,Semi-automated,FCA BCOBS,FCA,Reconciliation Statement,Core banking; adjustments ledger,Monthly,Deposit Operations Manager
Deposits & Account Servicing,DEP,16,Complaints / Exceptions Handling,DEP-R16,Failure to route servicing complaints into the DISP process could result in missed statutory timelines and FOS exposure,DEP-16,Servicing exceptions/complaints are tagged and handed to the complaints system with the DISP clock started; the interface is reconciled so no complaint is lost,Detective,External,Semi-automated,FCA DISP (interface),FCA,Reconciliation Statement,Complaints platform; case management,Quarterly,Customer Operations Team Lead
Complaints & Redress,CMP,1,Complaint Capture & Logging,CMP-R01,Failure to capture and log complaints at first contact could result in the DISP clock never starting and statutory timelines being breached,CMP-01,"All channels feed a single complaints system that records receipt date/time and category, automatically starting the DISP clock",Preventive,External,Semi-automated,FCA DISP 1 (complaint handling),FCA,System Log/Export,Complaints management system; CRM/telephony,Monthly,Complaints Intake Manager
Complaints & Redress,CMP,2,"Acknowledgement, Triage & Classification",CMP-R02,Failure to acknowledge and classify by DISP category and deadline could result in missed summary-resolution and 8-week deadlines,CMP-02,An SLA tracker drives acknowledgement and deadline monitoring by DISP category; vulnerability and severity are flagged for prioritised handling,Detective,External,Automated,FCA DISP 1.4-1.6,FCA,Exception Report,Complaints system; SLA tracker,Monthly,Complaints Team Leader
Complaints & Redress,CMP,3,Investigation & Root Cause,CMP-R03,Failure to investigate fairly on the evidence could result in wrong outcomes and unfair customer treatment,CMP-03,"Investigations follow an evidence checklist (records, calls, correspondence); decisions are quality-assured against the fairness standard",Detective,Internal,Manual,FCA DISP 1.4 (fair investigation),FCA,Sample Testing Output,Complaints system; case management,Monthly,Complaints Quality Manager
Complaints & Redress,CMP,4,Root Cause Assessment (case-level classification),CMP-R04,Failure to classify root cause at case level could result in systemic issues going undetected,CMP-04,Each case is coded to a root-cause taxonomy; codes are aggregated for thematic detection and miscoding is sampled,Detective,Internal,Semi-automated,FCA DISP 1.3 (root-cause analysis),FCA,Sample Testing Output,Complaints system,Quarterly,Complaints Root-Cause Analyst Lead
Complaints & Redress,CMP,5,Outcome Decision,CMP-R05,Failure to reach fair and consistent outcomes could result in inconsistent redress and FOS overturns,CMP-05,Outcome decisions follow a decision framework with sign-off thresholds; consistency is reviewed via calibration sampling,Detective,Internal,Manual,FCA DISP,FCA,Sign-off/Attestation Memo,Complaints system,Monthly,Complaints Manager
Complaints & Redress,CMP,6,Redress / Remediation Calculation & Payment,CMP-R06,Failure to calculate and pay redress correctly could result in under- or over-compensation and further complaints,CMP-06,"Redress is calculated using the approved methodology (including interest), independently checked before payment and reconciled to payments made",Detective,External,Semi-automated,FCA DISP App,FCA,Reconciliation Statement,Complaints system; payment system,Monthly,Redress Operations Manager
Complaints & Redress,CMP,7,Final Response & FOS Rights,CMP-R07,Failure to issue a compliant final response with FOS rights and the 6-month referral notice could result in a DISP breach and prejudiced customer rights,CMP-07,"The final-response template mandates outcome, reasons and FOS referral rights/time limit; issuance within deadline is monitored",Preventive,External,Semi-automated,FCA DISP 1.6 (final response,FCA,Sample Testing Output,Complaints system; doc generation,Monthly,Complaints Team Leader
Complaints & Redress,CMP,8,FOS Referral / Escalation Handling,CMP-R08,"Failure to cooperate with FOS within timelines could result in default findings, case fees and reputational harm",CMP-08,FOS cases are tracked to FOS deadlines with evidence packs supplied on time; FOS outcomes are analysed and fed back to root cause,Detective,External,Semi-automated,Financial Ombudsman Service scheme rules (FSMA 2000 Part XVI,FOS,Exception Report,Complaints system; FOS case tracker,Quarterly,FOS Liaison Manager
Complaints & Redress,CMP,9,Root-Cause / Thematic Analysis & Feedback,CMP-R09,Failure to analyse themes and feed back could result in recurring harm and product-level failures going unaddressed,CMP-09,Periodic thematic analysis identifies systemic drivers and raises actions to product/process owners; action closure is tracked,Corrective,Internal,Semi-automated,FCA DISP 1.3,FCA,Sample Testing Output,Complaints system; issue tracker,Quarterly,Conduct / Complaints Insight Lead
Complaints & Redress,CMP,10,Mass Remediation / Past-Business Review / Thematic Remediation Programme,CMP-R10,Failure to run mass remediation correctly could result in incomplete population identification and inconsistent redress at scale,CMP-10,"The remediation programme governs population definition, redress rules, QA sampling and independent oversight; completeness is reconciled to the source population",Corrective,External,Semi-automated,FCA DISP,FCA,Reconciliation Statement,Remediation case system; data warehouse,Event-triggered,Remediation Programme Director
Complaints & Redress,CMP,11,"Complaints MI, Governance & Regulatory Reporting",CMP-R11,Failure to report complaints MI accurately to the FCA could result in a misstated regulatory return and supervisory concern,CMP-11,"The complaints return is compiled from the complaints system, reconciled and signed off before submission; board MI is produced",Detective,External,Semi-automated,FCA DISP 1.10 complaints reporting,FCA,Regulatory Filing Copy,Complaints system; reg reporting,Quarterly,Complaints MI / Regulatory Reporting Manager
Financial Crime (AML/CTF & Sanctions),FC,1,Business-Wide Risk Assessment (BWRA),FC-R01,Failure to maintain a current firm-wide financial-crime risk assessment could result in mis-calibrated controls and an MLR reg 18 breach,FC-01,"A documented BWRA scores ML/TF/PF and sanctions risk across products, customers, geographies and channels, is refreshed at least annually and on material change, and drives the control framework",Preventive,External,Manual,MLR 2017 reg 18 (firm risk assessment),HM Treasury,Policy Document + Version History,GRC / risk platform,Annual,MLRO / Financial Crime Risk Head
Financial Crime (AML/CTF & Sanctions),FC,2,Policy & Control Framework Maintenance,FC-R02,"Failure to maintain compliant AML policies, controls and an MLRO could result in systemic control gaps and regulatory censure",FC-02,"AML policies and procedures are version-controlled, approved by the MLRO/board and mapped to obligations; an annual MLRO report evidences effectiveness",Preventive,External,Manual,"MLR 2017 reg 19-21 (policies, controls, MLRO)",HM Treasury,Policy Document + Version History,GRC / policy repository,Annual,MLRO
Financial Crime (AML/CTF & Sanctions),FC,3,Customer Risk Profiling,FC-R03,Failure to profile customer risk consistently could result in under-monitored high-risk customers,FC-03,The risk-rating model applies documented factors and thresholds; ratings drive monitoring intensity and are periodically recalibrated and back-tested,Preventive,Internal,Automated,MLR 2017 reg 18A,HM Treasury,Screenshot/Configuration Extract,AML platform; risk-rating engine,Quarterly,Financial Crime Risk Manager
Financial Crime (AML/CTF & Sanctions),FC,4,Screening Setup / List Management,FC-R04,Failure to keep screening lists current and correctly configured could result in missed sanctions/PEP matches,FC-04,Sanctions/PEP/adverse-media lists are ingested from authoritative sources on a defined SLA; list-load completeness and matching thresholds are controlled and change-managed,Preventive,External,Automated,SAMLA 2018,HM Treasury,System Log/Export,Screening tool; list-management system,Monthly,Sanctions Systems Manager
Financial Crime (AML/CTF & Sanctions),FC,5,Transaction Monitoring & Alert Generation,FC-R05,Failure to monitor transactions for suspicious activity could result in undetected money laundering and missed SARs,FC-05,"Transaction-monitoring rules/scenarios generate alerts against tuned thresholds; rule coverage and tuning are governed, documented and periodically validated",Detective,Internal,Automated,MLR 2017 reg 28(11) ongoing monitoring,HM Treasury,Screenshot/Configuration Extract,Transaction monitoring system,Quarterly,Transaction Monitoring Manager
Financial Crime (AML/CTF & Sanctions),FC,6,Alert Triage & Investigation,FC-R06,Failure to triage and investigate alerts promptly could result in a backlog and undetected suspicious activity,FC-06,Alerts are worked to SLA with documented rationale; quality-assurance sampling checks disposition quality and escalation to SAR where indicated,Detective,Internal,Semi-automated,MLR 2017,HM Treasury,Sample Testing Output,Case management system,Monthly,Financial Crime Investigations Manager
Financial Crime (AML/CTF & Sanctions),FC,7,"Sanctions Screening, Interdiction & Asset Freeze",FC-R07,Failure to interdict payments to designated persons and freeze/report assets could result in a strict-liability sanctions breach and OFSI enforcement,FC-07,Real-time payment/name screening blocks or holds hits pending disposition; confirmed matches are frozen and reported to OFSI within the required timeframe,Preventive,External,Automated,SAMLA 2018,HM Treasury,Regulatory Filing Copy,Screening tool; case management,Monthly,Sanctions Operations Manager
Financial Crime (AML/CTF & Sanctions),FC,8,PEP & Adverse Media Management,FC-R08,Failure to identify and proportionately manage PEP relationships could result in unmanaged corruption risk or unfair de-risking,FC-08,PEP hits are risk-assessed and approved at the appropriate level with EDD and enhanced monitoring; proportionality (esp. domestic PEPs) is documented and reviewed,Preventive,External,Semi-automated,MLR 2017 reg 35 (PEPs),HM Treasury,Sample Testing Output,Case management; EDD workflow,Quarterly,Financial Crime Advisory Manager
Financial Crime (AML/CTF & Sanctions),FC,9,"SAR Assessment, MLRO Review & Submission",FC-R09,Failure to assess and submit SARs (and seek DAML where needed) could result in a POCA offence and tipping-off exposure,FC-09,"Internal disclosures are reviewed by the Nominated Officer/MLRO, who decides and submits SARs/DAML requests to the NCA within statutory expectations; decisions are logged",Detective,External,Semi-automated,POCA 2002 (SAR duty),UK Parliament,System Log/Export,SAR workflow; NCA SAR portal,Monthly,Nominated Officer / MLRO
Financial Crime (AML/CTF & Sanctions),FC,10,Post-SAR Account Restriction,FC-R10,Failure to manage accounts consistently with a submitted SAR/DAML could result in tipping-off or dissipation of criminal property,FC-10,"Where a SAR/DAML is live, defined restrictions are applied within the moratorium and customer communications are controlled to avoid tipping-off; actions are logged",Corrective,External,Semi-automated,POCA 2002 (tipping-off,UK Parliament,System Log/Export,Case management; core banking,Quarterly,Financial Crime Operations Manager
Financial Crime (AML/CTF & Sanctions),FC,11,Anti-Bribery & Corruption / Gifts & Hospitality,FC-R11,Failure to maintain adequate anti-bribery procedures could result in a corporate s7 offence under the Bribery Act,FC-11,"A gifts & hospitality register with thresholds and approvals, plus risk-based ABC due diligence on third parties, evidences adequate procedures; breaches are investigated",Preventive,External,Semi-automated,Bribery Act 2010 (incl. s7 failure to prevent bribery),UK Parliament / SFO / Ministry of Justice,Sign-off/Attestation Memo,G&H register; GRC platform,Annual,Anti-Bribery & Corruption Officer
Financial Crime (AML/CTF & Sanctions),FC,12,High-Risk / EDD & Exit / Restriction Decisions,FC-R12,Failure to apply EDD or to make and document exit/restriction decisions fairly could result in either unmitigated crime risk or unfair customer exit,FC-12,High-risk relationships receive EDD; exit/restriction decisions follow a documented framework with senior sign-off and fair-treatment checks; rationale is retained,Preventive,External,Semi-automated,MLR 2017 reg 33-35,HM Treasury,Sign-off/Attestation Memo,EDD workflow; case management,Quarterly,Financial Crime EDD Manager
Financial Crime (AML/CTF & Sanctions),FC,13,"Financial Crime Governance, MI & Reporting",FC-R13,Failure to govern and report financial-crime MI (incl. REP-CRIM) could result in a misstated regulatory return and weak board oversight,FC-13,"Financial-crime MI is reported to the board on a defined cadence; the REP-CRIM return is compiled, reconciled and signed off before submission",Detective,External,Semi-automated,FCA SUP 16 REP-CRIM annual return,FCA,Regulatory Filing Copy,GRC platform; RegData,Annual,Financial Crime MI / Reporting Manager
Financial Crime (AML/CTF & Sanctions),FC,14,Training & Awareness,FC-R14,Failure to train staff on financial-crime obligations could result in missed detection and an MLR reg 24 breach,FC-14,Role-based financial-crime training is assigned and completion tracked to a threshold; effectiveness is tested and non-completers escalated,Preventive,External,Automated,MLR 2017 reg 24 (training),HM Treasury,System Log/Export,Learning management system (LMS),Annual,Financial Crime Training Lead
Fraud & Scams Management,FRD,1,Fraud Risk / Typology Assessment & Rules Design,FRD-R01,Failure to assess emerging fraud typologies and design detection rules could result in preventable fraud losses and customer harm,FRD-01,"A fraud typology assessment drives detection rules/models; rule coverage and effectiveness are governed, versioned and periodically reviewed against loss data",Preventive,Internal,Semi-automated,FCA Consumer Duty,FCA,Policy Document + Version History,Fraud strategy / rules repository,Quarterly,Fraud Strategy Manager
Fraud & Scams Management,FRD,2,Real-Time Fraud Detection & Profiling,FRD-R02,Failure to detect fraudulent transactions in real time could result in completed fraud and unrecoverable losses,FRD-02,A real-time fraud engine scores transactions and holds/steps-up high-risk payments per tuned thresholds; model performance is monitored for drift,Preventive,Internal,Automated,PSRs 2017 (unauthorised transactions),HM Treasury,Screenshot/Configuration Extract,Fraud detection engine,Monthly,Fraud Detection Manager
Fraud & Scams Management,FRD,3,Fraud Signal Intake & Triage,FRD-R03,Failure to intake and triage fraud signals promptly could result in delayed intervention and larger losses,FRD-03,Fraud alerts and external intelligence are triaged to SLA and prioritised by risk; disposition quality is sampled,Detective,Internal,Semi-automated,FCA Consumer Duty,FCA,Exception Report,Fraud case management,Monthly,Fraud Operations Manager
Fraud & Scams Management,FRD,4,"Alert Management, Intervention & Customer Contact / Warnings",FRD-R04,Failure to intervene and warn customers effectively could result in avoidable scam losses and weaker reimbursement outcomes,FRD-04,High-risk payments trigger tailored warnings/holds and customer contact; interventions and effectiveness (loss prevented) are logged and reviewed,Detective,Internal,Semi-automated,FCA Consumer Duty,FCA,System Log/Export,Fraud case management; telephony,Monthly,Fraud Interventions Manager
Fraud & Scams Management,FRD,5,Payment Delay / Intervention (up to D+4),FRD-R05,Failure to apply the payment-delay power within legal limits could result in either unchecked scam payments or unlawful payment delay,FRD-05,Payments meeting fraud-suspicion criteria are delayed within the statutory window with defined re-review and customer communication; delays are time-bound and logged,Preventive,External,Semi-automated,Payment Services (Amendment) Regs 2024 (delay power),HM Treasury,Exception Report,Payment engine; fraud case management,Monthly,Fraud Operations Manager
Fraud & Scams Management,FRD,6,Fraud Case Investigation,FRD-R06,Failure to investigate fraud cases fairly and completely could result in wrong liability outcomes and complaints,FRD-06,Cases are investigated to an evidence standard with documented decisions; QA sampling checks fairness and consistency of liability decisions,Detective,Internal,Manual,PSRs 2017,HM Treasury,Sample Testing Output,Fraud case management,Monthly,Fraud Investigations Manager
Fraud & Scams Management,FRD,7,APP Scam Claim Intake & Assessment,FRD-R07,Failure to intake and assess APP scam claims to the scheme standard could result in wrongful denial/delay and a reimbursement-rule breach,FRD-07,"APP claims are logged, assessed against the reimbursement rules and vulnerability considerations, and decided within the 5-business-day standard; exceptions escalate",Detective,External,Semi-automated,PSR APP scam reimbursement requirement (Faster Payments),Payment Systems Regulator,Exception Report,APP claims / fraud case system,Monthly,APP Reimbursement Manager
Fraud & Scams Management,FRD,8,Reimbursement Decision & Liability Apportionment,FRD-R08,Failure to decide reimbursement and apportion liability correctly could result in mis-payment and interbank disputes,FRD-08,Reimbursement decisions apply the scheme criteria and 50:50 liability split; apportionment is calculated and reconciled between sending/receiving PSPs via the claims system,Detective,External,Semi-automated,PSR APP reimbursement requirement (50:50 sending/receiving),PSR,Reconciliation Statement,Reimbursement claims system (RCMS),Monthly,APP Reimbursement Manager
Fraud & Scams Management,FRD,9,Mule / Receiving-Account Controls & Investigation,FRD-R09,Failure to detect and control mule/receiving accounts could result in laundering of scam proceeds and reimbursement liability,FRD-09,"Receiving-account monitoring flags mule indicators, freezes and investigates suspect accounts, files SARs and shares intelligence; actions are logged",Detective,Internal,Semi-automated,MLR 2017,HM Treasury,Exception Report,Fraud/AML case management,Monthly,Mule Investigations Manager
Fraud & Scams Management,FRD,10,"Recovery, Clawback & Interbank Liaison",FRD-R10,Failure to pursue recovery and interbank clawback could result in avoidable net losses and scheme non-compliance,FRD-10,Recovery/clawback requests are raised to counterparties within scheme timelines; recovered funds are reconciled and net loss tracked,Corrective,External,Semi-automated,Pay.UK reimbursement / recovery rules,Pay.UK,Reconciliation Statement,Reimbursement claims system; nostro reconciliation,Monthly,Fraud Recovery Manager
Fraud & Scams Management,FRD,11,"Fraud MI, Loss Recording, Reporting & Tuning",FRD-R11,Failure to record losses and report fraud MI accurately could result in mis-tuned controls and misreported performance,FRD-11,Fraud losses are recorded to a taxonomy; MI feeds board reporting and PSR performance returns; detection rules are re-tuned from loss trends,Detective,Internal,Semi-automated,FCA Consumer Duty,FCA,Regulatory Filing Copy,Fraud MI / loss database,Quarterly,Fraud MI Manager
Fraud & Scams Management,FRD,12,Law-Enforcement / Industry Data Sharing,FRD-R12,Failure to share fraud intelligence with law enforcement and industry could result in missed prevention and enabling repeat fraud,FRD-12,Confirmed fraud is reported to CIFAS/Action Fraud/NCA per defined routes and timelines; markers are placed and inbound intelligence actioned; sharing is logged,Detective,External,Semi-automated,POCA 2002,NCA,System Log/Export,Fraud case management; CIFAS interface,Quarterly,Fraud Intelligence Manager
Lending Origination & Underwriting,LEN,1,Application & Data Capture,LEN-R01,"Failure to capture complete, accurate application data could result in flawed affordability and credit decisions",LEN-01,The origination system enforces mandatory data capture and validation with consent; incomplete applications cannot progress to decisioning,Preventive,Internal,Automated,FCA CONC 2/4 (consumer credit),FCA,Screenshot/Configuration Extract,Loan origination system (LOS); CRM,Quarterly,Origination Operations Manager
Lending Origination & Underwriting,LEN,2,Eligibility & Completeness Check,LEN-R02,Failure to check eligibility and completeness could result in progressing ineligible or out-of-policy applications,LEN-02,System rules validate product eligibility and completeness; non-conforming cases are referred or declined with recorded reason,Preventive,Internal,Automated,FCA CONC/MCOB,FCA,Exception Report,LOS; policy engine,Quarterly,Underwriting Operations Lead
Lending Origination & Underwriting,LEN,3,Credit Bureau Interrogation / Credit File Pull,LEN-R03,Failure to obtain and use credit-reference data correctly could result in inaccurate affordability assessment and unlawful processing,LEN-03,A credit-file pull is performed with lawful basis and used in decisioning; bureau-data quality and consent are controlled; searches are logged,Preventive,External,Automated,FCA CONC 5 (creditworthiness),FCA,System Log/Export,LOS; CRA interface,Quarterly,Credit Risk Operations Manager
Lending Origination & Underwriting,LEN,4,Creditworthiness & Affordability Assessment,LEN-R04,Failure to assess affordability and creditworthiness could result in unaffordable lending and a CONC/MCOB breach with customer harm,LEN-04,Affordability is assessed against income/expenditure and stress rules per CONC/MCOB; the decision engine enforces policy and records affordability evidence,Preventive,External,Semi-automated,FCA CONC 5.2A / MCOB 11 (affordability),FCA,Sample Testing Output,LOS; decision engine,Quarterly,Underwriting Manager
Lending Origination & Underwriting,LEN,5,Credit Risk Grading / Scoring / PD Assessment,LEN-R05,"Failure to grade credit risk / assign PD accurately could result in mispriced risk, capital misstatement and IRB-model non-compliance",LEN-05,"Scoring/PD models assign grades within an approved, validated methodology and rating scale; overrides are governed and monitored; model use aligns with PRA permissions",Preventive,External,Semi-automated,PRA Rulebook credit risk / onshored CRR,PRA,Sample Testing Output,Credit risk / rating system,Quarterly,Credit Risk Modelling Manager
Lending Origination & Underwriting,LEN,6,Collateral & Valuation,LEN-R06,"Failure to value and control collateral could result in inflated security values, capital error and loss on default",LEN-06,Collateral is valued by approved methods/valuers within policy; revaluation triggers are applied; LTV and eligibility are validated before sanction,Preventive,External,Semi-automated,FCA MCOB (mortgages),FCA,Third-Party Certificate/Attestation,LOS; valuation / collateral system,Quarterly,Collateral & Valuations Manager
Lending Origination & Underwriting,LEN,7,Manual Underwriting & Exception Handling,LEN-R07,Failure to control manual underwriting and policy exceptions could result in out-of-appetite lending and inconsistent decisions,LEN-07,Manual/exception decisions require justification within delegated authority and are quality-assured; exception volumes and performance are monitored,Detective,Internal,Manual,FCA CONC/MCOB,FCA,Sign-off/Attestation Memo,LOS; exception log,Quarterly,Underwriting Manager
Lending Origination & Underwriting,LEN,8,"Credit Decision, Sanction & Approval",LEN-R08,Failure to approve credit within delegated authority could result in unauthorised exposure and breach of risk appetite,LEN-08,Credit decisions are sanctioned within a delegated-authority matrix; large/complex exposures route to credit committee; approvals are logged and immutable,Preventive,Internal,Semi-automated,Internal credit-approval authority,PRA,Sign-off/Attestation Memo,LOS; credit committee records,Quarterly,Head of Credit / Credit Committee Chair
Lending Origination & Underwriting,LEN,9,"Offer, Documentation & Terms / Disclosure",LEN-R09,Failure to issue compliant agreements and pre-contract disclosure could result in unenforceable agreements and a CCA/CONC breach,LEN-09,"Offer/agreement documents are generated from approved, version-controlled templates with mandated pre-contract disclosures; issuance is controlled and sampled",Preventive,External,Semi-automated,Consumer Credit Act 1974 (regulated agreements),UK Parliament,Policy Document + Version History,LOS; document generation,Annual,Lending Documentation Manager
Lending Origination & Underwriting,LEN,10,Conditions & Pre-Drawdown Checks,LEN-R10,Failure to satisfy conditions precedent before drawdown could result in releasing funds without required protections,LEN-10,"Pre-drawdown checklist confirms conditions precedent (valuation, legal, AML, insurance) are met before funds release; overrides require senior approval",Preventive,Internal,Semi-automated,Internal credit policy,FCA,Sample Testing Output,LOS; conditions checklist,Quarterly,Loan Operations Manager
Lending Origination & Underwriting,LEN,11,"Booking, Drawdown & Disbursement",LEN-R11,"Failure to book and disburse correctly could result in misstatement, mispayment and reconciliation breaks",LEN-11,Drawdown is executed against the sanctioned terms with segregation of duties; booking is reconciled to the sanction and to the disbursement payment,Detective,Internal,Semi-automated,Internal controls over financial reporting,FCA,Reconciliation Statement,Core banking; LOS; payment system,Monthly,Loan Operations Manager
Lending Origination & Underwriting,LEN,12,Post-Completion QA & File Review,LEN-R12,Failure to QA completed lending files could result in undetected control failures and systemic mis-lending,LEN-12,A risk-based sample of completed files is QA-reviewed against policy and regulatory requirements; findings drive remediation and process fixes,Detective,Internal,Manual,FCA CONC/MCOB,FCA,Sample Testing Output,LOS; QA workflow,Quarterly,Lending Quality Assurance Manager
Collections & Recoveries,COL,1,Arrears Identification & Early Warning,COL-R01,Failure to identify arrears and early-warning signals promptly could result in escalating customer harm and CONC/MCOB breach,COL-01,"Systematic arrears identification flags missed payments and early-warning indicators for timely, proportionate contact; coverage is reconciled to the book",Detective,External,Automated,FCA CONC 7 (arrears),FCA,Exception Report,Collections system; core banking,Monthly,Collections Operations Manager
Collections & Recoveries,COL,2,Customer Contact & Early Intervention,COL-R02,"Failure to make fair, timely contact could result in avoidable defaults and unfair treatment of customers in difficulty",COL-02,"Contact strategy applies compliant, proportionate outreach with affordability-based options; calls are quality-assured for fairness and forbearance signposting",Detective,External,Semi-automated,FCA CONC 7 / MCOB 13,FCA,Sample Testing Output,Collections system; telephony / QA,Monthly,Collections Team Leader
Collections & Recoveries,COL,3,Vulnerability & Circumstance / Financial Difficulty Assessment,COL-R03,Failure to assess vulnerability and financial difficulty could result in inappropriate collections action and foreseeable harm,COL-03,A structured financial-difficulty and vulnerability assessment informs forbearance; vulnerability is flagged and drives tailored handling; assessments are sampled,Preventive,External,Semi-automated,FCA CONC 7 / MCOB 13,FCA,Sample Testing Output,Collections system; CRM vulnerability flags,Quarterly,Financial Difficulty / Vulnerability Lead
Collections & Recoveries,COL,4,Forbearance Option Selection / Decision,COL-R04,Failure to offer appropriate forbearance could result in unsustainable arrangements and a CONC/MCOB forbearance breach,COL-04,Forbearance options are selected against documented criteria and affordability; decisions are recorded with rationale and reviewed for suitability,Preventive,External,Semi-automated,FCA CONC 7 / MCOB 13 (forbearance),FCA,Sign-off/Attestation Memo,Collections system,Quarterly,Collections Underwriting Manager
Collections & Recoveries,COL,5,"Arrangement Setup, Monitoring & Review",COL-R05,"Failure to set up and monitor arrangements could result in failed plans, re-default and understated impairment",COL-05,Arrangements are set with correct terms and monitored for adherence; breaks trigger re-assessment; arrangement performance is reported,Detective,External,Semi-automated,FCA CONC 7 / MCOB 13,FCA,Exception Report,Collections system,Monthly,Collections Operations Manager
Collections & Recoveries,COL,6,"Default, Termination, Litigation & Repossession",COL-R06,Failure to follow default/possession procedure could result in unlawful repossession and unenforceable action,COL-06,Default notices and possession action follow statutory/pre-action requirements as a last resort with sign-off; litigation steps are checklist-controlled and logged,Preventive,External,Manual,CCA 1974 (default notices),UK Parliament,Sign-off/Attestation Memo,Collections/recoveries system; legal case system,Quarterly,Recoveries & Litigation Manager
Collections & Recoveries,COL,7,"Write-Off, Charge-Off & Debt Sale",COL-R07,Failure to control write-off and charge-off could result in accounting misstatement and premature loss of recovery,COL-07,Write-off/charge-off follows approved criteria with authorisation and accounting sign-off; amounts are reconciled to the ledger and impairment,Detective,Internal,Semi-automated,Internal financial controls,FCA,Reconciliation Statement,Collections system; general ledger,Monthly,Credit Risk / Finance Controller
Collections & Recoveries,COL,8,Debt Sale / External Agency Placement,COL-R08,Failure to oversee debt purchasers/DCAs could result in customer harm by third parties and reputational/regulatory exposure,COL-08,"Debt sale/placement uses due-diligenced, contractually-bound partners with fair-treatment clauses; DCA performance and complaints are monitored",Detective,External,Semi-automated,FCA CONC 7 (fair debt sale/agency oversight),FCA,Third-Party Certificate/Attestation,Recoveries system; vendor management,Quarterly,Debt Sale / Agency Oversight Manager
Collections & Recoveries,COL,9,Impairment / Provisioning Interface (IFRS 9),COL-R09,Failure to feed arrears/forbearance data into IFRS 9 ECL could result in understated impairment and misstated accounts,COL-09,Stage allocation and ECL inputs are driven by arrears/forbearance status per the IFRS 9 model; the interface is reconciled and governed with documented assumptions,Detective,External,Semi-automated,IFRS 9 (ECL),UKEB/IASB,Reconciliation Statement,Collections system; ECL / impairment engine,Quarterly,Impairment / Credit Risk Manager
Collections & Recoveries,COL,10,Post-Write-Off Recoveries & Recovery Accounting,COL-R10,Failure to account for post-write-off recoveries correctly could result in misstated recoveries and lost income,COL-10,"Recoveries are captured, allocated and reconciled to written-off balances; recovery accounting is controlled and sampled",Detective,Internal,Semi-automated,Internal financial controls,Firm,Reconciliation Statement,Recoveries system; general ledger,Monthly,Recoveries Accounting Manager
Collections & Recoveries,COL,11,Post-Forbearance Monitoring,COL-R11,Failure to monitor post-forbearance performance could result in undetected re-default and unsustainable arrangements,COL-11,Post-forbearance accounts are monitored for sustainability and re-default; adverse trends trigger re-assessment and are reported,Detective,External,Semi-automated,FCA CONC 7 / MCOB 13,FCA,Exception Report,Collections system,Quarterly,Collections Operations Manager
Collections & Recoveries,COL,12,Complaint Linkage & Arrears Conduct MI / Governance,COL-R12,Failure to link arrears complaints and produce conduct MI could result in systemic unfair-treatment issues going undetected,COL-12,Arrears complaints are linked to cases and aggregated into conduct MI; themes are governed and escalated with action tracking,Detective,Internal,Semi-automated,FCA DISP (interface),FCA,Board/Committee Minute Extract,Complaints system; collections MI,Quarterly,Collections Conduct / MI Manager
Payments & Transaction Processing,PAY,1,Payment Channel / Product Configuration,PAY-R01,Failure to configure payment channels and products to scheme and PSR rules could result in mis-routed or non-compliant payments and scheme fines,PAY-01,Channel/product configuration is set from approved scheme parameters with maker-checker sign-off and reconciled to scheme onboarding records before go-live,Preventive,Internal,Semi-automated,Payment Services Regs 2017 (PSRs),HM Treasury,Screenshot/Configuration Extract,Payment hub; channel platform; scheme gateway,Quarterly,Payments Product Operations Manager
Payments & Transaction Processing,PAY,2,"Payment Initiation, Capture & Validation",PAY-R02,"Failure to capture and validate payment instructions completely could result in rejected, delayed or erroneous payments and PSR execution breaches",PAY-02,"Payment engine applies format, mandatory-field and limit validation at capture; invalid instructions are auto-rejected or routed to repair",Preventive,External,Automated,PSRs 2017 (execution/information),FCA,Exception Report,Payment gateway/hub; digital channels; card processor,Monthly,Payment Operations Manager
Payments & Transaction Processing,PAY,3,Authentication & Fraud/Sanctions Screening (SCA),PAY-R03,Failure to apply strong customer authentication and real-time sanctions screening could result in unauthorised payments and sanctioned-party settlement,PAY-03,SCA is enforced per RTS with exemption logic; every payment is screened real-time against sanctions lists; hits are held pending disposition,Preventive,External,Automated,PSRs 2017 reg 100 (SCA),FCA,System Log/Export,SCA; screening filter; fraud engine,Continuous,Payment Fraud & Screening Manager
Payments & Transaction Processing,PAY,4,Validation & Confirmation of Payee,PAY-R04,Failure to perform Confirmation of Payee could result in misdirected payments and increased APP fraud losses,PAY-04,CoP name-matching runs before payment setup/execution; mismatches present a warning and are logged; downgrade/opt-out cases are recorded,Preventive,External,Automated,Pay.UK CoP rules,Pay.UK,System Log/Export,Payment engine; CoP,Monthly,Payments Product Operations Manager
Payments & Transaction Processing,PAY,5,"Payment Processing, Scheme Routing & Clearing",PAY-R05,"Failure to route and clear payments per scheme rules could result in settlement failure, scheme sanctions and customer detriment",PAY-05,Routing/clearing engine applies scheme rules and cut-offs; scheme acknowledgements are reconciled and unmatched items are investigated to SLA,Detective,External,Automated,Pay.UK scheme rules (Bacs/FPS),Pay.UK,Reconciliation Statement,Scheme gateways; payment hub; SWIFT gateway,Monthly,Payment Operations Manager
Payments & Transaction Processing,PAY,6,Clearing & Settlement,PAY-R06,"Failure to settle to nostro/RTGS accurately and on time could result in liquidity mismanagement, overdrawn nostros and settlement risk",PAY-06,Settlement positions are reconciled to RTGS/nostro and the GL daily; breaks and funding shortfalls are escalated and cleared within cut-off,Detective,External,Semi-automated,BoE RTGS/CHAPS rules,Bank of England,Reconciliation Statement,Settlement; nostro; RTGS; core banking,Monthly,Settlements Manager
Payments & Transaction Processing,PAY,7,"Exception, Repair & Returns Handling",PAY-R07,Failure to repair and return failed payments within scheme timescales could result in scheme breaches and customer loss,PAY-07,Repair/returns queue enforces scheme return-reason codes and timescale SLAs; ageing items escalate; root causes feed back to prevention,Corrective,External,Semi-automated,Scheme rulebooks (returns/timescales),Pay.UK,Exception Report,Payment operations / investigations; repair queue,Monthly,Payment Investigations Manager
Payments & Transaction Processing,PAY,8,Reconciliation (nostro / suspense / scheme),PAY-R08,"Failure to reconcile nostro, suspense and scheme accounts could result in undetected loss, fraud or misstatement",PAY-08,"Automated matching reconciles nostro/suspense/scheme accounts; unmatched and aged items breach thresholds, are investigated and cleared with sign-off",Detective,Internal,Automated,Firm reconciliation policy,Internal,Reconciliation Statement,Reconciliation tool; GL; payment hub; nostro system,Monthly,Reconciliations Manager
Payments & Transaction Processing,PAY,9,Customer Dispute / Recall / Chargeback,PAY-R09,"Failure to process disputes, recalls and chargebacks within scheme/PSR timescales could result in customer detriment and lost recovery rights",PAY-09,Dispute system enforces scheme reason codes and time-bar deadlines; cases route to the correct scheme process; outcomes and refunds are tracked to SLA,Corrective,External,Semi-automated,Card scheme chargeback rules,Card schemes,Exception Report,Dispute management system; scheme portal; CRM,Monthly,Disputes & Chargebacks Manager
Payments & Transaction Processing,PAY,10,Card Issuing & Acquiring / Scheme Operations,PAY-R10,Failure to operate card issuing/acquiring to scheme and PCI rules could result in scheme non-compliance fines and cardholder-data compromise,PAY-10,Card management operations are run to scheme mandates with PCI-DSS controls; scheme compliance and PCI attestation (AoC) are maintained and evidenced,Preventive,External,Semi-automated,Card scheme rules (Visa/Mastercard),Card schemes,Third-Party Certificate/Attestation,Card management system,Annual,Card Operations Manager
Payments & Transaction Processing,PAY,11,Cash & ATM / Branch Operations,PAY-R11,"Failure to control cash/ATM operations could result in cash differences, loss and access-to-cash failings",PAY-11,Cash and ATM/teller balances are reconciled daily under dual control; differences are investigated and cleared; access-to-cash coverage is monitored,Detective,Internal,Semi-automated,BCOBS,FCA,Reconciliation Statement,Cash management; ATM switch; branch teller system,Monthly,Cash Operations Manager
Payments & Transaction Processing,PAY,12,E-Money / Client Safeguarding & Segregation,PAY-R12,Failure to safeguard and segregate relevant funds could result in shortfall and customer loss on firm failure,PAY-12,Safeguarded funds are reconciled daily to the safeguarding account/ledger; any shortfall is topped up same-day and breaches escalated to the safeguarding owner,Preventive,External,Semi-automated,Electronic Money Regs 2011,FCA,Reconciliation Statement,Safeguarding reconciliation ledger; GL; client money reconciliation tool,Monthly,Safeguarding / Client Money Manager
Payments & Transaction Processing,PAY,13,REP027 Safeguarding Data Aggregation & Submission,PAY-R13,Failure to aggregate and submit accurate safeguarding data (REP027) could result in a regulatory reporting breach and supervisory intervention,PAY-13,"REP027 is compiled from the safeguarding reconciliation, validated and signed off before RegData submission by the deadline; a submission archive is retained",Detective,External,Semi-automated,FCA safeguarding return REP027 (SUP 16),FCA,Regulatory Filing Copy,FCA RegData / regulatory engine,Monthly,Safeguarding Reporting Manager
Payments & Transaction Processing,PAY,14,Payment MI & Regulatory/Scheme Reporting,PAY-R14,Failure to produce accurate payment MI and scheme/regulatory returns could result in reporting breaches and undetected control failure,PAY-14,"Payment MI and scheme/regulatory returns are generated from reconciled data, reviewed against thresholds and signed off before submission",Detective,Internal,Semi-automated,PSRs 2017,FCA,Regulatory Filing Copy,Reporting tools; RegData; payments BI dashboard; scheme portals,Quarterly,Payments MI & Reporting Manager`;
