/**
 * UK Banking RiskTrace prototype — deterministic mock graph for demos.
 * Shape matches `components/UKBankingAudit` UI contracts.
 */

const spark = (base: number, n = 13) =>
  Array.from({ length: n }, (_, i) => Math.max(0, Math.min(100, Math.round(base + (i - n / 2) * 2 + (i % 3) * 3))));

const mockControlTraceData = {
  personas: [
    { id: 'cro', label: 'CRO', defaultScreen: 'riskPosture', smfId: 'SMF4-JAMES-CLARKE' },
    { id: 'smf16', label: 'SMF16', defaultScreen: 'controlUniverse', smfId: 'SMF16-ALEX-MORGAN' },
    { id: 'doer', label: '2LoD Compliance', defaultScreen: 'complianceWorkspace', smfId: null },
    { id: 'auditor', label: 'Internal Audit', defaultScreen: 'complianceWorkspace', smfId: null },
  ],
  navigationItems: [
    { id: 'nav-rp', label: 'Risk Posture', screen: 'riskPosture', visibleForPersonas: ['cro', 'smf16'] },
    { id: 'nav-cu', label: 'Control Universe', screen: 'controlUniverse', visibleForPersonas: ['cro', 'smf16', 'doer', 'auditor'] },
    { id: 'nav-cw', label: 'Compliance Workspace', screen: 'complianceWorkspace', visibleForPersonas: ['doer', 'auditor'] },
    { id: 'nav-pt', label: 'Population Testing', screen: 'populationTesting', visibleForPersonas: ['doer', 'auditor'] },
    { id: 'nav-sm', label: 'SMCR · Reasonable Steps', screen: 'smcrWorkspace', visibleForPersonas: ['cro', 'smf16'] },
    { id: 'nav-ap', label: 'Audit Pack Builder', screen: 'auditPackBuilder', visibleForPersonas: ['doer', 'auditor'] },
    { id: 'nav-ai', label: 'AI Insights', screen: 'aiInsights', visibleForPersonas: ['cro', 'smf16', 'doer', 'auditor'] },
  ],
  riskDomains: [
    { id: 'dom-fcc', label: 'FCC / AML', res: 72, resBand: 'amber' as const, trend: 'worsening' as const, resSparklineSeries: spark(72), primaryDriverRiskId: 'R-UK-AML-001' },
    { id: 'dom-cyber', label: 'Cyber', res: 41, resBand: 'green' as const, trend: 'stable' as const, resSparklineSeries: spark(41), primaryDriverRiskId: 'R-UK-CYB-001' },
    { id: 'dom-credit', label: 'Credit', res: 58, resBand: 'amber' as const, trend: 'stable' as const, resSparklineSeries: spark(58), primaryDriverRiskId: 'R-UK-CRD-001' },
    { id: 'dom-model', label: 'Model', res: 64, resBand: 'amber' as const, trend: 'improving' as const, resSparklineSeries: spark(64), primaryDriverRiskId: 'R-UK-MRM-001' },
    { id: 'dom-conduct', label: 'Conduct', res: 38, resBand: 'green' as const, trend: 'improving' as const, resSparklineSeries: spark(38), primaryDriverRiskId: 'R-UK-CND-001' },
    { id: 'dom-oper', label: 'Operational', res: 55, resBand: 'amber' as const, trend: 'stable' as const, resSparklineSeries: spark(55), primaryDriverRiskId: 'R-UK-OPS-001' },
    { id: 'dom-liquidity', label: 'Liquidity', res: 33, resBand: 'green' as const, trend: 'stable' as const, resSparklineSeries: spark(33), primaryDriverRiskId: 'R-UK-LIQ-001' },
    { id: 'dom-third', label: 'Third parties', res: 61, resBand: 'amber' as const, trend: 'worsening' as const, resSparklineSeries: spark(61), primaryDriverRiskId: 'R-UK-TPR-001' },
  ],
  risks: [
    {
      id: 'R-UK-AML-001',
      title: 'AML transaction monitoring effectiveness',
      description: 'Residual risk that TM coverage, tuning, and disposition quality do not keep pace with typologies and regulatory expectations.',
      domain: 'financial_crime',
      inherentRating: 'high',
      residualRating: 'high',
      residualScore: 78,
      trend: 'worsening' as const,
      resDecomposition: { inherent: 'high', controls: 'amber', incidents: 'red', appetite: 'amber', forward: 72 },
      accountableSMFId: 'SMF17-PRIYA-PATEL',
      linkedControlIds: ['CTRL-UK-AML-002', 'CTRL-UK-AML-001', 'CTRL-UK-AML-003'],
      linkedObligationIds: ['OBL-UK-MLR-83', 'OBL-UK-FSMA-SYSC'],
    },
    {
      id: 'R-UK-CYB-001',
      title: 'Cyber intrusion & resilience',
      description: 'Risk of successful attack or service disruption breaching operational resilience expectations.',
      domain: 'cyber',
      inherentRating: 'high',
      residualRating: 'medium',
      residualScore: 41,
      trend: 'stable' as const,
      resDecomposition: { inherent: 'high', controls: 'green', incidents: 'green', appetite: 'green', forward: 40 },
      accountableSMFId: 'SMF4-JAMES-CLARKE',
      linkedControlIds: ['CTRL-UK-CYB-001'],
      linkedObligationIds: ['OBL-UK-PS21-2'],
    },
    {
      id: 'R-UK-CRD-001',
      title: 'Wholesale credit deterioration',
      description: 'Risk of undetected deterioration in higher-risk wholesale exposures.',
      domain: 'credit',
      inherentRating: 'medium',
      residualRating: 'medium',
      residualScore: 58,
      trend: 'stable' as const,
      resDecomposition: { inherent: 'medium', controls: 'amber', incidents: 'amber', appetite: 'green', forward: 55 },
      accountableSMFId: 'SMF16-ALEX-MORGAN',
      linkedControlIds: ['CTRL-UK-CRD-001'],
      linkedObligationIds: ['OBL-UK-CRR'],
    },
    {
      id: 'R-UK-MRM-001',
      title: 'Model risk governance',
      description: 'Risk that material models are not inventoried, validated, and governed to PRA SS2/13 expectations.',
      domain: 'model',
      inherentRating: 'high',
      residualRating: 'medium',
      residualScore: 64,
      trend: 'improving' as const,
      resDecomposition: { inherent: 'high', controls: 'amber', incidents: 'amber', appetite: 'amber', forward: 62 },
      accountableSMFId: 'SMF16-ALEX-MORGAN',
      linkedControlIds: ['CTRL-UK-MRM-001'],
      linkedObligationIds: ['OBL-UK-SS213'],
    },
    {
      id: 'R-UK-CND-001',
      title: 'Consumer Duty outcomes',
      description: 'Risk that product and service outcomes fall short of Consumer Duty cross-cutting rules.',
      domain: 'conduct',
      inherentRating: 'medium',
      residualRating: 'low',
      residualScore: 38,
      trend: 'improving' as const,
      resDecomposition: { inherent: 'medium', controls: 'green', incidents: 'green', appetite: 'green', forward: 36 },
      accountableSMFId: 'SMF4-JAMES-CLARKE',
      linkedControlIds: ['CTRL-UK-CD-001'],
      linkedObligationIds: ['OBL-UK-CD-OUT'],
    },
    {
      id: 'R-UK-OPS-001',
      title: 'Payment & settlement operational failure',
      description: 'Risk of major operational incident in critical payment services.',
      domain: 'operational',
      inherentRating: 'high',
      residualRating: 'medium',
      residualScore: 55,
      trend: 'stable' as const,
      resDecomposition: { inherent: 'high', controls: 'amber', incidents: 'amber', appetite: 'green', forward: 54 },
      accountableSMFId: 'SMF16-ALEX-MORGAN',
      linkedControlIds: ['CTRL-UK-OPS-001'],
      linkedObligationIds: ['OBL-UK-PS21-2'],
    },
    {
      id: 'R-UK-LIQ-001',
      title: 'Liquidity stress',
      description: 'Risk of inadequate liquidity buffers under combined idiosyncratic and market stress.',
      domain: 'liquidity',
      inherentRating: 'medium',
      residualRating: 'low',
      residualScore: 33,
      trend: 'stable' as const,
      resDecomposition: { inherent: 'medium', controls: 'green', incidents: 'green', appetite: 'green', forward: 32 },
      accountableSMFId: 'SMF4-JAMES-CLARKE',
      linkedControlIds: ['CTRL-UK-LIQ-001'],
      linkedObligationIds: ['OBL-UK-LIQ-REG'],
    },
    {
      id: 'R-UK-TPR-001',
      title: 'Third-party concentration & resilience',
      description: 'Risk that critical outsourced services lack adequate oversight and exit planning.',
      domain: 'third_party',
      inherentRating: 'medium',
      residualRating: 'medium',
      residualScore: 61,
      trend: 'worsening' as const,
      resDecomposition: { inherent: 'medium', controls: 'amber', incidents: 'amber', appetite: 'amber', forward: 60 },
      accountableSMFId: 'SMF16-ALEX-MORGAN',
      linkedControlIds: ['CTRL-UK-TPR-001'],
      linkedObligationIds: ['OBL-UK-SS2-21'],
    },
  ],
  controls: [
    {
      id: 'CTRL-UK-AML-002',
      title: 'TM alert disposition within SLA with quality sampling',
      description: 'End-to-end control from alert generation through disposition with independent QA sampling.',
      controlType: 'preventive',
      controlNature: 'automated_with_manual',
      frequency: 'continuous',
      threeDim: {
        operating: { current: 78, band: 'amber' as const, trend: 'worsening' as const, series: spark(78) },
        catch: { current: 71, band: 'amber' as const, trend: 'stable' as const, series: spark(71) },
        evidence: { current: 62, band: 'amber' as const, trend: 'worsening' as const, series: spark(62) },
      },
      ces: { current: 71, band: 'amber' as const, trend: 'worsening' as const, delta13w: -4 },
      linkedRiskIds: ['R-UK-AML-001'],
      linkedObligationIds: ['OBL-UK-MLR-83', 'OBL-UK-FSMA-SYSC'],
      recentInstanceIds: ['CI-AML-9001', 'CI-AML-9002', 'CI-AML-9003'],
      judgementDependence: 'none',
      observedVariantDriftFlag: true,
      observedVariantNote: 'Observed run path includes manual override queue not reflected in documented variant.',
      documentedVariantSignature: 'VAR-TM-UK-2025-Q4',
    },
    {
      id: 'CTRL-UK-AML-001',
      title: 'Customer screening at onboarding & refresh',
      description: 'Sanctions and PEP screening with periodic refresh triggers.',
      controlType: 'preventive',
      controlNature: 'hybrid',
      frequency: 'daily',
      threeDim: {
        operating: { current: 88, band: 'green' as const, trend: 'stable' as const, series: spark(88) },
        catch: { current: 82, band: 'green' as const, trend: 'improving' as const, series: spark(82) },
        evidence: { current: 79, band: 'amber' as const, trend: 'stable' as const, series: spark(79) },
      },
      ces: { current: 84, band: 'green' as const, trend: 'stable' as const, delta13w: 1 },
      linkedRiskIds: ['R-UK-AML-001'],
      linkedObligationIds: ['OBL-UK-MLR-83'],
      recentInstanceIds: ['CI-AML-8001'],
      judgementDependence: 'partial',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-SCR-UK-2025',
    },
    {
      id: 'CTRL-UK-AML-003',
      title: 'SAR quality committee review',
      description: '2LoD review of SAR narratives prior to filing.',
      controlType: 'detective',
      controlNature: 'manual',
      frequency: 'weekly',
      threeDim: {
        operating: { current: 65, band: 'amber' as const, trend: 'stable' as const, series: spark(65) },
        catch: { current: 70, band: 'amber' as const, trend: 'stable' as const, series: spark(70) },
        evidence: { current: 58, band: 'amber' as const, trend: 'worsening' as const, series: spark(58) },
      },
      ces: { current: 66, band: 'amber' as const, trend: 'stable' as const, delta13w: 0 },
      linkedRiskIds: ['R-UK-AML-001'],
      linkedObligationIds: ['OBL-UK-MLR-83'],
      recentInstanceIds: [],
      judgementDependence: 'full',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-SAR-UK-2025',
    },
    {
      id: 'CTRL-UK-CYB-001',
      title: 'Privileged access reviews',
      description: 'Quarterly review of privileged accounts against SoD policy.',
      controlType: 'detective',
      controlNature: 'manual',
      frequency: 'quarterly',
      threeDim: {
        operating: { current: 92, band: 'green' as const, trend: 'stable' as const, series: spark(92) },
        catch: { current: 85, band: 'green' as const, trend: 'stable' as const, series: spark(85) },
        evidence: { current: 90, band: 'green' as const, trend: 'improving' as const, series: spark(90) },
      },
      ces: { current: 89, band: 'green' as const, trend: 'improving' as const, delta13w: 3 },
      linkedRiskIds: ['R-UK-CYB-001'],
      linkedObligationIds: ['OBL-UK-PS21-2'],
      recentInstanceIds: ['CI-CYB-1001'],
      judgementDependence: 'partial',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-PAM-UK-2025',
    },
    {
      id: 'CTRL-UK-CRD-001',
      title: 'Watchlist & early warning indicators',
      description: 'Monitoring of covenant and macro early warnings for wholesale book.',
      controlType: 'detective',
      controlNature: 'hybrid',
      frequency: 'monthly',
      threeDim: {
        operating: { current: 74, band: 'amber' as const, trend: 'stable' as const, series: spark(74) },
        catch: { current: 68, band: 'amber' as const, trend: 'stable' as const, series: spark(68) },
        evidence: { current: 72, band: 'amber' as const, trend: 'stable' as const, series: spark(72) },
      },
      ces: { current: 71, band: 'amber' as const, trend: 'stable' as const, delta13w: -1 },
      linkedRiskIds: ['R-UK-CRD-001'],
      linkedObligationIds: ['OBL-UK-CRR'],
      recentInstanceIds: [],
      judgementDependence: 'partial',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-CRD-UK-2025',
    },
    {
      id: 'CTRL-UK-MRM-001',
      title: 'Material model validation cycle',
      description: 'Annual independent validation for Tier 1 models.',
      controlType: 'preventive',
      controlNature: 'manual',
      frequency: 'annual',
      threeDim: {
        operating: { current: 70, band: 'amber' as const, trend: 'improving' as const, series: spark(70) },
        catch: { current: 66, band: 'amber' as const, trend: 'improving' as const, series: spark(66) },
        evidence: { current: 75, band: 'amber' as const, trend: 'improving' as const, series: spark(75) },
      },
      ces: { current: 70, band: 'amber' as const, trend: 'improving' as const, delta13w: 5 },
      linkedRiskIds: ['R-UK-MRM-001'],
      linkedObligationIds: ['OBL-UK-SS213'],
      recentInstanceIds: [],
      judgementDependence: 'full',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-MRM-UK-2025',
    },
    {
      id: 'CTRL-UK-CD-001',
      title: 'Consumer Duty outcomes testing',
      description: 'Annual assessment of outcomes vs price & value, consumer understanding, support.',
      controlType: 'detective',
      controlNature: 'manual',
      frequency: 'annual',
      threeDim: {
        operating: { current: 81, band: 'green' as const, trend: 'improving' as const, series: spark(81) },
        catch: { current: 76, band: 'amber' as const, trend: 'improving' as const, series: spark(76) },
        evidence: { current: 84, band: 'green' as const, trend: 'improving' as const, series: spark(84) },
      },
      ces: { current: 80, band: 'green' as const, trend: 'improving' as const, delta13w: 6 },
      linkedRiskIds: ['R-UK-CND-001'],
      linkedObligationIds: ['OBL-UK-CD-OUT'],
      recentInstanceIds: [],
      judgementDependence: 'full',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-CD-UK-2025',
    },
    {
      id: 'CTRL-UK-OPS-001',
      title: 'CHAPS dual control & maker-checker',
      description: 'Four-eyes on high-value outbound payments.',
      controlType: 'preventive',
      controlNature: 'automated',
      frequency: 'continuous',
      threeDim: {
        operating: { current: 94, band: 'green' as const, trend: 'stable' as const, series: spark(94) },
        catch: { current: 88, band: 'green' as const, trend: 'stable' as const, series: spark(88) },
        evidence: { current: 86, band: 'green' as const, trend: 'stable' as const, series: spark(86) },
      },
      ces: { current: 90, band: 'green' as const, trend: 'stable' as const, delta13w: 1 },
      linkedRiskIds: ['R-UK-OPS-001'],
      linkedObligationIds: ['OBL-UK-PS21-2'],
      recentInstanceIds: [],
      judgementDependence: 'none',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-PAY-UK-2025',
    },
    {
      id: 'CTRL-UK-LIQ-001',
      title: 'Liquidity stress testing & ILAAP linkage',
      description: 'Internal stress suite feeding ILAAP narrative.',
      controlType: 'detective',
      controlNature: 'hybrid',
      frequency: 'monthly',
      threeDim: {
        operating: { current: 87, band: 'green' as const, trend: 'stable' as const, series: spark(87) },
        catch: { current: 80, band: 'green' as const, trend: 'stable' as const, series: spark(80) },
        evidence: { current: 83, band: 'green' as const, trend: 'stable' as const, series: spark(83) },
      },
      ces: { current: 84, band: 'green' as const, trend: 'stable' as const, delta13w: 2 },
      linkedRiskIds: ['R-UK-LIQ-001'],
      linkedObligationIds: ['OBL-UK-LIQ-REG'],
      recentInstanceIds: [],
      judgementDependence: 'partial',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-LIQ-UK-2025',
    },
    {
      id: 'CTRL-UK-TPR-001',
      title: 'Critical third-party due diligence & exit',
      description: 'Onboarding and annual review of critical suppliers with exit plans.',
      controlType: 'preventive',
      controlNature: 'manual',
      frequency: 'annual',
      threeDim: {
        operating: { current: 68, band: 'amber' as const, trend: 'worsening' as const, series: spark(68) },
        catch: { current: 62, band: 'amber' as const, trend: 'worsening' as const, series: spark(62) },
        evidence: { current: 64, band: 'amber' as const, trend: 'stable' as const, series: spark(64) },
      },
      ces: { current: 65, band: 'amber' as const, trend: 'worsening' as const, delta13w: -5 },
      linkedRiskIds: ['R-UK-TPR-001'],
      linkedObligationIds: ['OBL-UK-SS2-21'],
      recentInstanceIds: [],
      judgementDependence: 'partial',
      observedVariantDriftFlag: false,
      observedVariantNote: '',
      documentedVariantSignature: 'VAR-TPR-UK-2025',
    },
  ],
  obligations: [
    {
      id: 'OBL-UK-MLR-83',
      citationShort: 'MLR 2017 r.19',
      citation: 'MLR 2017 Regulation 19',
      regulator: 'FCA',
      sourceInstrumentTitle: 'Money Laundering Regulations 2017',
      requirementText: 'Ongoing monitoring of business relationships including scrutiny of transactions to ensure consistency with knowledge of the customer.',
      sourceUrl: 'https://www.legislation.gov.uk/uksi/2017/692/regulation/19',
      ocs: {
        score: 72,
        band: 'amber' as const,
        coverageStatus: 'thinly_covered' as const,
        linkedControlsCount: 2,
        meanLinkedCES: 74,
        evidenceFreshnessDays: 12,
        evidenceCompleteness: 68,
      },
      linkedControlIds: ['CTRL-UK-AML-002', 'CTRL-UK-AML-001'],
      evidenceExpectation: ['Alert disposition log', 'QA sample sign-off', 'Population hash for reperformance'],
      regulatoryChangeHistory: [{ version: '1', effectiveFrom: '2017-06-26', summary: 'Initial MLR transposition' }],
      linkedPrescribedResponsibilities: ['PR-FC'],
      consumerDutyRelevant: false,
      smcrRelevant: true,
    },
    {
      id: 'OBL-UK-FSMA-SYSC',
      citationShort: 'SYSC 6.3',
      citation: 'FCA SYSC 6.3',
      regulator: 'FCA',
      sourceInstrumentTitle: 'Senior Management Arrangements, Systems and Controls',
      requirementText: 'A firm must establish, implement and maintain adequate policies and procedures sufficient to ensure compliance with its obligations under the regulatory system.',
      sourceUrl: 'https://www.handbook.fca.org.uk/handbook/SYSC/6/3.html',
      ocs: { score: 81, band: 'green' as const, coverageStatus: 'fully_covered' as const, linkedControlsCount: 3, meanLinkedCES: 79, evidenceFreshnessDays: 5, evidenceCompleteness: 82 },
      linkedControlIds: ['CTRL-UK-AML-002', 'CTRL-UK-AML-001', 'CTRL-UK-AML-003'],
      evidenceExpectation: ['Control design doc', 'Operating evidence', 'Issue linkage'],
      regulatoryChangeHistory: [],
      linkedPrescribedResponsibilities: ['PR-FC', 'PR-RISK'],
      consumerDutyRelevant: false,
      smcrRelevant: true,
    },
    {
      id: 'OBL-UK-PS21-2',
      citationShort: 'PS21/3 Ch.2',
      citation: 'PS21/3 Operational resilience',
      regulator: 'PRA/FCA',
      sourceInstrumentTitle: 'Building operational resilience',
      requirementText: 'Firms must identify their important business services, set impact tolerances, and demonstrate they can remain within them.',
      sourceUrl: 'https://www.bankofengland.co.uk/prudential-regulation/publication/2021/building-operational-resilience',
      ocs: { score: 76, band: 'amber' as const, coverageStatus: 'fully_covered' as const, linkedControlsCount: 3, meanLinkedCES: 84, evidenceFreshnessDays: 20, evidenceCompleteness: 71 },
      linkedControlIds: ['CTRL-UK-CYB-001', 'CTRL-UK-OPS-001'],
      evidenceExpectation: ['Mapping artefacts', 'Scenario test results', 'Self-assessment'],
      regulatoryChangeHistory: [{ version: '2', effectiveFrom: '2022-03-31', summary: 'IBS identification deadline' }],
      linkedPrescribedResponsibilities: ['PR-OPS'],
      consumerDutyRelevant: false,
      smcrRelevant: true,
    },
    {
      id: 'OBL-UK-CRR',
      citationShort: 'CRR Art.81',
      citation: 'CRR Article 81',
      regulator: 'PRA',
      sourceInstrumentTitle: 'Capital Requirements Regulation',
      requirementText: 'Large exposures monitoring and reporting.',
      sourceUrl: 'https://www.legislation.gov.uk/eur/2013/575/article/81',
      ocs: { score: 55, band: 'amber' as const, coverageStatus: 'uncovered' as const, linkedControlsCount: 1, meanLinkedCES: 71, evidenceFreshnessDays: 45, evidenceCompleteness: 48 },
      linkedControlIds: ['CTRL-UK-CRD-001'],
      evidenceExpectation: ['Exposure calculation evidence', 'Breaches register'],
      regulatoryChangeHistory: [],
      linkedPrescribedResponsibilities: ['PR-RISK'],
      consumerDutyRelevant: false,
      smcrRelevant: false,
    },
    {
      id: 'OBL-UK-SS213',
      citationShort: 'SS2/13',
      citation: 'PRA SS2/13',
      regulator: 'PRA',
      sourceInstrumentTitle: 'Model risk management',
      requirementText: 'Governance, identification, and control of model risk.',
      sourceUrl: 'https://www.bankofengland.co.uk/prudential-regulation/publication/2013/ss213-model-risk',
      ocs: { score: 70, band: 'amber' as const, coverageStatus: 'thinly_covered' as const, linkedControlsCount: 1, meanLinkedCES: 70, evidenceFreshnessDays: 8, evidenceCompleteness: 74 },
      linkedControlIds: ['CTRL-UK-MRM-001'],
      evidenceExpectation: ['Model inventory', 'Validation reports', 'Issues log'],
      regulatoryChangeHistory: [],
      linkedPrescribedResponsibilities: ['PR-RISK'],
      consumerDutyRelevant: false,
      smcrRelevant: false,
    },
    {
      id: 'OBL-UK-CD-OUT',
      citationShort: 'PRIN 2A',
      citation: 'FCA Consumer Duty',
      regulator: 'FCA',
      sourceInstrumentTitle: 'Consumer Duty rules',
      requirementText: 'Deliver good outcomes for retail customers across products and services.',
      sourceUrl: 'https://www.fca.org.uk/consumers/consumer-duty',
      ocs: { score: 80, band: 'green' as const, coverageStatus: 'fully_covered' as const, linkedControlsCount: 1, meanLinkedCES: 80, evidenceFreshnessDays: 6, evidenceCompleteness: 85 },
      linkedControlIds: ['CTRL-UK-CD-001'],
      evidenceExpectation: ['Outcomes metrics', 'Board attestation'],
      regulatoryChangeHistory: [],
      linkedPrescribedResponsibilities: ['PR-CONDUCT'],
      consumerDutyRelevant: true,
      smcrRelevant: true,
    },
    {
      id: 'OBL-UK-LIQ-REG',
      citationShort: 'Liquidity',
      citation: 'PRA liquidity expectations',
      regulator: 'PRA',
      sourceInstrumentTitle: 'Individual Liquidity Adequacy Standards',
      requirementText: 'Adequate liquidity risk management and stress testing.',
      sourceUrl: 'https://www.bankofengland.co.uk/prudential-regulation',
      ocs: { score: 84, band: 'green' as const, coverageStatus: 'fully_covered' as const, linkedControlsCount: 1, meanLinkedCES: 84, evidenceFreshnessDays: 4, evidenceCompleteness: 88 },
      linkedControlIds: ['CTRL-UK-LIQ-001'],
      evidenceExpectation: ['Stress results', 'ILAAP'],
      regulatoryChangeHistory: [],
      linkedPrescribedResponsibilities: ['PR-TREASURY'],
      consumerDutyRelevant: false,
      smcrRelevant: false,
    },
    {
      id: 'OBL-UK-SS2-21',
      citationShort: 'SS2/21',
      citation: 'PRA SS2/21',
      regulator: 'PRA',
      sourceInstrumentTitle: 'Outsourcing and third party risk management',
      requirementText: 'Management of material outsourcing arrangements.',
      sourceUrl: 'https://www.bankofengland.co.uk/prudential-regulation/publication/2021/march/outsourcing-and-third-party-risk-management-ss',
      ocs: { score: 65, band: 'amber' as const, coverageStatus: 'thinly_covered' as const, linkedControlsCount: 1, meanLinkedCES: 65, evidenceFreshnessDays: 30, evidenceCompleteness: 60 },
      linkedControlIds: ['CTRL-UK-TPR-001'],
      evidenceExpectation: ['Due diligence packs', 'Exit plans'],
      regulatoryChangeHistory: [],
      linkedPrescribedResponsibilities: ['PR-OPS'],
      consumerDutyRelevant: false,
      smcrRelevant: true,
    },
  ],
  processes: [{ id: 'PROC-TM-01', name: 'Transaction monitoring alert lifecycle' }],
  processSteps: [{ id: 'STEP-TM-DISP', name: 'Level-1 disposition' }],
  smfHolders: [
    {
      id: 'SMF4-JAMES-CLARKE',
      name: 'James Clarke',
      functionLabel: 'Chief Risk Officer',
      smfFunction: 'SMF4',
      prescribedResponsibilities: ['PR-RISK'],
      sorVersion: '2026.1',
      sorEffectiveFrom: '2026-01-15',
      managementResponsibilitiesMapRef: 'MRM-UK-2026-001',
      awaitingAcknowledgements: [
        { targetType: 'issue' as const, targetId: 'ISS-UK-AML-014', daysOpen: 18, raisedDate: '2026-03-10' },
      ],
      reasonableStepsTrail: [
        { timestamp: '2026-04-20T09:00:00Z', eventType: 'attestation', label: 'Quarterly risk attestation lodged', evidenceId: 'EV-UK-ATTEST-01' },
        { timestamp: '2026-04-01T11:30:00Z', eventType: 'committee', label: 'RCO signed escalation on TM backlog', evidenceId: 'EV-UK-MIN-RCO-04' },
      ],
      rss: {
        score: 74,
        band: 'amber' as const,
        components: {
          oversightCadenceEvidence: 80,
          escalationEvidence: 72,
          attestationFreshness: 78,
          issueAwareness: 68,
          decisionLogCompleteness: 70,
          mrmAlignment: 76,
          sorAlignment: 74,
        },
      },
      lastAttestationDate: '2026-04-18',
      nextAttestationDue: '2026-07-18',
      appointmentDate: '2022-03-01',
      conductRuleBreaches: 0,
      accountableProcessIds: ['PROC-TM-01'],
      accountableControlIds: ['CTRL-UK-AML-002', 'CTRL-UK-CYB-001'],
      accountableObligationIds: ['OBL-UK-FSMA-SYSC', 'OBL-UK-PS21-2'],
    },
    {
      id: 'SMF17-PRIYA-PATEL',
      name: 'Priya Patel',
      functionLabel: 'Head of Financial Crime Compliance',
      smfFunction: 'SMF17',
      prescribedResponsibilities: ['PR-FC'],
      sorVersion: '2026.1',
      sorEffectiveFrom: '2026-01-15',
      managementResponsibilitiesMapRef: 'MRM-UK-2026-002',
      awaitingAcknowledgements: [
        { targetType: 'issue' as const, targetId: 'ISS-UK-AML-014', daysOpen: 42, raisedDate: '2026-02-18' },
        { targetType: 'appetite_breach' as const, targetId: 'APP-UK-FC-01', daysOpen: 12, raisedDate: '2026-04-05' },
        { targetType: 'kri' as const, targetId: 'KRI-UK-FC-01', daysOpen: 5, raisedDate: '2026-04-22' },
      ],
      reasonableStepsTrail: [
        { timestamp: '2026-04-25T14:00:00Z', eventType: 'committee', label: 'FCC forum — TM tuning decisions', evidenceId: 'EV-UK-MIN-FCC-04' },
        { timestamp: '2026-04-10T16:20:00Z', eventType: 'review', label: 'Sampled QA outcomes for Q1', evidenceId: 'EV-UK-QA-01' },
      ],
      rss: {
        score: 66,
        band: 'amber' as const,
        components: {
          oversightCadenceEvidence: 70,
          escalationEvidence: 64,
          attestationFreshness: 72,
          issueAwareness: 58,
          decisionLogCompleteness: 62,
          mrmAlignment: 68,
          sorAlignment: 70,
        },
      },
      lastAttestationDate: '2026-04-12',
      nextAttestationDue: '2026-07-12',
      appointmentDate: '2021-06-01',
      conductRuleBreaches: 0,
      accountableProcessIds: ['PROC-TM-01'],
      accountableControlIds: ['CTRL-UK-AML-002', 'CTRL-UK-AML-001'],
      accountableObligationIds: ['OBL-UK-MLR-83', 'OBL-UK-FSMA-SYSC'],
    },
    {
      id: 'SMF16-ALEX-MORGAN',
      name: 'Alex Morgan',
      functionLabel: 'Head of Compliance',
      smfFunction: 'SMF16',
      prescribedResponsibilities: ['PR-COMPLIANCE'],
      sorVersion: '2026.1',
      sorEffectiveFrom: '2026-01-15',
      managementResponsibilitiesMapRef: 'MRM-UK-2026-003',
      awaitingAcknowledgements: [],
      reasonableStepsTrail: [
        { timestamp: '2026-04-19T10:00:00Z', eventType: 'review', label: 'Policy attestation cycle closed', evidenceId: null },
      ],
      rss: {
        score: 82,
        band: 'green' as const,
        components: {
          oversightCadenceEvidence: 85,
          escalationEvidence: 80,
          attestationFreshness: 84,
          issueAwareness: 78,
          decisionLogCompleteness: 82,
          mrmAlignment: 80,
          sorAlignment: 83,
        },
      },
      lastAttestationDate: '2026-04-19',
      nextAttestationDue: '2026-07-19',
      appointmentDate: '2020-09-15',
      conductRuleBreaches: 0,
      accountableProcessIds: [],
      accountableControlIds: ['CTRL-UK-CRD-001', 'CTRL-UK-MRM-001'],
      accountableObligationIds: ['OBL-UK-CRR', 'OBL-UK-SS213'],
    },
  ],
  actors: [
    { id: 'ACT-TESTER-01', name: 'Sam Taylor', role: 'Senior Compliance Tester' },
    { id: 'ACT-OWNER-01', name: 'Jordan Lee', role: 'Control Owner' },
  ],
  kris: [{ id: 'KRI-UK-FC-01', title: 'TM alert backlog age (p95)', name: 'TM backlog p95' }],
  riskAppetiteMetrics: [{ id: 'APP-UK-FC-01', metric: 'TM false negative rate proxy', name: 'Appetite breach · TM effectiveness' }],
  consumerOutcomes: [],
  importantBusinessServices: [],
  coverageGaps: [
    { id: 'GAP-01', gapType: 'evidence_completeness', ageDays: 9, entityId: 'CTRL-UK-AML-002', recommendedRemediation: 'Backfill population hash artefacts for March window.', severity: 'high' },
    { id: 'GAP-02', gapType: 'obligation_mapping', ageDays: 21, entityId: 'OBL-UK-CRR', recommendedRemediation: 'Add compensating control for large exposures sub-ledger.', severity: 'medium' },
    { id: 'GAP-03', gapType: 'smf_attestation', ageDays: 4, entityId: 'SMF17-PRIYA-PATEL', recommendedRemediation: 'Refresh SoR alignment evidence post re-org.', severity: 'low' },
  ],
  controlInstances: [
    {
      id: 'CI-AML-9001',
      caseOrTransactionId: 'TXN-8844221',
      controlId: 'CTRL-UK-AML-002',
      stepId: 'STEP-TM-DISP',
      operatorId: 'ACT-OWNER-01',
      outcome: 'fail',
      evidenceIds: [],
      evidenceCompletenessScore: 22,
      missingFields: ['disposition_code', 'supervisor_id'],
      expectedEvidenceStandardId: 'STD-EV-TM-UK-01',
    },
    {
      id: 'CI-AML-9002',
      caseOrTransactionId: 'TXN-8844302',
      controlId: 'CTRL-UK-AML-002',
      stepId: 'STEP-TM-DISP',
      operatorId: 'ACT-OWNER-01',
      outcome: 'fail',
      evidenceIds: ['EV-UK-PARTIAL-01'],
      evidenceCompletenessScore: 55,
      missingFields: ['narrative_attachment'],
      expectedEvidenceStandardId: 'STD-EV-TM-UK-01',
    },
    {
      id: 'CI-AML-9003',
      caseOrTransactionId: 'TXN-8844999',
      controlId: 'CTRL-UK-AML-002',
      stepId: 'STEP-TM-DISP',
      operatorId: 'ACT-OWNER-01',
      outcome: 'pass',
      evidenceIds: ['EV-UK-OK-01'],
      evidenceCompletenessScore: 92,
      missingFields: [],
      expectedEvidenceStandardId: 'STD-EV-TM-UK-01',
    },
    {
      id: 'CI-AML-8001',
      caseOrTransactionId: 'CUST-102938',
      controlId: 'CTRL-UK-AML-001',
      stepId: 'STEP-TM-DISP',
      operatorId: 'ACT-OWNER-01',
      outcome: 'pass',
      evidenceIds: ['EV-UK-OK-02'],
      evidenceCompletenessScore: 88,
      missingFields: [],
      expectedEvidenceStandardId: 'STD-EV-SCR-UK-01',
    },
    {
      id: 'CI-CYB-1001',
      caseOrTransactionId: 'PAM-Q1-2026',
      controlId: 'CTRL-UK-CYB-001',
      stepId: 'STEP-TM-DISP',
      operatorId: 'ACT-OWNER-01',
      outcome: 'pass',
      evidenceIds: ['EV-UK-OK-03'],
      evidenceCompletenessScore: 91,
      missingFields: [],
      expectedEvidenceStandardId: 'STD-EV-PAM-01',
    },
  ],
  evidenceRecords: [
    {
      id: 'EV-UK-ATTEST-01',
      evidenceType: 'attestation',
      s166Ready: true,
      consumerDutyRelevant: false,
      payloadPreview: '{ "period": "2026-Q1", "signer": "SMF4", "hash": "a1b2…" }',
      sourceSystem: 'governance_portal',
      createdTs: '2026-04-20T09:00:05Z',
      ingestedTs: '2026-04-20T09:02:00Z',
      collectionMethod: 'workflow',
      payloadHash: 'sha256:0f1e2d3c4b5a6978',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'regulatory',
      retentionExpiry: '2031-04-20',
      evidenceStandardId: 'STD-EV-ATTEST-01',
      evidenceCompletenessScore: 94,
      evidenceFreshnessDays: 5,
      missingFields: [],
      regulatorReady: true,
      linkedAuditPackIds: ['AP-S165-FCC-001'],
    },
    {
      id: 'EV-UK-MIN-RCO-04',
      evidenceType: 'minutes',
      s166Ready: true,
      consumerDutyRelevant: false,
      payloadPreview: 'RCO minutes excerpt…',
      sourceSystem: 'board_portal',
      createdTs: '2026-04-01T12:00:00Z',
      ingestedTs: '2026-04-01T12:30:00Z',
      collectionMethod: 'upload',
      payloadHash: 'sha256:9f8e7d6c5b4a3210',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'regulatory',
      retentionExpiry: '2031-04-01',
      evidenceStandardId: 'STD-EV-MIN-01',
      evidenceCompletenessScore: 88,
      evidenceFreshnessDays: 24,
      missingFields: [],
      regulatorReady: true,
      linkedAuditPackIds: ['AP-S165-FCC-001'],
    },
    {
      id: 'EV-UK-PARTIAL-01',
      evidenceType: 'system_log',
      s166Ready: false,
      consumerDutyRelevant: false,
      payloadPreview: '{ "alert_id": "AL-991", "disposition": "pending" }',
      sourceSystem: 'tm_engine',
      createdTs: '2026-04-24T08:00:00Z',
      ingestedTs: '2026-04-24T08:05:00Z',
      collectionMethod: 'automated',
      payloadHash: 'sha256:deadbeef01',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'operational',
      retentionExpiry: '2029-04-24',
      evidenceStandardId: 'STD-EV-TM-UK-01',
      evidenceCompletenessScore: 55,
      evidenceFreshnessDays: 2,
      missingFields: ['narrative_attachment'],
      regulatorReady: false,
      linkedAuditPackIds: [],
    },
    {
      id: 'EV-UK-OK-01',
      evidenceType: 'case_file',
      s166Ready: true,
      consumerDutyRelevant: false,
      payloadPreview: '{ "complete": true }',
      sourceSystem: 'case_mgmt',
      createdTs: '2026-04-23T10:00:00Z',
      ingestedTs: '2026-04-23T10:01:00Z',
      collectionMethod: 'workflow',
      payloadHash: 'sha256:cafebabe',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'regulatory',
      retentionExpiry: '2031-04-23',
      evidenceStandardId: 'STD-EV-TM-UK-01',
      evidenceCompletenessScore: 92,
      evidenceFreshnessDays: 3,
      missingFields: [],
      regulatorReady: true,
      linkedAuditPackIds: [],
    },
    {
      id: 'EV-UK-OK-02',
      evidenceType: 'screening',
      s166Ready: true,
      consumerDutyRelevant: false,
      payloadPreview: '{ "hits": 0 }',
      sourceSystem: 'screening',
      createdTs: '2026-04-22T15:00:00Z',
      ingestedTs: '2026-04-22T15:02:00Z',
      collectionMethod: 'automated',
      payloadHash: 'sha256:feedface',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'regulatory',
      retentionExpiry: '2031-04-22',
      evidenceStandardId: 'STD-EV-SCR-UK-01',
      evidenceCompletenessScore: 88,
      evidenceFreshnessDays: 4,
      missingFields: [],
      regulatorReady: true,
      linkedAuditPackIds: [],
    },
    {
      id: 'EV-UK-OK-03',
      evidenceType: 'access_review',
      s166Ready: true,
      consumerDutyRelevant: false,
      payloadPreview: '{ "review": "Q1-2026", "exceptions": 2 }',
      sourceSystem: 'pam_tool',
      createdTs: '2026-04-21T09:00:00Z',
      ingestedTs: '2026-04-21T09:10:00Z',
      collectionMethod: 'upload',
      payloadHash: 'sha256:11223344',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'regulatory',
      retentionExpiry: '2031-04-21',
      evidenceStandardId: 'STD-EV-PAM-01',
      evidenceCompletenessScore: 91,
      evidenceFreshnessDays: 5,
      missingFields: [],
      regulatorReady: true,
      linkedAuditPackIds: [],
    },
    {
      id: 'EV-UK-MIN-FCC-04',
      evidenceType: 'minutes',
      s166Ready: true,
      consumerDutyRelevant: false,
      payloadPreview: 'FCC forum minutes…',
      sourceSystem: 'board_portal',
      createdTs: '2026-04-25T14:05:00Z',
      ingestedTs: '2026-04-25T14:20:00Z',
      collectionMethod: 'upload',
      payloadHash: 'sha256:55667788',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'regulatory',
      retentionExpiry: '2031-04-25',
      evidenceStandardId: 'STD-EV-MIN-01',
      evidenceCompletenessScore: 90,
      evidenceFreshnessDays: 1,
      missingFields: [],
      regulatorReady: true,
      linkedAuditPackIds: ['AP-S165-FCC-001'],
    },
    {
      id: 'EV-UK-QA-01',
      evidenceType: 'workpaper',
      s166Ready: false,
      consumerDutyRelevant: false,
      payloadPreview: 'QA sample summary…',
      sourceSystem: 'grc',
      createdTs: '2026-04-10T16:25:00Z',
      ingestedTs: '2026-04-10T16:30:00Z',
      collectionMethod: 'workflow',
      payloadHash: 'sha256:99aabbcc',
      hashVerified: true,
      chainOfCustodyStatus: 'intact',
      retentionClass: 'operational',
      retentionExpiry: '2029-04-10',
      evidenceStandardId: 'STD-EV-WP-01',
      evidenceCompletenessScore: 72,
      evidenceFreshnessDays: 14,
      missingFields: ['partner_sign_off'],
      regulatorReady: false,
      linkedAuditPackIds: [],
    },
  ],
  exceptions: [],
  issues: [
    {
      id: 'ISS-UK-AML-014',
      title: 'TM disposition SLA breaches concentrated in wholesale desk',
      description: 'Empirical cluster of late dispositions correlated with desk staffing model change.',
      severity: 'high' as const,
      source: 'testing' as const,
      status: 'open' as const,
      regulatoryReportableFlag: false,
      daysOpen: 42,
      raisedDate: '2026-02-18',
      targetCloseDate: '2026-06-30',
      rootCauseClusterId: 'RC-CLUSTER-01',
      rootCauseClusterName: 'Operating model / capacity',
      rootCause: 'Capacity shortfall post reorganisation not reflected in runbooks.',
      pastClusterSuccessRate: 'Historical remediation success for this cluster: 72% within 90 days.',
      siblingIssueIds: ['ISS-UK-OPS-009'],
      linkedControlInstanceIds: ['CI-AML-9001', 'CI-AML-9002'],
      ownerId: 'ACT-OWNER-01',
      accountableSMFId: 'SMF17-PRIYA-PATEL',
      linkedRiskIds: ['R-UK-AML-001'],
      linkedObligationIds: ['OBL-UK-MLR-83'],
    },
    {
      id: 'ISS-UK-OPS-009',
      title: 'Manual workaround in wire release path',
      description: 'Sibling issue linked to capacity cluster.',
      severity: 'medium' as const,
      source: 'audit' as const,
      status: 'open' as const,
      regulatoryReportableFlag: false,
      daysOpen: 30,
      raisedDate: '2026-03-01',
      targetCloseDate: '2026-05-30',
      rootCauseClusterId: 'RC-CLUSTER-01',
      rootCauseClusterName: 'Operating model / capacity',
      rootCause: 'Temporary workaround bypassing standard queue.',
      pastClusterSuccessRate: null,
      siblingIssueIds: ['ISS-UK-AML-014'],
      linkedControlInstanceIds: [],
      ownerId: 'ACT-OWNER-01',
      accountableSMFId: 'SMF16-ALEX-MORGAN',
      linkedRiskIds: ['R-UK-OPS-001'],
      linkedObligationIds: ['OBL-UK-PS21-2'],
    },
  ],
  remediationActions: [
    {
      id: 'REM-UK-001',
      issueId: 'ISS-UK-AML-014',
      ownerId: 'ACT-OWNER-01',
      description: 'Hire two L1 analysts and rebalance queue routing.',
      status: 'in_progress' as const,
      dueDate: '2026-05-15',
      validationStatus: 'pending' as const,
    },
    {
      id: 'REM-UK-002',
      issueId: 'ISS-UK-AML-014',
      ownerId: 'ACT-TESTER-01',
      description: 'Refresh TM tuning memo with FCC sign-off.',
      status: 'open' as const,
      dueDate: '2026-05-30',
      validationStatus: null,
    },
  ],
  tests: [
    {
      id: 'TEST-Q2-AML-002',
      controlId: 'CTRL-UK-AML-002',
      workpaperId: 'WP-UK-AML-002',
      testerId: 'ACT-TESTER-01',
      testerFunction: '2LoD Compliance Testing',
      testWindowStart: '2026-04-01',
      testWindowEnd: '2026-04-30',
      status: 'in_progress' as const,
      method: 'population' as const,
      populationSize: 18420,
      excludedCount: 120,
      excludedReason: 'Duplicate alerts merged in source',
      eligibleCount: 18300,
      testedCount: 18300,
      exceptionCount: 142,
      result: 'qualified' as const,
      exceptionDetails: [
        { type: 'missing_evidence', count: 88 },
        { type: 'late_disposition', count: 36 },
        { type: 'other', count: 18 },
      ],
      exceptionInstanceIds: ['CI-AML-9001', 'CI-AML-9002', 'CI-AML-9003'],
      populationQueryRef: 'POP/TM/UK/Q2-2026/v3',
      populationQueryHash: 'sha256:pophash0123456789abcdef',
      samplingRationale: null as string | null,
    },
    {
      id: 'TEST-Q1-SCR-001',
      controlId: 'CTRL-UK-AML-001',
      workpaperId: 'WP-UK-SCR-001',
      testerId: 'ACT-TESTER-01',
      testerFunction: '2LoD Compliance Testing',
      testWindowStart: '2026-01-01',
      testWindowEnd: '2026-03-31',
      status: 'done' as const,
      method: 'sample_stratified' as const,
      populationSize: 50200,
      excludedCount: 0,
      excludedReason: null as string | null,
      eligibleCount: 50200,
      testedCount: 450,
      exceptionCount: 6,
      result: 'pass_with_observations' as const,
      exceptionDetails: [{ type: 'documentation', count: 6 }],
      exceptionInstanceIds: [],
      populationQueryRef: 'POP/SCR/UK/Q1-2026/v1',
      populationQueryHash: 'sha256:scrhash',
      samplingRationale: 'Stratified sample by risk rating; 450 selections.',
    },
  ],
  workpapers: [
    {
      id: 'WP-UK-AML-002',
      controlId: 'CTRL-UK-AML-002',
      generatedSummary: 'Population reperformance of TM dispositions for April 2026.',
      status: 'draft' as const,
      aiAssistanceLineage: { humanEditsCount: 7, finalHumanOwner: 'Sam Taylor' },
      findings: 'Exception rate elevated vs prior quarter; missing evidence concentrated in wholesale queue.',
      conclusion: 'Qualified opinion — remediation plan required before sign-off.',
    },
    {
      id: 'WP-UK-SCR-001',
      controlId: 'CTRL-UK-AML-001',
      generatedSummary: 'Stratified sample testing of screening outcomes.',
      status: 'signed_off' as const,
      aiAssistanceLineage: null,
      findings: 'Minor documentation gaps only.',
      conclusion: 'Pass with observations.',
    },
  ],
  auditPacks: [
    {
      id: 'AP-S165-FCC-001',
      title: 's.166-style FCC control & evidence pack (Q2 dry run)',
      scopeType: 'regulatory_exam_prep' as const,
      targetAudience: 'PRA_FCA' as const,
      timeWindowStart: '2026-01-01',
      timeWindowEnd: '2026-04-30',
      asOfStateDate: '2026-04-30',
      asOfStateHash: 'sha256:packstate0123456789abcdef0123456789abcdef',
      readinessStatus: 'internal_review' as const,
      composition: {
        controls: { count: 42, sampleIds: ['CTRL-UK-AML-002', 'CTRL-UK-AML-001'] },
        obligations: { count: 18, sampleIds: ['OBL-UK-MLR-83'] },
        evidence: { count: 12040, sampleIds: ['EV-UK-ATTEST-01'] },
        issues: { count: 6, sampleIds: ['ISS-UK-AML-014'] },
        workpapers: { count: 14, sampleIds: ['WP-UK-AML-002'] },
        smfRecords: { count: 9, sampleIds: ['SMF17-PRIYA-PATEL'] },
        kriObservations: { count: 220, sampleIds: [] },
        appetiteObservations: { count: 48, sampleIds: [] },
        totalEntities: 12407,
      },
      chainOfCustodyManifest: {
        evidenceCount: 12040,
        allHashesVerified: true,
        manifestSigned: false,
        manifestTs: '2026-04-29T17:00:00Z',
      },
      narrativeLineage: { model: 'gpt', modelVersion: '4.1', perParagraphCitationCount: 38, inputsNotSeen: ['Informal email threads not ingested'] },
      generatedNarrative:
        'Executive summary\nThis pack summarises the state of FCC controls for the period ending 30 April 2026.\n\nControl effectiveness\nKey controls show stable operating performance with elevated evidence gaps in wholesale TM.\n\nSMCR & governance\nSMF17 reasonable steps trail demonstrates active oversight with open items on backlog remediation.\n\nAppendix\nHashes and manifests are attached for independent verification.',
    },
    {
      id: 'AP-UK-OPS-001',
      title: 'Operational resilience evidence bundle',
      scopeType: 'internal_audit' as const,
      targetAudience: 'BOARD' as const,
      timeWindowStart: '2025-10-01',
      timeWindowEnd: '2026-03-31',
      asOfStateDate: '2026-03-31',
      asOfStateHash: 'sha256:ops001',
      readinessStatus: 'drafting' as const,
      composition: {
        controls: { count: 12, sampleIds: ['CTRL-UK-OPS-001'] },
        obligations: { count: 4, sampleIds: ['OBL-UK-PS21-2'] },
        evidence: { count: 800, sampleIds: ['EV-UK-OK-03'] },
        issues: { count: 1, sampleIds: ['ISS-UK-OPS-009'] },
        workpapers: { count: 3, sampleIds: [] },
        smfRecords: { count: 2, sampleIds: ['SMF16-ALEX-MORGAN'] },
        kriObservations: { count: 40, sampleIds: [] },
        appetiteObservations: { count: 10, sampleIds: [] },
        totalEntities: 872,
      },
      chainOfCustodyManifest: {
        evidenceCount: 800,
        allHashesVerified: false,
        manifestSigned: false,
        manifestTs: '2026-04-15T12:00:00Z',
      },
      narrativeLineage: { model: 'gpt', modelVersion: '4.1', perParagraphCitationCount: 12, inputsNotSeen: [] },
      generatedNarrative: 'Draft narrative for Ops resilience testing window.',
    },
  ],
  aiInsights: [
    {
      id: 'AI-UK-001',
      type: 'what_changed' as const,
      screenRelevance: ['riskPosture', 'controlUniverse'],
      title: 'Wholesale TM backlog gradient shifted post desk merge',
      summary: 'Model detects step-change in age distribution coincident with org change on 18 March.',
      severity: 'high' as const,
      confidence: 0.82,
      modelId: 'risktrace-uk-v1',
      modelVersion: '2026.04',
      relatedEntityIds: [{ type: 'control' as const, id: 'CTRL-UK-AML-002' }],
      methodology: 'Bayesian change-point on alert-age cohorts; counterfactual tested against synthetic control desks.',
      generatedAt: '2026-04-28T08:00:00Z',
      independenceLineage: { inputsFromLOD1: false, inputsFromLOD2: false },
      sourceRecordIds: [
        { type: 'control' as const, id: 'CTRL-UK-AML-002', label: 'TM disposition control' },
        { type: 'issue' as const, id: 'ISS-UK-AML-014', label: 'SLA breach cluster' },
      ],
      counterfactual: 'If staffing had stayed at February levels, p95 age would likely be 18% lower (CI 9–26%).',
      inputsNotSeen: ['Informal WhatsApp escalation threads'],
      humanActionStatus: 'pending_review' as const,
    },
    {
      id: 'AI-UK-002',
      type: 'anomaly' as const,
      screenRelevance: ['controlUniverse'],
      title: 'Evidence completeness dip isolated to one TM segment',
      summary: 'Segment 7 shows disproportionate missing narrative attachments.',
      severity: 'medium' as const,
      confidence: 0.74,
      modelId: 'risktrace-uk-v1',
      modelVersion: '2026.04',
      relatedEntityIds: [{ type: 'control' as const, id: 'CTRL-UK-AML-002' }],
      methodology: 'Isolation Forest on instance-level EC scores.',
      generatedAt: '2026-04-27T10:00:00Z',
      independenceLineage: { inputsFromLOD1: false, inputsFromLOD2: true },
      sourceRecordIds: [{ type: 'evidence' as const, id: 'EV-UK-PARTIAL-01', label: 'Partial capture' }],
      counterfactual: null,
      inputsNotSeen: [],
      humanActionStatus: 'acknowledged' as const,
    },
    {
      id: 'AI-UK-003',
      type: 'root_cause' as const,
      screenRelevance: ['riskPosture'],
      title: 'Capacity cluster links AML and Ops issues',
      summary: 'Graph walk suggests shared root cause between ISS-UK-AML-014 and ISS-UK-OPS-009.',
      severity: 'medium' as const,
      confidence: 0.66,
      modelId: 'risktrace-uk-v1',
      modelVersion: '2026.04',
      relatedEntityIds: [
        { type: 'issue' as const, id: 'ISS-UK-AML-014' },
        { type: 'issue' as const, id: 'ISS-UK-OPS-009' },
      ],
      methodology: 'Graph attention over issue / control / change-ticket edges.',
      generatedAt: '2026-04-26T15:00:00Z',
      independenceLineage: { inputsFromLOD1: true, inputsFromLOD2: false },
      sourceRecordIds: [{ type: 'issue' as const, id: 'ISS-UK-AML-014', label: 'TM SLA' }],
      counterfactual: null,
      inputsNotSeen: ['HR system workforce plans'],
      humanActionStatus: 'pending_review' as const,
    },
    {
      id: 'AI-UK-004',
      type: 'coverage' as const,
      screenRelevance: ['controlUniverse'],
      title: 'CRR large exposures obligation thinly linked',
      summary: 'Only one control mapped; consider adding early warning KRI linkage.',
      severity: 'low' as const,
      confidence: 0.71,
      modelId: 'risktrace-uk-v1',
      modelVersion: '2026.04',
      relatedEntityIds: [{ type: 'obligation' as const, id: 'OBL-UK-CRR' }],
      methodology: 'OCS decomposition vs peer banks (anonymised benchmarks).',
      generatedAt: '2026-04-25T09:00:00Z',
      independenceLineage: { inputsFromLOD1: false, inputsFromLOD2: false },
      sourceRecordIds: [{ type: 'obligation' as const, id: 'OBL-UK-CRR', label: 'CRR Art.81' }],
      counterfactual: null,
      inputsNotSeen: [],
      humanActionStatus: 'actioned' as const,
    },
  ],
  auditTrailEvents: [],
  metrics: {
    enterpriseRES: {
      value: 58,
      band: 'amber' as const,
      delta: 3,
      sparklineSeries: spark(58),
      praSREPCategory: '2' as const,
    },
    byPersona: {
      cro: {
        inboxItems: [
          {
            id: 'INBOX-01',
            label: 'Escalate TM qualified test to CRO decision',
            type: 'testing_outcome',
            ageDays: 4,
            targetEntityType: 'issue' as const,
            targetEntityId: 'ISS-UK-AML-014',
            severity: 'high' as const,
          },
          {
            id: 'INBOX-02',
            label: 'Audit pack readiness for FCC dry run',
            type: 'audit_pack',
            ageDays: 2,
            targetEntityType: 'auditPack' as const,
            targetEntityId: 'AP-S165-FCC-001',
            severity: 'medium' as const,
          },
          {
            id: 'INBOX-03',
            label: 'AI insight — capacity cluster',
            type: 'ai_insight',
            ageDays: 1,
            targetEntityType: 'aiInsight' as const,
            targetEntityId: 'AI-UK-003',
            severity: 'medium' as const,
          },
        ],
      },
    },
  },
};

export default mockControlTraceData;
