import { buildPosture } from "./constants";
import { fmtRs } from "./format";
import type { KeystoneDataV4 } from "./types";

export function createInitialStore(): KeystoneDataV4 {
  return {
    company: {
      exciseBase: { amount: 64.8, unit: "bn", tag: "SOURCED" },
      penaltyPct: { value: 100, tag: "SOURCED" },
      totalTaxes: { amount: 97, unit: "bn", tag: "SOURCED" },
      fy2026Revenue: { amount: 132.4, unit: "bn", tag: "SOURCED" },
      capacityHL: { low: 2.0, high: 2.4, unit: "M hL", tag: "OPEN" },
      exposureBand: { low: 160, high: 650, unit: "M", tag: "ILLUSTRATIVE" },
    },
    reconciliation: {
      streams: [
        { key: "packagedVolume", label: "Packaged volume", value: 12400, unit: "units", status: "AGREE", src: "SAP ECC" },
        { key: "stickersConsumed", label: "Tickets / stickers", value: 11900, unit: "units", status: "MISMATCH", src: "Excise portal" },
        { key: "permitsIssued", label: "Permits issued", value: 12400, unit: "units", status: "AGREE", src: "Permit system" },
        { key: "dutyDeclared", label: "Duty declared", value: null, unit: "", status: "AGREE", src: "Excise return" },
      ],
      nodeState: "AT_RISK",
      expectedDuty: 79.36,
      variance: {
        amount: 3.2,
        unit: "M",
        status: "AT_RISK",
        unaccounted: 500,
        tag: "ILLUSTRATIVE",
        rootCause:
          "12,400 units packaged on dispatch window D-1184, but only 11,900 per-bottle tickets (Fool Proof Stickers) logged against issued permits — 500 units unaccounted → ~Rs 3.2M duty at risk.",
      },
      detection: { value: "2 min vs ~weeks manual", tag: "ASSUMPTION" },
    },
    batch: {
      id: "B-2271",
      src: "Brewery Mgmt — Krones API",
      panel: [["Microbiological", "PASS"], ["Sensory panel", "PASS"], ["ABV verification", "FAIL"]],
      abv: { lab: 4.8, label: 4.6, excise: 4.6, delta: 0.2, tag: "ILLUSTRATIVE" },
      dutyAtStake: {
        amount: 0.6,
        unit: "M",
        tag: "ILLUSTRATIVE",
        basis: "0.2 ABV pts × this batch's duty-able volume (≈50,000 L) × duty rate — illustrative",
      },
    },
    receivables: {
      fy2025: 5410000000,
      fy2026: 4070000000,
      trend: "IMPROVING",
      yoyPct: 25,
      badDebt: 23000000,
      badDebtPctOfBook: 0.6,
      creditDays: null,
      eclAgeing: "OPEN",
      distributorPoints: { low: 1130, high: 4000, tag: "OPEN" },
      ageing: [
        { bucket: "Current 0–30d", amt: 3300000000, pct: 81, sev: "LOW" },
        { bucket: "31–60d", amt: 520000000, pct: 13, sev: "MED" },
        { bucket: "60+d", amt: 250000000, pct: 6, sev: "HIGH" },
      ],
      src: "SFA + SAP ECC",
    },
    loads: [
      { id: "L-442", date: "14 May", value: 4200000, pos: "Distributor #903 — Nugegoda depot (Western)", fl: "FL-3", status: "LAPSED", state: "BLOCKED", sltda: "NA" },
      { id: "L-441", date: "14 May", value: 3100000, pos: "Distributor #57 — Kandy depot (Central) · on-trade chain", fl: "FL-3", status: "EXPIRING", state: "FLAGGED", sltda: "LAPSED" },
      { id: "L-440", date: "15 May", value: 2600000, pos: "Distributor #218 — Borella depot (Western)", fl: "FL-3", status: "VALID", state: "CLEAR", sltda: "NA" },
    ],
    riskMatrix: {
      rows: [
        {
          id: "rm-supply",
          category: "Global events and supply chain disruptions",
          catTag: "SOURCED",
          domain: "D9",
          inherent: { i: "HIGH", l: "MED" },
          control: null,
          residual: "MED",
          mitigation: "Diversified multi-region sourcing; strategic inventory reserves; local-supplier development.",
          kri: null,
          trend: "STABLE",
        },
        {
          id: "rm-local",
          category: "Local market and economic risks",
          catTag: "SOURCED",
          domain: "D7",
          inherent: { i: "HIGH", l: "MED" },
          control: null,
          residual: "MED",
          mitigation: "Macroeconomic monitoring; pricing strategy; operational-efficiency / cost management.",
          kri: { label: "Contingent liabilities (bank guarantees, FY2026, from Rs 4,070M)", value: fmtRs(3514000000), tag: "SOURCED", status: "WATCH" },
          trend: "STABLE",
        },
        {
          id: "rm-tax",
          category: "Taxation and tariffs",
          catTag: "SOURCED",
          domain: "D1",
          inherent: { i: "HIGH", l: "HIGH" },
          control: "Duty",
          residual: "MED",
          mitigation: "Corporate tax 40%→45% from 1 Apr 2025 (income tax +39% YoY); live four-way excise tie-out catches duty variance pre-emptively.",
          kri: { label: "Total taxes to Government (FY2025)", value: fmtRs(97000000000), tag: "SOURCED", status: "WATCH" },
          trend: "STABLE",
        },
        {
          id: "rm-recv",
          category: "Receivables / distributor-credit exposure",
          catTag: "ILLUSTRATIVE",
          domain: "D7",
          inherent: { i: "MED", l: "MED" },
          control: "Dispatch",
          residual: "LOW",
          mitigation: "Tight credit control (small bad-debt book); early-warning on credit-days; receivables falling Rs 5.41bn → 4.07bn.",
          kri: { label: "Group trade receivables (FY2026)", value: fmtRs(4070000000), tag: "SOURCED", status: "OK" },
          trend: "IMPROVING",
        },
        {
          id: "rm-bcp",
          category: "Business continuity / flood risk",
          catTag: "ILLUSTRATIVE",
          domain: "D10",
          inherent: { i: "HIGH", l: "LOW" },
          control: null,
          residual: "MED",
          mitigation: "Riverbank-plant flood history; Swift Water Rescue training; business-interruption insurance; Site B / DR under consideration.",
          kri: null,
          trend: "STABLE",
        },
      ],
      escalation: { steps: ["Risk register", "Board", "Quarterly ESG Committee"], tag: "SOURCED" },
    },
    complianceExceptions: [
      {
        id: "ce-independence",
        ruleRef: "7.10.2(a)",
        title: "Minimum independent directors",
        gap: "2 of 3 required",
        disclosureRef: "LION/CSE/ANN/2024/NS/04 (1 Feb 2024)",
        cure: "Ajay Baliga, Independent NED, appointed 2 Feb 2024",
        status: "CURED",
        raisedOn: "Nov 2023",
        curedOn: "2 Feb 2024",
        tag: "VERIFIED",
      },
    ],
    boardReport: {
      sectionOrder: ["Board-affairs compliance statement", "Audit Committee", "RPT Review Committee", "Auditor sign-off"],
      committees: [
        {
          id: "cm-audit",
          name: "Audit Committee",
          remit: "Oversee the financial-reporting process, internal control, the audit process and compliance with laws — the Companies Act No. 07 of 2007 and the SEC Act No. 19 of 2021 — and review internal controls and risk against Sri Lanka Accounting Standards.",
          remitTag: "VERIFIED",
          composition: ["A.S. Amaratunga (Chair, NE/Ind)", "A.J. Alles (NE/Ind)", "D.R.P. Goonetilleke (NE)"],
          meetingCount: null,
        },
        {
          id: "cm-rem",
          name: "Remuneration Committee",
          remit: "Maintain formal, transparent policies for Director and CEO compensation to attract, retain and develop talent.",
          remitTag: "VERIFIED",
          composition: ["A.B. Baliga (Chair, NE/Ind)"],
          meetingCount: null,
        },
        {
          id: "cm-rpt",
          name: "Related Party Transactions Review Committee",
          remit: "Maintain policy and process per the CSE RPT rules for identification, classification and end-to-end reporting of related party transactions.",
          remitTag: "VERIFIED",
          composition: ["A.S. Amaratunga (Chair)", "A.B. Baliga", "D.R.P. Goonetilleke"],
          meetingCount: null,
        },
        {
          id: "cm-nom",
          name: "Nominations & Governance Committee",
          remit: "Formal procedure to appoint / re-elect directors; succession planning; Board composition; recommend the corporate-governance framework.",
          remitTag: "VERIFIED",
          composition: ["Functions via Carson Cumberbatch PLC"],
          meetingCount: null,
        },
      ],
      complianceTable: [{ ruleRef: "7.10.2(a)", requirement: "Minimum number of independent directors", exceptionRef: "ce-independence" }],
      assurance: {
        companiesAct: "These financial statements are in compliance with the requirements of the Companies Act No. 07 of 2007.",
        thanks: "Grateful thanks for the counsel and oversight of the Audit, Remuneration, Related Party Transactions Review, and Nominations & Governance Committees, and fellow Board members.",
        tag: "VERIFIED",
      },
    },
    evidence: {
      EXCISE: [
        {
          id: "e1",
          label: "Batch release + ABV trail — B-2271",
          from: "C2",
          status: "CHECKED",
          signedBy: "QA / Lab Manager",
          ts: "14 May 2026",
          records: ["ABV triple-check — lab 4.8% / label 4.6% / excise-basis 4.6%", "QC panel — micro PASS, sensory PASS, ABV flagged & resolved", "Release sign-off recorded against batch"],
        },
        {
          id: "e2",
          label: "Dispatch licence stamps — L-440 / L-441 / L-442",
          from: "C3",
          status: "CHECKED",
          signedBy: "Distribution / Commercial",
          ts: "15 May 2026",
          records: ["FL-3 licence check — L-440 valid · L-441 SLTDA flagged · L-442 lapsed (blocked)", "Distributor-tier depots — Western / Central", "Auto-block evidence captured on the lapsed-licence load"],
        },
        {
          id: "e3",
          label: "Transport-permit ↔ sticker tie-out — May 2026",
          from: "C1",
          status: "CHECKED",
          signedBy: "Excise desk",
          ts: "May 2026",
          records: ["Permits issued 12,400 vs tickets logged 11,900 — variance flagged", "Per-bottle ticket reconciliation (see C1)"],
        },
      ],
      SLSI: [
        { id: "s1", label: "Batch release records — May 2026", from: "C2", status: "CHECKED", signedBy: "QA", ts: "May 2026", records: ["Batch QC summary", "Release approvals log"] },
        { id: "s2", label: "ABV verification trail — B-2271", from: "C2", status: "CHECKED", signedBy: "QA / Lab", ts: "14 May 2026", records: ["ABV triple-check detail and sign-off"] },
      ],
      FCAU: [{ id: "f1", label: "Batch release + QC panel — May 2026", from: "C2", status: "CHECKED", signedBy: "QA", ts: "May 2026", records: ["QC panel results", "Food-safety checks"] }],
      CUSTOMS: [
        { id: "c1", label: "Duty declaration — May 2026", from: "C1", status: "CHECKED", signedBy: "Finance / Excise", ts: "May 2026", records: ["Excise return summary", "Duty computed on the ABV basis"] },
        { id: "c2", label: "Dispatch licence stamps — export loads", from: "C3", status: "CHECKED", signedBy: "Distribution", ts: "May 2026", records: ["Export-load licence checks"] },
      ],
      CEA: [{ id: "ce1", label: "Environmental monitoring records — May 2026", from: "C2", status: "CHECKED", signedBy: "EHS", ts: "May 2026", records: ["Effluent / emissions logs", "Environmental-permit status"] }],
      LABOUR: [{ id: "l1", label: "Safety training + incident log — May 2026", from: "C2", status: "CHECKED", signedBy: "HR / EHS", ts: "May 2026", records: ["Safety-training register", "Incident log for the period"] }],
    },
    posture: buildPosture(),
    headlineMetrics: [
      {
        key: "exposure",
        label: "Excise exposure under live reconciliation",
        value: "Rs 160–650M",
        tag: "ILLUSTRATIVE",
        emphasis: "PRIMARY",
        note: "illustrative: assumed discrepancy rate × Rs 64.8bn excise base · same figure as C1",
      },
      {
        key: "receivablesExposure",
        label: "Receivables under live credit watch",
        value: fmtRs(4070000000),
        tag: "SOURCED",
        emphasis: "PRIMARY",
        note: "FY2026 · down ~25% YoY",
      },
      {
        key: "auditReady",
        label: "Regulators audit-ready",
        value: "6 / 6",
        tag: "SOURCED",
        emphasis: "PRIMARY",
        note: "evidence packs assemble on demand (C4)",
      },
    ],
  };
}
