import type { Scope3MockData } from "./types";
import { buildGhgGasInventory } from "./ghg-gas-inventory";
import { attachProcurementScope3Fields, type SupplierRowSeed } from "./scope3-procurement";
import { mergeSubmittedEvidencesDeep } from "./scope3-evidence-drilldown";

/** End-to-end bundled dataset for Scope 3 emissions management (GHG Protocol + India disclosures: BRSR / SEBI, CDP, SBTi). */
const scope3MockDataBase: Omit<Scope3MockData, "suppliers" | "ghgGasInventory"> & { suppliers: SupplierRowSeed[] } = {
  company: {
    legalName: "Sun Pharma Research Ltd",
    shortName: "SunPharma",
    sector: "Pharmaceuticals — formulations, sterile injectables & selected APIs",
    hq: "Corporate office — Mumbai; manufacturing — Gujarat (Vadodara, Dahej), Goa, Himachal Pradesh",
    operatingCountry: "India",
    brsrListed: true,
    sbtiCommitted: true,
    sbtiNearTermYear: 2030,
    listing: "NSE / BSE (large-cap) · consolidated subsidiary boundary for climate reporting",
    lastInventoryClose: "2025-03-31",
  },
  inventoryMeta: {
    reportingYearLabel: "FY2025 (1 Apr 2024 – 31 Mar 2025)",
    methodologyVersion:
      "GHG Protocol Corporate Value Chain (Scope 3) Standard (2011) · India grid & transport factors per CEA 2024 and BEE guidance where applicable · EF registry lock v2025.09 · GWP IPCC AR6 (100-yr)",
    organizationalBoundary:
      "Operational control per Companies Act consolidation — includes wholly owned formulation sites, R&D centres, and captive utilities; excludes non-operated JVs except downstream logistics JV where operational control tests were met in FY25 Q2 (see boundary memo EV-2025-0301). Category 13 pilot franchises remain immaterial and flagged not assured.",
    dataFreshnessNote:
      "Mock inventory for product demo: category totals reconcile to the executive Scope 3 KPI; supplier rows reflect attributed upstream/downstream contributions, not a full mass-balance closure to ERP spend until API integration.",
  },
  executive: {
    totalScope3TCO2e: 1847200,
    yoyScope3Pct: -3.2,
    primaryDataCoveragePct: 41,
    brsrReadinessPct: 73,
    verifiedSuppliers: 8,
    totalSuppliers: 20,
    spendEsgCompliantPct: 68,
    activeComplianceFlags: 7,
  },
  regulatory: [
    {
      code: "BRSR",
      label: "BRSR (SEBI)",
      deadline: "2026-06-30",
      status: "On Track",
      nextAction: "Finalize Section A GHG tables with assurance mapping.",
    },
    {
      code: "BRSR_CORE",
      label: "BRSR Core",
      deadline: "2026-05-15",
      status: "At Risk",
      nextAction:
        "Close four high-priority supplier gaps (CryoLab, ChemLogistics, OceanBulk, BioSterile Pack) affecting Core KPI coverage on PCFs and logistics attestations.",
    },
    {
      code: "SEBI_LODR",
      label: "SEBI LODR / ERP disclosures",
      deadline: "2026-07-31",
      status: "On Track",
      nextAction: "Align climate narrative with audited inventory numbers.",
    },
    {
      code: "DGFT_CBIC",
      label: "DGFT / CBIC — export consignment carbon evidence (pilot)",
      deadline: "2026-01-31",
      status: "At Risk",
      nextAction: "Upload embedded emissions worksheets for nominated export API batches (India clearances).",
    },
    {
      code: "MOEF_EPR",
      label: "MoEFCC EPR (plastic packaging)",
      deadline: "2026-09-30",
      status: "On Track",
      nextAction: "Reconcile EPR returns with packaging mass balances for FY25.",
    },
    {
      code: "CDP",
      label: "CDP Climate",
      deadline: "2026-07-26",
      status: "On Track",
      nextAction: "Validate C6 supply chain module with procurement sign-off.",
    },
    {
      code: "SBTI",
      label: "SBTi FLAG / near-term",
      deadline: "2030-12-31",
      status: "On Track",
      nextAction: "Maintain annual linear reduction vs. approved trajectory.",
    },
  ],
  trend: [
    { year: 2021, scope1: 188000, scope2: 355000, scope3: 1720000, sbtiTarget: 2020000 },
    { year: 2022, scope1: 228000, scope2: 408000, scope3: 1890000, sbtiTarget: 1960000 },
    { year: 2023, scope1: 210000, scope2: 380000, scope3: 1925000, sbtiTarget: 1880000 },
    { year: 2024, scope1: 195000, scope2: 318000, scope3: 1908300, sbtiTarget: 1845000 },
    { year: 2025, scope1: 218000, scope2: 368000, scope3: 1847200, sbtiTarget: 1810000 },
  ],
  scope3Categories: [
    {
      id: 1,
      name: "Purchased goods & services",
      stream: "Upstream",
      tCO2e: 782400,
      dataQuality: "Primary",
      pctOfTotal: 42.36,
      supplierCount: 48,
      yoyPct: -4.1,
      topSupplier: "APIchem India Pvt Ltd",
      methodologyNote:
        "Hybrid model: supplier-specific kgCO₂e/kg or kgCO₂e/INR where PCFs exist; India EEIO (EXIO / India hybrid desk) for long-tail excipients and indirect materials. Co-manufactured APIs use mass allocation per joint-plant letters where available.",
      emissionFactorSummary: "Supplier EF (kgCO2e/INR) + India EEIO proxies for gaps.",
      dataSources: ["Supplier PCFs (FY25 lock)", "SAP invoice lines — INR", "Internal LCA library v4.2", "Allocation memos (joint plant)"],
      controlGaps: ["3 suppliers on legacy spend-based only", "Missing allocation for co-manufactured SKUs"],
      brsrMapping: "BRSR Principle 6 — Energy & Emissions (Scope 3 upstream purchased goods).",
    },
    {
      id: 2,
      name: "Capital goods",
      stream: "Upstream",
      tCO2e: 68400,
      dataQuality: "Secondary",
      pctOfTotal: 3.7,
      supplierCount: 9,
      yoyPct: 6.2,
      topSupplier: "Siemens Ltd",
      methodologyNote: "Capital asset registers mapped to industry-average capital goods factors.",
      emissionFactorSummary: "India capital-goods intensity factors by asset class (industry proxy).",
      dataSources: ["Capex register", "Vendor invoices"],
      controlGaps: ["Asset tagging inconsistent for lab instruments"],
      brsrMapping: "BRSR — capex-linked emissions disclosure (supporting).",
    },
    {
      id: 3,
      name: "Fuel & energy-related (not S1/S2)",
      stream: "Upstream",
      tCO2e: 92800,
      dataQuality: "Secondary",
      pctOfTotal: 5.02,
      supplierCount: 6,
      yoyPct: -1.0,
      topSupplier: "Grid-linked T&D losses",
      methodologyNote: "Well-to-tank + T&D for purchased electricity and steam.",
      emissionFactorSummary: "CEA grid EF 2024 + IPCC WTT factors.",
      dataSources: ["Energy bills", "Steam allocation model"],
      controlGaps: ["Steam mass balance not fully closed at Goa site"],
      brsrMapping: "BRSR energy table — well-to-tank / T&D disclosure.",
    },
    {
      id: 4,
      name: "Upstream transportation & distribution",
      stream: "Upstream",
      tCO2e: 156300,
      dataQuality: "Primary",
      pctOfTotal: 8.46,
      supplierCount: 14,
      yoyPct: -2.4,
      topSupplier: "BlueDart-GreenFreight JV",
      methodologyNote: "Ton-km model with primary fleet data for key 3PL lanes.",
      emissionFactorSummary: "GLEC-aligned factors; primary where telematics available.",
      dataSources: ["TMS shipments", "3PL sustainability reports"],
      controlGaps: ["Spot charters missing weight verification"],
      brsrMapping: "BRSR logistics emissions — upstream distribution.",
    },
    {
      id: 5,
      name: "Waste generated in operations",
      stream: "Upstream",
      tCO2e: 31200,
      dataQuality: "Secondary",
      pctOfTotal: 1.69,
      supplierCount: 11,
      yoyPct: 0.8,
      topSupplier: "Ramky Enviro Engineers",
      methodologyNote: "Waste tonnage by treatment route × route-specific factors.",
      emissionFactorSummary: "CPCB / CPCB+ waste treatment factors + hazardous-stream proxies.",
      dataSources: ["Manifests", "Treatment certificates"],
      controlGaps: ["Hazardous sludge mass estimates quarterly only"],
      brsrMapping: "BRSR waste & emissions cross-link.",
    },
    {
      id: 6,
      name: "Business travel",
      stream: "Upstream",
      tCO2e: 18600,
      dataQuality: "Primary",
      pctOfTotal: 1.01,
      supplierCount: 4,
      yoyPct: 11.0,
      topSupplier: "Corporate travel program",
      methodologyNote: "Travel management system with RFI to CRF.",
      emissionFactorSummary: "India domestic aviation + rail / road factors by class & distance.",
      dataSources: ["Concur / SAP Travel"],
      controlGaps: ["Private charters not fully coded"],
      brsrMapping: "BRSR business travel footnote.",
    },
    {
      id: 7,
      name: "Employee commuting",
      stream: "Upstream",
      tCO2e: 44200,
      dataQuality: "Spend-Based",
      pctOfTotal: 2.39,
      supplierCount: 1,
      yoyPct: -0.5,
      topSupplier: "HR mobility survey",
      methodologyNote: "Survey-based mode split with India urban commuting benchmarks.",
      emissionFactorSummary: "Survey + national average fallback.",
      dataSources: ["FY25 commute survey (n=11,400)"],
      controlGaps: ["Low response at two CRO satellite offices"],
      brsrMapping: "BRSR social + environment narrative (commuting).",
    },
    {
      id: 8,
      name: "Upstream leased assets",
      stream: "Upstream",
      tCO2e: 28900,
      dataQuality: "Secondary",
      pctOfTotal: 1.56,
      supplierCount: 5,
      yoyPct: 2.1,
      topSupplier: "Indospace Warehousing",
      methodologyNote: "Leased floor area energy intensity benchmarks.",
      emissionFactorSummary: "BEE ECBC-like intensities by city cluster.",
      dataSources: ["Lease contracts", "Landlord disclosures"],
      controlGaps: ["Two landlords without energy disclosure"],
      brsrMapping: "Supporting note for leased operations.",
    },
    {
      id: 9,
      name: "Downstream transportation & distribution",
      stream: "Downstream",
      tCO2e: 188300,
      dataQuality: "Secondary",
      pctOfTotal: 10.19,
      supplierCount: 22,
      yoyPct: -1.8,
      topSupplier: "FedEx SupplyChain India",
      methodologyNote:
        "Distributor and 3PL TMS samples scaled to India sales volumes; cold-chain legs blended with metered electricity where IndoCold / FedEx primary extracts exist. Uncertainty higher where only hub averages available.",
      emissionFactorSummary: "Road + air blended; India regional freight intensity factors.",
      dataSources: ["Distributor TMS sample", "Sales volumes"],
      controlGaps: ["Cold-chain lane primary data <35%"],
      brsrMapping: "BRSR downstream logistics (where reported).",
    },
    {
      id: 10,
      name: "Processing of sold products",
      stream: "Downstream",
      tCO2e: 53400,
      dataQuality: "Secondary",
      pctOfTotal: 2.89,
      supplierCount: 7,
      yoyPct: 0.4,
      topSupplier: "Hospital compounding networks (India)",
      methodologyNote: "Allocated using sold volume × typical hospital processing energy.",
      emissionFactorSummary: "Literature-based hospital processing intensities.",
      dataSources: ["India sales SKUs", "Pharma distribution study 2023"],
      controlGaps: ["Limited primary data from hospital chains"],
      brsrMapping: "Downstream processing narrative for India hospital customers.",
    },
    {
      id: 11,
      name: "Use of sold products",
      stream: "Downstream",
      tCO2e: 195700,
      dataQuality: "Spend-Based",
      pctOfTotal: 10.59,
      supplierCount: 3,
      yoyPct: -6.0,
      topSupplier: "Retail & hospital use phase",
      methodologyNote:
        "Portfolio-weighted use-phase model: Rx injectables (cold chain + clinical waste pathway), oral solids (patient transport negligible), OTC (retail refrigeration share). Monte Carlo uncertainty documented for BRSR sensitivity.",
      emissionFactorSummary: "Portfolio-weighted use-phase factors (internal LCA).",
      dataSources: ["SKU classification", "Internal LCA models"],
      controlGaps: ["High uncertainty band — flagged for BRSR extended narrative / sensitivity disclosure"],
      brsrMapping: "BRSR / CDP — use-phase assumptions documented.",
    },
    {
      id: 12,
      name: "End-of-life treatment of sold products",
      stream: "Downstream",
      tCO2e: 67800,
      dataQuality: "Secondary",
      pctOfTotal: 3.67,
      supplierCount: 8,
      yoyPct: 1.2,
      topSupplier: "EPR plastics recovery partners",
      methodologyNote: "EoL split by packaging material and regional recovery rates.",
      emissionFactorSummary: "CPCB / India regional landfill & incineration mix.",
      dataSources: ["Packaging BOM", "EPR reports"],
      controlGaps: ["India EPR reporting lag by one quarter"],
      brsrMapping: "Packaging & circularity linkage.",
    },
    {
      id: 13,
      name: "Downstream leased assets",
      stream: "Downstream",
      tCO2e: 12100,
      dataQuality: "Not Assessed",
      pctOfTotal: 0.66,
      supplierCount: 2,
      yoyPct: 0.0,
      topSupplier: "Franchise pharmacy coolers (pilot)",
      methodologyNote: "Pilot program — methodology under development.",
      emissionFactorSummary: "Placeholder benchmark pending primary study.",
      dataSources: ["Pilot contracts"],
      controlGaps: ["Methodology not finalized", "Excluded from assurance boundary FY25"],
      brsrMapping: "Excluded with justification (immaterial pilot).",
    },
    {
      id: 14,
      name: "Franchises",
      stream: "Downstream",
      tCO2e: 8600,
      dataQuality: "Secondary",
      pctOfTotal: 0.47,
      supplierCount: 4,
      yoyPct: 3.0,
      topSupplier: "Franchise retail network",
      methodologyNote: "Revenue-based allocation using franchise disclosure pack.",
      emissionFactorSummary: "Retail intensity benchmarks.",
      dataSources: ["Franchise revenue", "Disclosure pack"],
      controlGaps: ["Two franchisees late reporting"],
      brsrMapping: "Franchise emissions footnote.",
    },
    {
      id: 15,
      name: "Investments",
      stream: "Downstream",
      tCO2e: 98500,
      dataQuality: "Spend-Based",
      pctOfTotal: 5.33,
      supplierCount: 6,
      yoyPct: 1.9,
      topSupplier: "Listed equity portfolio (financed emissions)",
      methodologyNote: "PCAF-style financed emissions for listed minority stakes.",
      emissionFactorSummary: "EEIO financed emissions — PCAF data quality score 3.",
      dataSources: ["Treasury holdings snapshot", "India-listed equity EF database (reference)"],
      controlGaps: ["Private equity holdings out of scope FY25"],
      brsrMapping: "Financed emissions voluntary disclosure block.",
    },
  ],
  suppliers: [
    {
      id: "s1",
      name: "APIchem India Pvt Ltd",
      segment: "API manufacturing",
      productPurchased: "Paracetamol API, ibuprofen intermediates",
      annualSpendCr: 420,
      scope3ContributionTCO2e: 198400,
      esgScore: 82,
      dataQuality: "Primary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-11-02",
      risk: "Low",
      primaryCategories: [1, 4],
      dataGaps: [],
      aiSuggestedActions: ["Maintain annual PCF refresh cadence."],
    },
    {
      id: "s2",
      name: "PackWell Polymers Ltd",
      segment: "Packaging",
      productPurchased: "Blister foils, HDPE bottles, shrink film",
      annualSpendCr: 118,
      scope3ContributionTCO2e: 64200,
      esgScore: 71,
      dataQuality: "Secondary",
      submissionStatus: "Submitted",
      brsrMapped: true,
      lastAssessed: "2025-09-18",
      risk: "Medium",
      primaryCategories: [1, 12],
      dataGaps: ["Recycled content % not third-party verified"],
      aiSuggestedActions: ["Request ISCC PLUS or equivalent for recycled resins."],
    },
    {
      id: "s3",
      name: "BlueDart-GreenFreight JV",
      segment: "Logistics",
      productPurchased: "Domestic express & freight — APIs and finished goods",
      annualSpendCr: 86,
      scope3ContributionTCO2e: 95600,
      esgScore: 77,
      dataQuality: "Primary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-10-05",
      risk: "Low",
      primaryCategories: [4, 9],
      dataGaps: ["Spot air charters missing weight capture"],
      aiSuggestedActions: ["Enforce TMS weight fields for spot bookings."],
    },
    {
      id: "s4",
      name: "CryoLab Consumables Pvt Ltd",
      segment: "Lab consumables",
      productPurchased: "Cryovials, serological pipettes, filter tips",
      annualSpendCr: 34,
      scope3ContributionTCO2e: 22800,
      esgScore: 58,
      dataQuality: "Spend-Based",
      submissionStatus: "Pending",
      brsrMapped: false,
      lastAssessed: "2025-04-12",
      risk: "High",
      primaryCategories: [1],
      dataGaps: ["No PCF", "No renewable electricity proof"],
      aiSuggestedActions: ["Issue corrective action; consider dual sourcing."],
    },
    {
      id: "s5",
      name: "SynCRO Research Services",
      segment: "Contract research",
      productPurchased: "Analytical validation, stability studies, method transfers",
      annualSpendCr: 210,
      scope3ContributionTCO2e: 87400,
      esgScore: 74,
      dataQuality: "Secondary",
      submissionStatus: "Submitted",
      brsrMapped: true,
      lastAssessed: "2025-08-22",
      risk: "Medium",
      primaryCategories: [1, 6],
      dataGaps: ["Site-level energy not split by client"],
      aiSuggestedActions: ["Request client-specific allocation memo from CRO."],
    },
    {
      id: "s6",
      name: "ChemLogistics India",
      segment: "Hazmat road transport",
      productPurchased: "FTL hazmat — solvents & chemical intermediates",
      annualSpendCr: 52,
      scope3ContributionTCO2e: 31200,
      esgScore: 63,
      dataQuality: "Secondary",
      submissionStatus: "Overdue",
      brsrMapped: false,
      lastAssessed: "2024-12-01",
      risk: "High",
      primaryCategories: [4],
      dataGaps: ["No GLEC submission", "Driver training evidence missing"],
      aiSuggestedActions: ["Escalate to category owner; freeze new awards until remediated."],
    },
    {
      id: "s7",
      name: "GreenSteam Utilities",
      segment: "Steam / utilities",
      productPurchased: "Industrial steam (tonne-hours), condensate return services",
      annualSpendCr: 95,
      scope3ContributionTCO2e: 41800,
      esgScore: 80,
      dataQuality: "Primary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-10-30",
      risk: "Low",
      primaryCategories: [3],
      dataGaps: [],
      aiSuggestedActions: ["Document mass balance closure for assurance."],
    },
    {
      id: "s8",
      name: "SealFlex Export Packaging Pvt Ltd",
      segment: "Export packaging",
      productPurchased: "Export shippers, desiccants, temperature monitors",
      annualSpendCr: 64,
      scope3ContributionTCO2e: 28600,
      esgScore: 88,
      dataQuality: "Primary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-07-14",
      risk: "Low",
      primaryCategories: [1, 9, 12],
      dataGaps: [],
      aiSuggestedActions: ["Use as reference supplier for export consignment evidence packs (JNPT / ICD lanes)."],
    },
    {
      id: "s9",
      name: "IndoCold Chain Ltd",
      segment: "Cold chain",
      productPurchased: "Cold storage & linehaul — vaccines and biologics",
      annualSpendCr: 71,
      scope3ContributionTCO2e: 50200,
      esgScore: 76,
      dataQuality: "Secondary",
      submissionStatus: "Submitted",
      brsrMapped: true,
      lastAssessed: "2025-06-09",
      risk: "Medium",
      primaryCategories: [4, 9],
      dataGaps: ["Reefer electricity mix estimated"],
      aiSuggestedActions: ["Request metered electricity splits for top 5 hubs."],
    },
    {
      id: "s10",
      name: "Metro Waste Solutions",
      segment: "Waste treatment",
      productPurchased: "Hazardous incineration, solvent recovery services",
      annualSpendCr: 9,
      scope3ContributionTCO2e: 9400,
      esgScore: 66,
      dataQuality: "Secondary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-05-20",
      risk: "Medium",
      primaryCategories: [5],
      dataGaps: ["Quarterly vs monthly granularity mismatch"],
      aiSuggestedActions: ["Align reporting cadence to inventory close."],
    },
    {
      id: "s11",
      name: "FineChem Intermediates",
      segment: "Intermediates",
      productPurchased: "N-acetyl intermediates, custom synthesis campaigns",
      annualSpendCr: 178,
      scope3ContributionTCO2e: 112600,
      esgScore: 69,
      dataQuality: "Primary",
      submissionStatus: "Submitted",
      brsrMapped: true,
      lastAssessed: "2025-09-01",
      risk: "Medium",
      primaryCategories: [1],
      dataGaps: ["Allocation for joint plant output pending"],
      aiSuggestedActions: ["Obtain mass-based allocation statement."],
    },
    {
      id: "s12",
      name: "PrintCraft Labels",
      segment: "Labels & inserts",
      productPurchased: "Carton inserts, patient leaflets, security labels",
      annualSpendCr: 22,
      scope3ContributionTCO2e: 11800,
      esgScore: 61,
      dataQuality: "Spend-Based",
      submissionStatus: "Pending",
      brsrMapped: false,
      lastAssessed: "2025-02-28",
      risk: "High",
      primaryCategories: [1, 12],
      dataGaps: ["No recycled paper chain-of-custody"],
      aiSuggestedActions: ["Switch to FSC-certified supplier or obtain PCF."],
    },
    {
      id: "s13",
      name: "AquaPure Water Systems",
      segment: "Water treatment chemicals",
      productPurchased: "RO antiscalants, membrane cleaning chemistry",
      annualSpendCr: 14,
      scope3ContributionTCO2e: 7600,
      esgScore: 72,
      dataQuality: "Secondary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-08-11",
      risk: "Low",
      primaryCategories: [1, 5],
      dataGaps: [],
      aiSuggestedActions: [],
    },
    {
      id: "s14",
      name: "SolarEdge Power Purchase",
      segment: "Renewable electricity",
      productPurchased: "Group captive solar PPA — I-REC eligible MWh",
      annualSpendCr: 31,
      scope3ContributionTCO2e: 4200,
      esgScore: 91,
      dataQuality: "Primary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-10-12",
      risk: "Low",
      primaryCategories: [3],
      dataGaps: [],
      aiSuggestedActions: ["Highlight as decarbonization lever in CDP narrative."],
    },
    {
      id: "s15",
      name: "TalentTravel Services",
      segment: "Travel management",
      productPurchased: "Corporate air, hotel, and ground transport program",
      annualSpendCr: 8,
      scope3ContributionTCO2e: 6200,
      esgScore: 84,
      dataQuality: "Primary",
      submissionStatus: "Verified",
      brsrMapped: true,
      lastAssessed: "2025-07-30",
      risk: "Low",
      primaryCategories: [6],
      dataGaps: [],
      aiSuggestedActions: [],
    },
    {
      id: "s16",
      name: "Indospace Warehousing",
      segment: "Leased warehousing",
      productPurchased: "Leased pallet positions — Bhiwandi & NCR hubs",
      annualSpendCr: 41,
      scope3ContributionTCO2e: 15200,
      esgScore: 67,
      dataQuality: "Secondary",
      submissionStatus: "Submitted",
      brsrMapped: true,
      lastAssessed: "2025-04-19",
      risk: "Medium",
      primaryCategories: [8],
      dataGaps: ["Two sites missing landlord energy disclosure"],
      aiSuggestedActions: ["Add green lease clause for FY27 renewals."],
    },
    {
      id: "s17",
      name: "FedEx SupplyChain India",
      segment: "Downstream logistics",
      productPurchased: "DC-to-hospital distribution, secondary packaging",
      annualSpendCr: 59,
      scope3ContributionTCO2e: 48800,
      esgScore: 76,
      dataQuality: "Secondary",
      submissionStatus: "Submitted",
      brsrMapped: true,
      lastAssessed: "2025-09-27",
      risk: "Medium",
      primaryCategories: [9],
      dataGaps: ["Primary telematics coverage 38%"],
      aiSuggestedActions: ["Negotiate primary data SLA in contract renewal."],
    },
    {
      id: "s18",
      name: "BioSterile Pack",
      segment: "Sterile packaging",
      productPurchased: "Pre-sterilized vials, Tyvek pouches, barrier films",
      annualSpendCr: 27,
      scope3ContributionTCO2e: 19400,
      esgScore: 64,
      dataQuality: "Secondary",
      submissionStatus: "Pending",
      brsrMapped: false,
      lastAssessed: "2025-03-10",
      risk: "High",
      primaryCategories: [1, 12],
      dataGaps: ["EO sterilization emissions estimated only"],
      aiSuggestedActions: ["Request facility-specific EO emission study."],
    },
    {
      id: "s19",
      name: "OceanBulk Chartering",
      segment: "Ocean freight",
      productPurchased: "Time charter & COA — bulk API ocean lanes",
      annualSpendCr: 36,
      scope3ContributionTCO2e: 28400,
      esgScore: 59,
      dataQuality: "Spend-Based",
      submissionStatus: "Overdue",
      brsrMapped: false,
      lastAssessed: "2024-10-15",
      risk: "High",
      primaryCategories: [4, 9],
      dataGaps: ["No fuel consumption data", "No CII reporting"],
      aiSuggestedActions: ["Require IMO DCS data sharing in RFQ award criteria."],
    },
    {
      id: "s20",
      name: "AgriFeed Organics",
      segment: "Excipient sourcing",
      productPurchased: "Organic excipients — starch, lactose, cellulose blends",
      annualSpendCr: 19,
      scope3ContributionTCO2e: 13200,
      esgScore: 70,
      dataQuality: "Secondary",
      submissionStatus: "Submitted",
      brsrMapped: true,
      lastAssessed: "2025-08-03",
      risk: "Medium",
      primaryCategories: [1],
      dataGaps: ["FLAG emissions screening incomplete"],
      aiSuggestedActions: ["Complete FLAG screening for SBTi."],
    },
  ],
  buyers: [
    {
      id: "b1",
      name: "Apollo Hospitals Enterprise Ltd",
      segment: "Hospital network — institutional",
      annualSalesCr: 312,
      downstreamScope3TCO2e: 42800,
      disclosureCooperationScore: 84,
      dataQuality: "Primary",
      collaborationStatus: "Verified",
      valueChainMapped: true,
      lastReviewed: "2025-10-18",
      risk: "Low",
      primaryCategories: [9, 10, 11],
      dataGaps: [],
      recommendedActions: ["Maintain annual downstream logistics sample from their TMS."],
    },
    {
      id: "b2",
      name: "MedPlus Health Services Ltd",
      segment: "Retail pharmacy chain",
      annualSalesCr: 186,
      downstreamScope3TCO2e: 35200,
      disclosureCooperationScore: 71,
      dataQuality: "Secondary",
      collaborationStatus: "Submitted",
      valueChainMapped: true,
      lastReviewed: "2025-09-05",
      risk: "Medium",
      primaryCategories: [9, 11, 12],
      dataGaps: ["EoL split for blister packs estimated"],
      recommendedActions: ["Request EPR return reconciliation for top SKUs."],
    },
    {
      id: "b3",
      name: "Aster DM Healthcare (India)",
      segment: "Hospital & pharmacy group",
      annualSalesCr: 124,
      downstreamScope3TCO2e: 28900,
      disclosureCooperationScore: 76,
      dataQuality: "Secondary",
      collaborationStatus: "Submitted",
      valueChainMapped: true,
      lastReviewed: "2025-08-22",
      risk: "Medium",
      primaryCategories: [9, 10],
      dataGaps: ["Cold-chain primary data <40% for two hubs"],
      recommendedActions: ["Pilot consolidated reefer reporting template."],
    },
    {
      id: "b4",
      name: "Reliance Retail — Wellness",
      segment: "Modern trade — OTC",
      annualSalesCr: 98,
      downstreamScope3TCO2e: 21400,
      disclosureCooperationScore: 62,
      dataQuality: "Spend-Based",
      collaborationStatus: "Pending",
      valueChainMapped: false,
      lastReviewed: "2025-04-30",
      risk: "High",
      primaryCategories: [9, 11],
      dataGaps: ["No SKU-level sell-through energy model", "Use-phase assumptions only"],
      recommendedActions: ["Escalate via national accounts; propose joint LCA workshop."],
    },
    {
      id: "b5",
      name: "Cipla Health Ltd (distribution JV)",
      segment: "Co-marketing / distribution",
      annualSalesCr: 72,
      downstreamScope3TCO2e: 16800,
      disclosureCooperationScore: 79,
      dataQuality: "Primary",
      collaborationStatus: "Verified",
      valueChainMapped: true,
      lastReviewed: "2025-11-01",
      risk: "Low",
      primaryCategories: [9, 12],
      dataGaps: [],
      recommendedActions: ["Document allocation rule for shared SKUs in BRSR annex."],
    },
    {
      id: "b6",
      name: "Government Medical Stores Org. (Tamil Nadu)",
      segment: "Public sector tender",
      annualSalesCr: 54,
      downstreamScope3TCO2e: 9200,
      disclosureCooperationScore: 55,
      dataQuality: "Secondary",
      collaborationStatus: "Overdue",
      valueChainMapped: false,
      lastReviewed: "2024-11-12",
      risk: "High",
      primaryCategories: [9, 10],
      dataGaps: ["Tender lane emissions desk-only", "No hospital consumption survey"],
      recommendedActions: [
        "Use CPCB + literature proxy for tender lanes; document ±30% uncertainty band in BRSR extended narrative and tie to Category 9–10 workbook version 2025.11.",
      ],
    },
    {
      id: "b7",
      name: "Netmeds Marketplace Ltd",
      segment: "E-pharmacy — last-mile",
      annualSalesCr: 41,
      downstreamScope3TCO2e: 13100,
      disclosureCooperationScore: 68,
      dataQuality: "Secondary",
      collaborationStatus: "Submitted",
      valueChainMapped: true,
      lastReviewed: "2025-07-19",
      risk: "Medium",
      primaryCategories: [9, 11],
      dataGaps: ["Courier mix modeled from national averages"],
      recommendedActions: ["Negotiate anonymised route-level sample for FY26."],
    },
    {
      id: "b8",
      name: "Max Healthcare Institute Ltd",
      segment: "Hospital network — NCR",
      annualSalesCr: 88,
      downstreamScope3TCO2e: 24600,
      disclosureCooperationScore: 81,
      dataQuality: "Primary",
      collaborationStatus: "Verified",
      valueChainMapped: true,
      lastReviewed: "2025-10-28",
      risk: "Low",
      primaryCategories: [10, 11],
      dataGaps: [],
      recommendedActions: ["Refresh Category 11 use-phase assumptions post portfolio change."],
    },
  ],
  rfq: {
    id: "rfq-2026-0142",
    title: "API intermediate — export consignment (evidence-sensitive)",
    commodity: "Inter-X HCl salt — 40 MT",
    dueDate: "2026-02-15",
    responses: [
      { vendorName: "FineChem Intermediates", scope3Score: 78, dataQuality: "Primary", verifiedPct: 88, evidencePackReady: true, notes: "Strong PCF; India plant energy disclosed." },
      { vendorName: "APIchem India Pvt Ltd", scope3Score: 86, dataQuality: "Primary", verifiedPct: 92, evidencePackReady: true, notes: "Best data quality; slightly higher logistics intensity." },
      { vendorName: "ChemLogistics India", scope3Score: 44, dataQuality: "Secondary", verifiedPct: 41, evidencePackReady: false, notes: "Logistics partner risk; evidence pack incomplete." },
      { vendorName: "SynCRO Research Services", scope3Score: 62, dataQuality: "Secondary", verifiedPct: 55, evidencePackReady: false, notes: "CRO pathway irrelevant; included as benchmark error." },
      { vendorName: "SealFlex Export Packaging Pvt Ltd", scope3Score: 81, dataQuality: "Primary", verifiedPct: 90, evidencePackReady: true, notes: "Packaging-only scope; partial relevance." },
      { vendorName: "OceanBulk Chartering", scope3Score: 35, dataQuality: "Spend-Based", verifiedPct: 22, evidencePackReady: false, notes: "Spend-based only; disqualify for domestic award." },
      { vendorName: "GreenSteam Utilities", scope3Score: 58, dataQuality: "Primary", verifiedPct: 72, evidencePackReady: false, notes: "Utilities-only; partial process relevance." },
      { vendorName: "BioSterile Pack", scope3Score: 49, dataQuality: "Secondary", verifiedPct: 48, evidencePackReady: false, notes: "Sterile packaging; not primary for API award." },
    ],
  },
  controls: [
    {
      controlId: "S3-C-01",
      description:
        "Validate supplier-reported activity data and PCFs before they update Category 1–2 inventory positions; retain evidence for assurance.",
      scope3Categories: "Cat. 1, 2",
      linkedSupplierIds: ["s1", "s2", "s4", "s11", "s18"],
      linkedCategoryIds: [1, 2],
      frameworks: ["GHG Protocol", "BRSR", "CDP", "SBTi"],
      owner: "ESG Operations",
      frequency: "Quarterly",
      lastTested: "2025-10-12",
      status: "Effective",
      evidenceLink: "/evidence/s3-c-01-q3-25.zip",
    },
    {
      controlId: "S3-C-02",
      description:
        "Govern emission-factor updates (supplier-specific, secondary, EEIO) with approval, version tagging, and impact analysis on historical Scope 3 totals.",
      scope3Categories: "All categories",
      frameworks: ["GHG Protocol", "BRSR Core", "SEBI LODR"],
      owner: "Climate Accounting",
      frequency: "Annual",
      lastTested: "2025-04-02",
      status: "Partially Effective",
      evidenceLink: "/evidence/s3-c-02-ef-registry.xlsx",
    },
    {
      controlId: "S3-C-03",
      description:
        "Annual board or delegated committee sign-off of Scope 3 organizational boundary, material categories (GHG Protocol), and exclusion rationale.",
      scope3Categories: "Portfolio",
      frameworks: ["GHG Protocol", "BRSR", "SBTi"],
      owner: "Head of Sustainability",
      frequency: "Annual",
      lastTested: "2025-05-18",
      status: "Effective",
      evidenceLink: "/evidence/s3-c-03-boundary-memo.pdf",
    },
    {
      controlId: "S3-C-04",
      description:
        "Embedded emissions for regulated export consignments: supplier attestation, QA of activity data, and linkage to Category 4 / downstream reporting.",
      scope3Categories: "Cat. 4, 9, 12",
      linkedSupplierIds: ["s1", "s8", "s6"],
      linkedCategoryIds: [4, 9, 12],
      frameworks: ["DGFT pilot", "BRSR"],
      owner: "Trade Compliance",
      frequency: "Per shipment",
      lastTested: "2025-11-20",
      status: "Deficient",
      evidenceLink: "/evidence/s3-c-04-export-queue.csv",
    },
    {
      controlId: "S3-C-05",
      description:
        "Procurement governance: ESG and data-quality weighting in RFQs, documented evaluation trail, and alignment with Category 1 supplier engagement policy.",
      scope3Categories: "Cat. 1",
      linkedSupplierIds: ["s1", "s2", "s4", "s5", "s12", "s20"],
      linkedCategoryIds: [1],
      frameworks: ["BRSR", "CDP"],
      owner: "Procurement COE",
      frequency: "Quarterly",
      lastTested: "2025-09-30",
      status: "Effective",
      evidenceLink: "/evidence/s3-c-05-rfq-rubric.pptx",
    },
    {
      controlId: "S3-C-06",
      description:
        "IT general controls over Scope 3 data lake: lineage from raw supplier files through calculation jobs to disclosure tables; segregation of duties for adjustments.",
      scope3Categories: "All categories",
      linkedSupplierIds: ["s1", "s3", "s6", "s17", "s19"],
      linkedCategoryIds: [1, 4, 9],
      frameworks: ["GHG Protocol", "BRSR Core", "SEBI LODR"],
      owner: "IT & Data Governance",
      frequency: "Semi-annual",
      lastTested: "2025-08-14",
      status: "Partially Effective",
      evidenceLink: "/evidence/s3-c-06-lineage-diagram.png",
    },
    {
      controlId: "S3-C-07",
      description:
        "Track and close prior-year limited-assurance findings on Scope 3; evidence of retest before next inventory close.",
      scope3Categories: "Portfolio",
      frameworks: ["BRSR Core", "ISAE 3000 (illustrative)"],
      owner: "Internal Audit",
      frequency: "Annual",
      lastTested: "2025-03-10",
      status: "Effective",
      evidenceLink: "/evidence/s3-c-07-assurance-pbc.pdf",
    },
    {
      controlId: "S3-C-08",
      description:
        "Monthly review of statistical anomaly flags on category and supplier intensity; document management response for audit file.",
      scope3Categories: "All categories",
      linkedSupplierIds: ["s4", "s6", "s12", "s18", "s19"],
      linkedCategoryIds: [1, 4, 9],
      frameworks: ["CDP", "BRSR Core"],
      owner: "ESG Analytics",
      frequency: "Monthly",
      lastTested: "2025-11-01",
      status: "Effective",
      evidenceLink: "/evidence/s3-c-08-anomaly-log.csv",
    },
    {
      controlId: "S3-C-09",
      description:
        "Category 11 use-phase and Category 12 end-of-life assumptions: LCA ownership, peer review, and disclosure of uncertainty bands per GHG Protocol guidance.",
      scope3Categories: "Cat. 11, 12",
      frameworks: ["GHG Protocol", "CDP", "BRSR Core"],
      owner: "Product Sustainability",
      frequency: "Annual",
      lastTested: "2024-12-05",
      status: "Deficient",
      evidenceLink: "/evidence/s3-c-09-usephase-lca.zip",
    },
    {
      controlId: "S3-C-10",
      description:
        "Category 15 financed emissions: PCAF methodology application, data quality scoring, and reconciliation to treasury holdings.",
      scope3Categories: "Cat. 15",
      frameworks: ["GHG Protocol", "CDP", "BRSR Core"],
      owner: "Treasury",
      frequency: "Annual",
      lastTested: "2025-01-22",
      status: "Not Assessed",
      evidenceLink: "/evidence/s3-c-10-pcaf-workbook.xlsx",
    },
    {
      controlId: "S3-C-11",
      description:
        "Category 7 employee commuting: survey design, response-rate checks, and extrapolation methodology signed off for inventory inclusion.",
      scope3Categories: "Cat. 7",
      frameworks: ["GHG Protocol", "BRSR"],
      owner: "HR",
      frequency: "Annual",
      lastTested: "2025-07-01",
      status: "Partially Effective",
      evidenceLink: "/evidence/s3-c-11-commute-survey.pdf",
    },
    {
      controlId: "S3-C-12",
      description:
        "Category 5 waste from operations: manifest completeness, mass-balance to calculated emissions, and reconciliation to third-party disposal records.",
      scope3Categories: "Cat. 5",
      frameworks: ["GHG Protocol", "BRSR"],
      owner: "EHS",
      frequency: "Quarterly",
      lastTested: "2025-10-28",
      status: "Deficient",
      evidenceLink: "/evidence/s3-c-12-waste-rec.xlsx",
    },
  ],
  auditReadiness: {
    overallPct: 73,
    dimensions: [
      {
        key: "completeness",
        label: "Activity & PCF completeness (Scope 3)",
        score: 78,
        status: "Adequate",
        missing:
          "Six supplier PCFs overdue or in clarification; Category 11 LCA peer review outstanding; export consignment evidence incomplete for two API batches (IN-API-0331/0334).",
        recommendedAction:
          "Targeted data collection per GHG Protocol data-quality hierarchy; procurement-led chase list with assurance deadline.",
      },
      {
        key: "methodology",
        label: "Methodology & policy documentation",
        score: 69,
        status: "Adequate",
        missing:
          "Category 11 use-phase LCA governance sign-off pending; allocation rules for co-marketed SKUs (Cipla JV) and joint-plant outputs not fully documented in calculation manual v2025.09.",
        recommendedAction:
          "Publish Scope 3 calculation manual vNext with category owners, uncertainty, and change log for auditors.",
      },
      {
        key: "trail",
        label: "Inventory audit trail & change control",
        score: 81,
        status: "Strong",
        missing: "Minor gaps in cold-chain evidence attachments for Category 9.",
        recommendedAction:
          "Enforce mandatory metadata on uploads; quarterly ITGC sample over adjustment logs affecting Scope 3.",
      },
      {
        key: "factors",
        label: "Emission factor governance",
        score: 66,
        status: "Weak",
        missing: "EEIO factors not uniformly updated to FY25 registry release; regression tests not logged for all categories.",
        recommendedAction:
          "Controlled EF release with signed impact memo and back-casting policy for restated figures.",
      },
      {
        key: "verification",
        label: "Limited / reasonable assurance readiness",
        score: 68,
        status: "Adequate",
        missing: "Export consignment evidence pack incomplete; management representation letter draft not scoped to Scope 3.",
        recommendedAction:
          "Complete PBC list for Scope 3 categories in scope; align narrative disclosures with inventory workbook.",
      },
    ],
    quarterlyTrend: [
      { quarter: "FY24 Q4", score: 64 },
      { quarter: "FY25 Q1", score: 67 },
      { quarter: "FY25 Q2", score: 70 },
      { quarter: "FY25 Q3", score: 73 },
    ],
    dataTraceabilityPct: 76,
    methodologyDocCompletenessPct: 69,
  },
  aiInsights: [
    {
      id: "ai-1",
      severity: "Critical",
      category: "Compliance Gap",
      title: "Export consignment evidence pack incomplete for two API batches",
      detail:
        "DGFT pilot workbook shows missing embedded emissions worksheets and signed supplier attestation for export batches IN-API-0331 and IN-API-0334 (Category 1 + logistics linkage to Cat. 4). Blocks customs carbon evidence narrative until FineChem pack is complete.",
      confidencePct: 91,
      recommendedAction: "Trigger supplier corrective action and hold shipment until pack complete.",
      linkedSupplier: "FineChem Intermediates",
      linkedCategoryId: 1,
      workflow: "Open",
    },
    {
      id: "ai-2",
      severity: "High",
      category: "Supplier Risk",
      title: "ChemLogistics India — overdue GLEC submission",
      detail: "Hazmat transport supplier overdue 74 days on validated emissions submission; affects Category 4 coverage.",
      confidencePct: 88,
      recommendedAction: "Escalate to category owner and restrict new PO awards.",
      linkedSupplier: "ChemLogistics India",
      linkedCategoryId: 4,
      workflow: "Assigned",
      assignee: "Category Owner — Logistics",
    },
    {
      id: "ai-3",
      severity: "High",
      category: "Data Quality",
      title: "Category 11 use-phase uncertainty band exceeds policy threshold",
      detail:
        "Monte Carlo 90% CI width > 45% of the ~196 ktCO₂e point estimate for Category 11; BRSR extended narrative / sensitivity disclosure required alongside S3-C-09 remediation.",
      confidencePct: 84,
      recommendedAction: "Document limitations and planned primary studies for FY26.",
      linkedCategoryId: 11,
      workflow: "Acknowledged",
    },
    {
      id: "ai-4",
      severity: "Medium",
      category: "Reduction Opportunity",
      title: "Cold-chain lane consolidation — Mumbai to Visakhapatnam",
      detail: "Model suggests 8–11 ktCO2e annual saving via consolidated reefer blocks on east-coast lanes without service level drop.",
      confidencePct: 76,
      recommendedAction: "Pilot two consolidated sailings with distributor sign-off.",
      linkedSupplier: "IndoCold Chain Ltd",
      linkedCategoryId: 9,
      workflow: "Open",
    },
    {
      id: "ai-5",
      severity: "Medium",
      category: "Anomaly Detection",
      title: "Spike in Category 6 business travel vs. headcount trend",
      detail: "Travel emissions +11% YoY while headcount +2%; long-haul premium class mix elevated in Q3.",
      confidencePct: 79,
      recommendedAction: "Travel policy review — premium class approvals.",
      linkedCategoryId: 6,
      workflow: "Open",
    },
    {
      id: "ai-6",
      severity: "Medium",
      category: "Supplier Risk",
      title: "PrintCraft Labels — no chain-of-custody for recycled inputs",
      detail: "Impacts BRSR Core packaging KPI credibility for recycled content claims.",
      confidencePct: 81,
      recommendedAction: "Require FSC / recycled content certification in 60 days.",
      linkedSupplier: "PrintCraft Labels",
      linkedCategoryId: 1,
      workflow: "Open",
    },
    {
      id: "ai-7",
      severity: "Low",
      category: "Data Quality",
      title: "Employee commuting survey response gap",
      detail: "Two CRO satellite offices <40% response; commuting model confidence reduced.",
      confidencePct: 72,
      recommendedAction: "Run targeted HR campaign and extend survey window.",
      linkedCategoryId: 7,
      workflow: "Dismissed",
      dismissReason: "Accepted for FY25 with sensitivity footnote.",
    },
    {
      id: "ai-8",
      severity: "Low",
      category: "Reduction Opportunity",
      title: "Increase primary data coverage for downstream logistics",
      detail: "Moving 20% of spend from secondary to primary could improve BRSR Core score by ~4 points.",
      confidencePct: 70,
      recommendedAction: "Add TMS telematics SLA to top 3 downstream 3PLs.",
      linkedSupplier: "FedEx SupplyChain India",
      linkedCategoryId: 9,
      workflow: "Open",
    },
  ],
  reports: [
    {
      id: "r1",
      name: "BRSR Section A — GHG emissions",
      status: "Ready",
      lastGenerated: "2025-11-18",
      nextDeadline: "2026-06-30",
      previewBullets: ["Scope 1–3 totals", "Intensity metrics", "Methodology summary", "Assurance mapping"],
    },
    {
      id: "r2",
      name: "BRSR Core KPI sheet (climate)",
      status: "Incomplete",
      missingFields: ["4 supplier PCFs / attestations", "Export consignment worksheets IN-API-0331/0334"],
      lastGenerated: "2025-10-02",
      nextDeadline: "2026-05-15",
      previewBullets: ["Core KPI table", "Data quality tiers", "Supplier coverage"],
    },
    {
      id: "r3",
      name: "MoEFCC Form IV / state PCB — climate annex (draft)",
      status: "Incomplete",
      missingFields: ["State PCB submission annex", "Use-phase sensitivity narrative"],
      lastGenerated: "2025-09-20",
      nextDeadline: "2026-09-30",
      previewBullets: ["Air emissions summary", "Hazardous waste linkage", "GHG assumptions"],
    },
    {
      id: "r4",
      name: "CDP Climate questionnaire extract",
      status: "Ready",
      lastGenerated: "2025-11-10",
      nextDeadline: "2026-07-26",
      previewBullets: ["C6.1–C6.10 supply chain", "Verification status", "Targets linkage"],
    },
    {
      id: "r5",
      name: "India export consignment — embedded emissions workbook",
      status: "Incomplete",
      missingFields: ["Embedded emissions for IN-API-0331/0334"],
      nextDeadline: "2026-01-31",
      previewBullets: ["ITC-HS codes", "Specific embedded emissions", "Supplier attestations"],
    },
    {
      id: "r6",
      name: "SBTi progress report",
      status: "Ready",
      lastGenerated: "2025-08-30",
      nextDeadline: "2026-03-31",
      previewBullets: ["Near-term target trajectory", "Scope 3 breakdown", "FLAG status"],
    },
  ],
  reductionOpportunities: [
    { id: "ro1", title: "Supplier PCF program expansion (long-tail)", categoryId: 1, estimatedSavingTCO2e: 42000, effort: "Medium" },
    { id: "ro2", title: "Green electricity in upstream leased warehouses", categoryId: 8, estimatedSavingTCO2e: 6200, effort: "Low" },
    { id: "ro3", title: "Packaging light-weighting + recycled resin", categoryId: 12, estimatedSavingTCO2e: 18500, effort: "Medium" },
    { id: "ro4", title: "Cold-chain consolidation (India coastal lanes)", categoryId: 9, estimatedSavingTCO2e: 9500, effort: "High" },
    { id: "ro5", title: "Logistics mode shift (air to rail for domestic)", categoryId: 4, estimatedSavingTCO2e: 12800, effort: "Medium" },
  ],
  anomalies: [
    {
      id: "an1",
      entity: "CryoLab Consumables Pvt Ltd",
      metric: "Cat. 1 intensity — tCO₂e / INR Cr spend",
      zScore: 3.1,
      note: "Scope 3 screening flag: intensity outlier vs. lab consumables peer cluster; may indicate mis-mapped activity or EF tier drift.",
    },
    {
      id: "an2",
      entity: "Category 6 — Business travel",
      metric: "YoY % change vs. FY24 inventory",
      zScore: 2.6,
      note: "Governance review suggested: reconcile travel system accruals with GHG inventory boundary before assurance fieldwork.",
    },
    {
      id: "an3",
      entity: "OceanBulk Chartering",
      metric: "Cat. 4 upstream logistics — data timeliness",
      zScore: -2.9,
      note: "Supplier engagement risk: late submissions weaken Category 4 documentation for limited assurance.",
    },
    {
      id: "an4",
      entity: "Category 11 — use of sold products",
      metric: "Sensitivity band vs. FY24 inventory",
      zScore: 2.4,
      note: "Use-phase point estimate reduced following Rx portfolio mix update; uncertainty band still wide — aligns with ai-3 and S3-C-09 deficiency until LCA peer review closes.",
    },
  ],
  lineage: [
    {
      step: 1,
      label: "Supplier & operations evidence capture",
      detail:
        "Category-level source files (PCFs, audited energy, TMS extracts, utility bills, waste manifests, travel bookings) land in the governed data room with checksum registration; supplier portal uploads auto-route to QA queues with SLA timers tied to procurement tier.",
    },
    {
      step: 2,
      label: "QA, mapping & emission factor tiering",
      detail:
        "Activities mapped to GHG Protocol Scope 3 categories 1–15 with approver sign-off; supplier-specific factors preferred, India secondary factors second, EEIO only where documented in the EF registry lock (v2025.09) with peer review for material lines.",
    },
    {
      step: 3,
      label: "Controlled calculation run",
      detail:
        "Activity × EF in the locked calculation engine; allocation rules (mass, economic, revenue) versioned per SKU family; GWP AR6 100-yr applied consistently; job IDs and parquet hashes stored for auditor re-performance and BRSR traceability.",
    },
    {
      step: 4,
      label: "Management review & governance sign-off",
      detail:
        "ESG, finance, and category owners review variances vs. prior year and vs. SBTi trajectory; deficient controls (S3-C-04, S3-C-09, S3-C-12) escalated with dated remediation owners before inventory lock memo.",
    },
    {
      step: 5,
      label: "Disclosure packages & assurance interface",
      detail:
        "Exports to BRSR Section A / Core, CDP C6, SBTi FLAG annex, and DGFT pilot consignment workbooks; PBC index links each disclosure line to evidence IDs, control IDs, and (where applicable) AI insight or compliance alert IDs for third-party review.",
    },
  ],
  submittedEvidences: [
    {
      id: "EV-2025-0142",
      title: "FY25 product carbon footprint (PCF) — paracetamol API grade",
      submittedAt: "2025-10-28T09:14:00+05:30",
      indexedAt: "2025-10-28T11:02:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "APIchem India Pvt Ltd",
      submitterRole: "VP Quality & ESG",
      supplierId: "s1",
      scope3CategoryIds: [1, 2],
      linkedControlIds: ["S3-C-01", "S3-C-05"],
      disclosureUse: ["CDP Scope 3", "BRSR Principle 6", "Internal Cat. 1 workbook"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "ESG Operations — QA",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Cradle-to-gate PCF for paracetamol API (site: Dahej) using primary electricity and steam splits; allocation for co-manufactured co-product per mass; GWP AR6 applied in model v4.2.",
      verificationFocus:
        "Reconcile PCF functional unit to purchase orders SP-AP-2025-Q3; confirm EF versions match locked registry 2025-09; spot-check two shipment lots against weighbridge logs.",
      artifacts: [
        {
          fileName: "APIchem_PCF_paracetamol_FY25.pdf",
          format: "PDF",
          sizeLabel: "4.1 MB",
          sha256Prefix: "a3f91c8e2b10",
          contentSummary: "Third-party-reviewed PCF 48 pp. — system boundary cradle-to-gate Dahej; includes sensitivity table for grid vs. market-based electricity.",
        },
        { fileName: "Dahej_electricity_RE_cert_bundle.zip", format: "ZIP", sizeLabel: "1.2 MB", sha256Prefix: "7d2044aa91fe" },
        { fileName: "allocation_memo_comanufacture.xlsx", format: "XLSX", sizeLabel: "820 KB", sha256Prefix: "c90122bb44aa" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0160",
      title: "ISCC PLUS certificate & mass-balance claim — recycled PP stream",
      submittedAt: "2025-11-02T16:40:00+05:30",
      indexedAt: "2025-11-03T08:55:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "PackWell Polymers Ltd",
      submitterRole: "Sustainability lead",
      supplierId: "s2",
      scope3CategoryIds: [1, 12],
      linkedControlIds: ["S3-C-01", "S3-C-05"],
      disclosureUse: ["BRSR extended producer responsibility annex", "CDP plastics module"],
      intendedDataQualityTier: "Primary",
      reviewState: "Clarification requested",
      reviewer: "Climate Accounting",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Claims 42% post-consumer recycled PP for blister-grade resin; provides ISCC PLUS scope certificate and conversion factors for mass balance.",
      verificationFocus:
        "Certificate scope must explicitly cover SKU families on PO PW-2025-1180–1194; need chain-of-custody lot trace for Q3 production week 40–44.",
      artifacts: [
        { fileName: "ISCC_PLUS_certificate_2025-2028.pdf", format: "PDF", sizeLabel: "1.1 MB", sha256Prefix: "e44102ab19cd" },
        { fileName: "mass_balance_PP_stream_Q3.xlsx", format: "XLSX", sizeLabel: "640 KB", sha256Prefix: "22b8ee6610aa" },
      ],
      lineageStep: 1,
      linkedEsgRequestId: "esg-req-001",
    },
    {
      id: "EV-2025-0098",
      title: "GLEC Framework conformity statement + fuel data extract (domestic linehaul)",
      submittedAt: "2025-09-14T11:22:00+05:30",
      indexedAt: "2025-09-15T09:30:00+05:30",
      channel: "Secure SFTP / data room",
      submitterOrg: "BlueDart-GreenFreight JV",
      submitterRole: "Network sustainability",
      supplierId: "s3",
      scope3CategoryIds: [4, 9],
      linkedControlIds: ["S3-C-06", "S3-C-08"],
      disclosureUse: ["Cat. 4 logistics inventory", "BRSR logistics narrative"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "ESG Analytics",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Provides GLEC-aligned emission factors per tonne-km by vehicle class for FY25 domestic network; includes diesel CNG blend shares by hub.",
      verificationFocus:
        "Match extract primary keys to TMS shipment IDs in data lake; verify empty running correction methodology unchanged from FY24 memo.",
      artifacts: [
        { fileName: "GLEC_conformity_statement_FY25_signed.pdf", format: "PDF", sizeLabel: "2.4 MB", sha256Prefix: "91aa4455cc01" },
        { fileName: "fuel_and_distance_extract_FY25.csv", format: "CSV", sizeLabel: "18 MB", sha256Prefix: "55fe102233ab" },
      ],
      lineageStep: 2,
    },
    {
      id: "EV-2025-0211",
      title: "Hazmat FTL weight tickets + diesel purchase invoices (partial fleet)",
      submittedAt: "2025-11-18T08:05:00+05:30",
      indexedAt: "2025-11-18T14:40:00+05:30",
      channel: "Email + checksum registry",
      submitterOrg: "ChemLogistics India",
      submitterRole: "Fleet compliance",
      supplierId: "s6",
      scope3CategoryIds: [4],
      linkedControlIds: ["S3-C-04", "S3-C-08"],
      disclosureUse: ["Cat. 4 hazmat lane workbook", "Export consignment support"],
      intendedDataQualityTier: "Secondary",
      reviewState: "Under review",
      reviewer: "Trade Compliance",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Submitter asserts primary weight capture for 62% of hazmat FTL km; remainder uses fleet-average DEFRA-based factors pending full telematics rollout.",
      verificationFocus:
        "Cross-check invoice periods to trip manifests; confirm driver training evidence pack referenced in S3-C-06 remediation plan is attached or still outstanding.",
      artifacts: [
        { fileName: "weight_tickets_Oct2025_redacted.pdf", format: "PDF", sizeLabel: "6.8 MB", sha256Prefix: "bb9012cc77de" },
        { fileName: "diesel_purchase_register_oct.csv", format: "CSV", sizeLabel: "410 KB", sha256Prefix: "09aa6677ee11" },
      ],
      lineageStep: 1,
      linkedEsgRequestId: "esg-req-003",
    },
    {
      id: "EV-2025-0188",
      title: "Export consignment embedded emissions worksheet — batch IN-API-0328",
      submittedAt: "2025-10-30T13:50:00+05:30",
      indexedAt: "2025-10-30T15:10:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "SealFlex Export Packaging Pvt Ltd",
      supplierId: "s8",
      scope3CategoryIds: [4, 9, 12],
      linkedControlIds: ["S3-C-04"],
      disclosureUse: ["DGFT pilot embedded emissions", "BRSR value chain"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "Trade Compliance",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Pack-level mass and laminate EF tied to APIchem PCF for batch IN-API-0328; includes supplier attestation per customs pilot template v3.",
      verificationFocus:
        "Validate CN code mapping and moisture barrier film SKU against BOM; confirm ICEGATE reference numbers align with logistics TMS gate-out timestamps.",
      artifacts: [
        { fileName: "embedded_emissions_IN-API-0328.xlsx", format: "XLSX", sizeLabel: "540 KB", sha256Prefix: "33c1ff90ab45" },
        { fileName: "supplier_attestation_IN-API-0328.pdf", format: "PDF", sizeLabel: "720 KB", sha256Prefix: "de441200aa99" },
      ],
      lineageStep: 2,
    },
    {
      id: "EV-2025-0110",
      title: "Joint-plant output allocation — mass-based statement (intermediates)",
      submittedAt: "2025-09-01T10:00:00+05:30",
      indexedAt: "2025-09-02T16:20:00+05:30",
      channel: "Secure SFTP / data room",
      submitterOrg: "FineChem Intermediates",
      supplierId: "s11",
      scope3CategoryIds: [1],
      linkedControlIds: ["S3-C-01"],
      disclosureUse: ["Cat. 1 allocation register"],
      intendedDataQualityTier: "Primary",
      reviewState: "Under review",
      reviewer: "Climate Accounting",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Signed letter from plant director allocating joint reactor output to your purchase contracts FC-7781–7790 using certified mass yields.",
      verificationFocus:
        "Independent recalculation of allocation keys vs. stoichiometry in process brief; confirm boundary includes shared utilities per GHG Protocol corporate standard guidance.",
      artifacts: [
        { fileName: "allocation_statement_joint_plant_FY25.pdf", format: "PDF", sizeLabel: "1.0 MB", sha256Prefix: "aa118899ccff" },
        { fileName: "mass_yield_supporting_lab.csv", format: "CSV", sizeLabel: "95 KB", sha256Prefix: "441199aabb22" },
      ],
      lineageStep: 2,
    },
    {
      id: "EV-2025-0077",
      title: "CRO study energy — client-specific allocation memo (analytical services)",
      submittedAt: "2025-08-22T15:30:00+05:30",
      indexedAt: "2025-08-23T09:00:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "SynCRO Research Services",
      supplierId: "s5",
      scope3CategoryIds: [1, 6],
      linkedControlIds: ["S3-C-01"],
      disclosureUse: ["Cat. 1 services spend", "Cat. 6 professional services"],
      intendedDataQualityTier: "Secondary",
      reviewState: "Indexed — accepted",
      reviewer: "ESG Operations — QA",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Allocates site electricity and refrigerant losses to SunPharma contract portfolio using time-on-project and fume hood hours; includes ISO 50001 audit excerpt.",
      verificationFocus:
        "Confirm allocation denominator matches contracted FTE in MSA Schedule B; verify refrigerant GWP set matches inventory locked AR6 table.",
      artifacts: [
        { fileName: "SynCRO_client_allocation_memo_FY25.pdf", format: "PDF", sizeLabel: "2.1 MB", sha256Prefix: "66aa00ff11cc" },
        { fileName: "ISO50001_audit_excerpt_2024.pdf", format: "PDF", sizeLabel: "3.0 MB", sha256Prefix: "ff0099aa4455" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0055",
      title: "Industrial steam invoices + condensate return meter log",
      submittedAt: "2025-10-30T08:00:00+05:30",
      indexedAt: "2025-10-30T12:45:00+05:30",
      channel: "Secure SFTP / data room",
      submitterOrg: "GreenSteam Utilities",
      supplierId: "s7",
      scope3CategoryIds: [3],
      linkedControlIds: ["S3-C-06"],
      disclosureUse: ["Cat. 3 steam purchased", "BRSR energy"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "Climate Accounting",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Mass balance for steam delivered to Vadodara formulation campus; condensate return credited per contract clause 14.b.",
      verificationFocus:
        "Meter calibration certificates within 12 months; align invoice MWh to mass balance closure in S3-C-06 ITGC sample list.",
      artifacts: [
        { fileName: "steam_invoices_FY25_Q1-Q3.pdf", format: "PDF", sizeLabel: "5.2 MB", sha256Prefix: "10feed99aa00" },
        { fileName: "condensate_return_meters.csv", format: "CSV", sizeLabel: "120 KB", sha256Prefix: "aa00bb11cc22" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0203",
      title: "Reefer hub electricity splits — top 5 cold stores (estimated mix disclosure)",
      submittedAt: "2025-06-09T18:00:00+05:30",
      indexedAt: "2025-06-10T10:15:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "IndoCold Chain Ltd",
      supplierId: "s9",
      scope3CategoryIds: [4, 9],
      linkedControlIds: ["S3-C-08"],
      disclosureUse: ["Cat. 4 & 9 cold chain narrative"],
      intendedDataQualityTier: "Secondary",
      reviewState: "Clarification requested",
      reviewer: "ESG Analytics",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Provides estimated grid vs. diesel generator split for reefer plugs at five hubs; includes temperature logger integrity statement.",
      verificationFocus:
        "Require metered splits or utility bills for hubs representing ≥80% of tonne-km; document uncertainty band used in inventory sensitivity table.",
      artifacts: [
        { fileName: "reefer_electricity_estimate_FY25.xlsx", format: "XLSX", sizeLabel: "380 KB", sha256Prefix: "badcafe00123" },
        { fileName: "logger_integrity_statement.pdf", format: "PDF", sizeLabel: "600 KB", sha256Prefix: "cafe00123456" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0033",
      title: "I-REC retirement statements — captive solar PPA cohort",
      submittedAt: "2025-10-12T09:00:00+05:30",
      indexedAt: "2025-10-12T10:30:00+05:30",
      channel: "Internal — ESG / Finance",
      submitterOrg: "Sun Pharma Research Ltd",
      submitterRole: "Treasury & ESG",
      scope3CategoryIds: [3],
      linkedControlIds: ["S3-C-02", "S3-C-03"],
      disclosureUse: ["CDP market-based scope 2 linkage", "BRSR energy"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "Head of Sustainability",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Retirement of 42 GWh I-RECs tied to SolarEdge PPA contract IDs; applied to market-based reporting for purchased electricity in Scope 2 memo and supporting Scope 3 Cat. 3 narrative.",
      verificationFocus:
        "Vintage and geography eligibility vs. GHG Protocol Scope 2 quality criteria; no double counting vs. supplier invoices already in Cat. 3 steam model.",
      artifacts: [
        { fileName: "I_REC_retirement_bundle_FY25.zip", format: "ZIP", sizeLabel: "2.0 MB", sha256Prefix: "001122334455" },
        { fileName: "PPA_contract_register_redacted.xlsx", format: "XLSX", sizeLabel: "290 KB", sha256Prefix: "66778899aabb" },
      ],
      lineageStep: 2,
    },
    {
      id: "EV-2025-0124",
      title: "Emission factor registry lock — v2025.09 + impact memo",
      submittedAt: "2025-09-30T17:00:00+05:30",
      indexedAt: "2025-10-01T09:00:00+05:30",
      channel: "Internal — ESG / Finance",
      submitterOrg: "Sun Pharma Research Ltd",
      submitterRole: "Climate Accounting",
      scope3CategoryIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15],
      linkedControlIds: ["S3-C-02"],
      disclosureUse: ["Inventory calculation engine", "Assurance PBC"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "IT & Data Governance",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Signed release of EF registry v2025.09 with GWP AR6 mapping; includes regression test summary for top 40 Scope 3 activity classes.",
      verificationFocus:
        "Hash of deployed parquet matches attachment; approver segregation per S3-C-06 change-control matrix.",
      artifacts: [
        { fileName: "EF_registry_v2025_09_manifest.xml", format: "XML", sizeLabel: "88 KB", sha256Prefix: "abcdef001122" },
        { fileName: "EF_release_impact_memo.pdf", format: "PDF", sizeLabel: "1.4 MB", sha256Prefix: "fedcba998877" },
      ],
      lineageStep: 3,
    },
    {
      id: "EV-2024-0990",
      title: "Board-approved organizational boundary & category inclusion memo",
      submittedAt: "2024-05-18T12:00:00+05:30",
      indexedAt: "2024-05-20T09:00:00+05:30",
      channel: "Assurance PBC bundle",
      submitterOrg: "Sun Pharma Research Ltd",
      submitterRole: "Company Secretary office",
      scope3CategoryIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15],
      linkedControlIds: ["S3-C-03"],
      disclosureUse: ["BRSR boundary", "CDP organizational boundary"],
      intendedDataQualityTier: "Primary",
      reviewState: "Superseded by resubmission",
      reviewer: "Head of Sustainability",
      reportingPeriodLabel: "FY24",
      assertionSummary:
        "FY24 memo — superseded by FY25 refresh EV-2025-0301 after JV restructuring; retained for audit trail linkage.",
      verificationFocus:
        "Historical reference only; ensure inventory system marks downstream logistics JV inclusion effective FY25 Q2.",
      artifacts: [
        { fileName: "boundary_memo_FY24_board_signed.pdf", format: "PDF", sizeLabel: "3.2 MB", sha256Prefix: "112233445566" },
      ],
      lineageStep: 4,
    },
    {
      id: "EV-2025-0301",
      title: "FY25 organizational boundary refresh (post-JV logistics inclusion)",
      submittedAt: "2025-05-19T09:30:00+05:30",
      indexedAt: "2025-05-19T14:00:00+05:30",
      channel: "Internal — ESG / Finance",
      submitterOrg: "Sun Pharma Research Ltd",
      submitterRole: "Head of Sustainability",
      scope3CategoryIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15],
      linkedControlIds: ["S3-C-03"],
      disclosureUse: ["BRSR boundary", "Inventory lock package"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "Internal Audit",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Updates operational control narrative for downstream logistics JV; explicit inclusion of FedEx SupplyChain India flows in Cat. 9.",
      verificationFocus:
        "Cross-check JV operational control tests with legal opinion attachment; confirm category materiality table updated in disclosure workbook.",
      artifacts: [
        { fileName: "boundary_memo_FY25_refresh_signed.pdf", format: "PDF", sizeLabel: "4.0 MB", sha256Prefix: "998877665544" },
        { fileName: "legal_opinion_logistics_JV.pdf", format: "PDF", sizeLabel: "2.2 MB", sha256Prefix: "554433221100" },
      ],
      lineageStep: 4,
    },
    {
      id: "EV-2025-0088",
      title: "Limited assurance finding closure — Cat. 4 evidence attachments",
      submittedAt: "2025-03-12T11:00:00+05:30",
      indexedAt: "2025-03-15T10:00:00+05:30",
      channel: "Assurance PBC bundle",
      submitterOrg: "Sun Pharma Research Ltd",
      submitterRole: "Internal Audit",
      scope3CategoryIds: [4],
      linkedControlIds: ["S3-C-07"],
      disclosureUse: ["Assurance working papers"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "Internal Audit",
      reportingPeriodLabel: "FY24 → FY25",
      assertionSummary:
        "Retest evidence for prior-year finding CL-23-Scope3-04; attaches cold-chain attachment remediation pack and sign-off from ESG Operations.",
      verificationFocus:
        "Link closure IDs to S3-C-07 register row; confirm all attachments hashed in evidence index before FY25 lock.",
      artifacts: [
        { fileName: "finding_closure_CL-23-Scope3-04.pdf", format: "PDF", sizeLabel: "1.8 MB", sha256Prefix: "aabbccddeeff" },
      ],
      lineageStep: 5,
    },
    {
      id: "EV-2025-0224",
      title: "EO sterilization emissions study (facility-level) — draft",
      submittedAt: "2025-11-25T14:20:00+05:30",
      indexedAt: "2025-11-25T16:00:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "BioSterile Pack",
      supplierId: "s18",
      scope3CategoryIds: [1, 12],
      linkedControlIds: ["S3-C-01", "S3-C-09"],
      disclosureUse: ["Cat. 12 packaging sterilisation"],
      intendedDataQualityTier: "Secondary",
      reviewState: "Under review",
      reviewer: "Product Sustainability",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Draft LCA-based EO emission factors per pallet type; submitter notes peer review pending from external consultant.",
      verificationFocus:
        "Cannot support primary tier until peer review complete; hold inventory line at secondary proxy per data-quality hierarchy until sign-off.",
      artifacts: [
        { fileName: "EO_study_draft_v0.4.pdf", format: "PDF", sizeLabel: "8.4 MB", sha256Prefix: "deadbeef00aa" },
        { fileName: "supporting_emissions_model.xlsx", format: "XLSX", sizeLabel: "2.9 MB", sha256Prefix: "00aabbccddee" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0350",
      title: "Site electricity & diesel backup — lab consumables mfg (FY25 Q1–Q3)",
      submittedAt: "2025-11-05T10:00:00+05:30",
      indexedAt: "2025-11-06T09:15:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "CryoLab Consumables Pvt Ltd",
      submitterRole: "Plant controller",
      supplierId: "s4",
      scope3CategoryIds: [1],
      linkedControlIds: ["S3-C-01", "S3-C-06"],
      disclosureUse: ["Cat. 1 supplier-specific energy", "Assurance PBC — supplier responses"],
      intendedDataQualityTier: "Secondary",
      reviewState: "Under review",
      reviewer: "ESG Operations — QA",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Monthly kWh and diesel gen-set litres for Bengaluru plant; submitter states renewable share not yet third-party verified.",
      verificationFocus:
        "Until RE verification attached, cap tier at Secondary; reconcile gen-set hours to production output for sampled SKUs.",
      artifacts: [
        { fileName: "CryoLab_energy_Q1-Q3_FY25.xlsx", format: "XLSX", sizeLabel: "410 KB", sha256Prefix: "50feedaa1122" },
        { fileName: "diesel_gen_log_redacted.pdf", format: "PDF", sizeLabel: "2.1 MB", sha256Prefix: "60aabbccddee" },
      ],
      lineageStep: 1,
      linkedEsgRequestId: "esg-req-002",
    },
    {
      id: "EV-2025-0351",
      title: "IMO DCS fuel reports + voyage summaries (selected deep-sea legs)",
      submittedAt: "2025-10-01T12:00:00+05:30",
      indexedAt: "2025-10-02T08:00:00+05:30",
      channel: "Email + checksum registry",
      submitterOrg: "OceanBulk Chartering",
      supplierId: "s19",
      scope3CategoryIds: [4, 9],
      linkedControlIds: ["S3-C-08"],
      disclosureUse: ["Cat. 4 ocean freight workbook"],
      intendedDataQualityTier: "Primary",
      reviewState: "Clarification requested",
      reviewer: "ESG Analytics",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Partial IMO Data Collection System extracts for 11 voyages; submitter withheld remainder pending charterer legal clearance.",
      verificationFocus:
        "Complete voyage population for SunPharma-linked cargoes or document defensible extrapolation with uncertainty table.",
      artifacts: [
        { fileName: "IMO_DCS_extract_sample_Q3.csv", format: "CSV", sizeLabel: "240 KB", sha256Prefix: "71bbccddeeff" },
        { fileName: "voyage_summary_notes.pdf", format: "PDF", sizeLabel: "900 KB", sha256Prefix: "82ccddeeff00" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0352",
      title: "FSC chain-of-custody — carton inserts (virgin fibre stream)",
      submittedAt: "2025-08-30T14:00:00+05:30",
      indexedAt: "2025-08-31T10:00:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "PrintCraft Labels",
      supplierId: "s12",
      scope3CategoryIds: [1, 12],
      linkedControlIds: ["S3-C-01", "S3-C-05"],
      disclosureUse: ["BRSR Principle 6 — packaging", "CDP forests"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "Climate Accounting",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "FSC certificate covers insert grades PC-INS-220 to PC-INS-245; mass balance certificates for two mills.",
      verificationFocus:
        "Match FSC licence code to FSC public register snapshot dated submission week; confirm tonnes tie to PO receipts.",
      artifacts: [
        { fileName: "FSC_CoC_certificate_2025-2027.pdf", format: "PDF", sizeLabel: "1.3 MB", sha256Prefix: "93ddeeff0011" },
        { fileName: "mill_mass_balance_Q2.xlsx", format: "XLSX", sizeLabel: "330 KB", sha256Prefix: "a4eeff001122" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0353",
      title: "Hazardous waste manifests + third-party incinerator stack test summary",
      submittedAt: "2025-05-21T09:00:00+05:30",
      indexedAt: "2025-05-22T11:30:00+05:30",
      channel: "Secure SFTP / data room",
      submitterOrg: "Metro Waste Solutions",
      supplierId: "s10",
      scope3CategoryIds: [5],
      linkedControlIds: ["S3-C-12"],
      disclosureUse: ["Cat. 5 waste from operations"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "EHS liaison — ESG",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Quarterly manifests for solvent wastes routed to RCRA-equivalent incineration; stack test NOx / CO limits attached for primary facility.",
      verificationFocus:
        "Mass closure to Cat. 5 calculation sheet; confirm destruction efficiency factors match methodology memo v2.1.",
      artifacts: [
        { fileName: "waste_manifests_Q1-Q2_FY25.pdf", format: "PDF", sizeLabel: "7.2 MB", sha256Prefix: "b5ff00112233" },
        { fileName: "stack_test_summary_2024.pdf", format: "PDF", sizeLabel: "1.6 MB", sha256Prefix: "c60011223344" },
      ],
      lineageStep: 1,
    },
    {
      id: "EV-2025-0354",
      title: "FLAG screening questionnaire + satellite deforestation risk screen (excipients)",
      submittedAt: "2025-08-04T16:00:00+05:30",
      indexedAt: "2025-08-05T09:00:00+05:30",
      channel: "Supplier portal",
      submitterOrg: "AgriFeed Organics",
      supplierId: "s20",
      scope3CategoryIds: [1],
      linkedControlIds: ["S3-C-01", "S3-C-05"],
      disclosureUse: ["SBTi FLAG annex", "CDP forests"],
      intendedDataQualityTier: "Secondary",
      reviewState: "Under review",
      reviewer: "Product Sustainability",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Supplier-provided FLAG tool output for maize starch sourcing basins; includes commodity codes and land-use change proxy.",
      verificationFocus:
        "Validate commodity scope vs. actual purchase invoices; escalate if basin overlap with protected areas per internal red-list.",
      artifacts: [
        { fileName: "FLAG_screening_agrifeed_v2.xlsx", format: "XLSX", sizeLabel: "1.1 MB", sha256Prefix: "d71122334455" },
        { fileName: "satellite_risk_map_appendix.pdf", format: "PDF", sizeLabel: "4.4 MB", sha256Prefix: "e82233445566" },
      ],
      lineageStep: 2,
    },
    {
      id: "EV-2025-0355",
      title: "TMS shipment-level extract — DC to hospital lanes (anonymised ship-to)",
      submittedAt: "2025-09-28T07:30:00+05:30",
      indexedAt: "2025-09-28T19:00:00+05:30",
      channel: "Secure SFTP / data room",
      submitterOrg: "FedEx SupplyChain India",
      supplierId: "s17",
      scope3CategoryIds: [9],
      linkedControlIds: ["S3-C-06", "S3-C-08"],
      disclosureUse: ["Cat. 9 downstream transport", "BRSR logistics"],
      intendedDataQualityTier: "Primary",
      reviewState: "Indexed — accepted",
      reviewer: "ESG Analytics",
      reportingPeriodLabel: "FY25",
      assertionSummary:
        "Primary telematics-backed distance and weight for 38% of contracted lanes; remainder modelled using hub-to-hub averages with documented QA rules.",
      verificationFocus:
        "Reconcile anonymisation salt to internal master patient-data policy; extend sample to meet S3-C-06 SLA for FY26 lock if coverage < 50%.",
      artifacts: [
        { fileName: "TMS_lane_extract_FY25_ytd.zip", format: "ZIP", sizeLabel: "24 MB", sha256Prefix: "f93344556677" },
        { fileName: "QA_rules_lane_fill.pdf", format: "PDF", sizeLabel: "480 KB", sha256Prefix: "0a4455667788" },
      ],
      lineageStep: 2,
    },
  ],
  pendingEsgRequests: [
    {
      id: "esg-req-001",
      supplierId: "s2",
      supplierName: "PackWell Polymers Ltd",
      requestedFields: ["emissions_data", "certifications", "lifecycle_data"],
      requesterNote:
        "Please provide FY25 Q1–Q3 site electricity (market-based) for Dahej + Vadodara lines, and cradle-to-gate PCF for recycled PP grades used in PO PW-2025-1180–1194 (Excel + PDF).",
      status: "Acknowledged",
      dueBy: "2026-01-22",
      createdAt: "2025-12-10",
    },
    {
      id: "esg-req-002",
      supplierId: "s4",
      supplierName: "CryoLab Consumables Pvt Ltd",
      requestedFields: ["emissions_data", "energy_usage"],
      status: "Sent",
      dueBy: "2026-02-01",
      createdAt: "2025-12-15",
    },
    {
      id: "esg-req-003",
      supplierId: "s6",
      supplierName: "ChemLogistics India",
      requestedFields: ["emissions_data", "certifications", "energy_usage", "lifecycle_data"],
      status: "Partial response",
      dueBy: "2025-12-28",
      createdAt: "2025-11-20",
    },
  ],
  procurementGmInsights: [
    {
      id: "pgm-1",
      severity: "High",
      category: "Procurement Intelligence",
      title: "Top Category 1 contributors by attributed tCO₂e",
      detail:
        "APIchem India Pvt Ltd, FineChem Intermediates, and BlueDart-GreenFreight JV together drive ~24% of upstream-attributed tCO₂e in Category 1 and logistics-heavy flows; sequencing PCF refresh + GLEC data before FY26 lock de-risks assurance fees and procurement renegotiation.",
      confidencePct: 86,
      recommendedAction: "Sequence supplier workshops before inventory lock; align with S3-C-01 and S3-C-05 control tests.",
      linkedSupplier: "APIchem India Pvt Ltd",
      linkedCategoryId: 1,
      workflow: "Open",
      assignee: "Procurement GM",
    },
    {
      id: "pgm-2",
      severity: "Medium",
      category: "Procurement Intelligence",
      title: "Cost vs. emission trade-off — spend reallocation lever",
      detail:
        "Spend-based positions on OceanBulk Chartering and PrintCraft Labels carry lower unit cost visibility but widen uncertainty bands vs. primary-data lanes; shifting 8–12% volume to verified partners could reduce inventory risk with bounded cost impact.",
      confidencePct: 74,
      recommendedAction: "Run dual-source RFQ with minimum verified-data gate per GHG Protocol data-quality hierarchy.",
      linkedSupplier: "OceanBulk Chartering",
      linkedCategoryId: 4,
      workflow: "Open",
      assignee: "Procurement GM",
    },
    {
      id: "pgm-3",
      severity: "Critical",
      category: "Procurement Intelligence",
      title: "Suppliers missing BRSR-aligned ESG disclosures",
      detail:
        "CryoLab Consumables, ChemLogistics India, OceanBulk Chartering, and BioSterile Pack show overdue or unmapped submissions — weakens Category 1 / 4 assurance trail for limited review.",
      confidencePct: 91,
      recommendedAction: "Issue consolidated Scope 3 data request pack; escalate high-priority suppliers to joint ESG–procurement review.",
      linkedSupplier: "ChemLogistics India",
      workflow: "Assigned",
      assignee: "ESG Operations",
    },
  ],
  complianceAlerts: [
    {
      id: "ca1",
      severity: "critical",
      title: "Export consignment — two API batches missing embedded emissions",
      detail: "IN-API-0331 and IN-API-0334 require supplier attestation and worksheet upload before the DGFT pilot deadline.",
      due: "2026-01-18",
      actionLabel: "Open AI insight",
      target: "ai",
    },
    {
      id: "ca2",
      severity: "warning",
      title: "BRSR Core — four supplier PCFs / attestations outstanding",
      detail:
        "CryoLab Consumables, ChemLogistics India, OceanBulk Chartering, and BioSterile Pack remain below Core KPI policy until verified PCFs or equivalent primary packs are indexed.",
      due: "2026-05-01",
      actionLabel: "Review suppliers",
      target: "supplier",
      supplierName: "CryoLab Consumables Pvt Ltd",
    },
    {
      id: "ca3",
      severity: "warning",
      title: "Category 11 — use-phase uncertainty exceeds disclosure policy",
      detail: "BRSR extended narrative required; LCA governance sign-off pending.",
      due: "2026-02-28",
      actionLabel: "Open category",
      target: "category",
      categoryId: 11,
    },
    {
      id: "ca4",
      severity: "warning",
      title: "Logistics supplier — GLEC submission overdue",
      detail: "ChemLogistics India affects Category 4 assurance boundary.",
      due: "2025-12-31",
      actionLabel: "Open supplier",
      target: "supplier",
      supplierName: "ChemLogistics India",
    },
    {
      id: "ca5",
      severity: "info",
      title: "Control S3-C-04 — export consignment evidence control deficient",
      detail: "Last test identified missing per-shipment evidence chain; remediation in progress.",
      due: "2026-01-10",
      actionLabel: "Controls register",
      target: "controls",
    },
    {
      id: "ca6",
      severity: "info",
      title: "CDP C6 — procurement sign-off pending",
      detail: "Supply chain module awaiting Procurement GM attestation on Category 1 engagement metrics.",
      due: "2026-06-01",
      actionLabel: "Reporting center",
      target: "reports",
    },
    {
      id: "ca7",
      severity: "info",
      title: "FLAG screening — excipient supplier incomplete",
      detail: "AgriFeed Organics FLAG screening blocks SBTi forest/land narrative completeness.",
      due: "2026-03-15",
      actionLabel: "Open supplier",
      target: "supplier",
      supplierName: "AgriFeed Organics",
    },
  ],
  exportConsignmentQueue: [
    {
      id: "cb1",
      batchRef: "IN-API-0328",
      product: "Inter-X HCl salt",
      cnCode: "2933 39 99",
      destination: "JNPT (Nhava Sheva)",
      status: "Complete",
      embeddedEmissionsTCO2e: 42.6,
      due: "2026-01-31",
    },
    {
      id: "cb2",
      batchRef: "IN-API-0331",
      product: "Inter-X HCl salt",
      cnCode: "2933 39 99",
      destination: "Mundra Port",
      status: "Evidence pending",
      due: "2026-01-20",
    },
    {
      id: "cb3",
      batchRef: "IN-API-0334",
      product: "Inter-X HCl salt",
      cnCode: "2933 39 99",
      destination: "Chennai Port",
      status: "Blocked",
      due: "2026-01-12",
    },
    {
      id: "cb4",
      batchRef: "IN-PKG-0102",
      product: "Sterile laminate rolls",
      cnCode: "3920 10 23",
      destination: "Visakhapatnam ICD",
      status: "Complete",
      embeddedEmissionsTCO2e: 8.1,
      due: "2026-01-31",
    },
  ],
  supplierPortal: {
    supplierId: "s2",
    supplierName: "PackWell Polymers Ltd",
    openTasks: [
      { id: "t1", label: "Upload ISCC PLUS certificate for recycled PP stream (PO PW-2025-1180–1194)", due: "2026-01-10", status: "Pending" },
      { id: "t2", label: "Confirm FY25 renewable electricity share (site-level) with utility attestation", due: "2025-12-20", status: "Submitted" },
      { id: "t3", label: "Complete export consignment attestation — ICEGATE-linked SKUs (DGFT pilot)", due: "2026-01-05", status: "Pending" },
      { id: "t4", label: "Respond to clarification on Q3 mass-balance lot trace (weeks 40–44)", due: "2026-01-18", status: "Pending" },
    ],
    recentSubmissions: [
      { id: "h1", label: "Q3 PCF refresh — laminates", submittedAt: "2025-10-02", outcome: "Accepted" },
      { id: "h2", label: "Packaging mass & BOM update", submittedAt: "2025-08-19", outcome: "Queries raised" },
    ],
  },
};

const scope3SuppliersResolved = scope3MockDataBase.suppliers.map(attachProcurementScope3Fields);

export const scope3MockData: Scope3MockData = {
  ...scope3MockDataBase,
  suppliers: scope3SuppliersResolved,
  submittedEvidences: mergeSubmittedEvidencesDeep(scope3MockDataBase.submittedEvidences),
  ghgGasInventory: buildGhgGasInventory({
    scope3Categories: scope3MockDataBase.scope3Categories,
    executive: scope3MockDataBase.executive,
    suppliers: scope3SuppliersResolved,
  }),
};
